### ISSUE TITLE
RMSD agglomerative clustering

### ISSUE THREAD

**Issue by RobertArbon** [msmbuilder/msmbuilder#1013]
Hi, 

I'm using ward clustering with RMSD metric:
`    clusterer = LandmarkAgglomerative(n_clusters=n_clusters,
                                      n_landmarks=n_clusters//10,
                                      linkage='ward', metric='rmsd',
                                      landmark_strategy='stride',
                                      random_state=None, max_landmarks=None,
                                      ward_predictor='ward')`
Question: does the RMSD algorithm remove translation and rotation before calculating the RMSD?  The libdistance.pdist is not documented.

Thanks!

**Comment by brookehus** [comment]
Hi,

You can see [here](https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/tests/test_libdistance.py#L151-L173) that the libdistance RMSD calculations are cross-checked with the mdtraj RMSD function, which you can read more about [in the docs](http://mdtraj.org/1.8.0/api/generated/mdtraj.rmsd.html) or [on github](https://github.com/mdtraj/mdtraj/tree/master/mdtraj/rmsd). I believe this implementation removes translation and rotation.

**Comment by RobertArbon** [comment]
Thanks - I didn't think to check the test files.
