### ISSUE TITLE
Negative eigenvalue timescales

### ISSUE THREAD

**Issue by RobertArbon** [msmbuilder/msmbuilder#1023]
#Hi, 

I notice you disregard negative eigenvalues when calculating timescales of an MSM.  

in `core.py/_solve_msm_eigensystem` you order the eigenvalues by their real part: 

```
    u, lv, rv = scipy.linalg.eig(transmat, left=True, right=True)
    order = np.argsort(-np.real(u))
```

and then in the timescale calculation in `msm.py/timecales_`  you let the `log` calculation produce `nan`'s:

```
        with np.errstate(invalid='ignore', divide='ignore'):
            timescales = - self.lag_time / np.log(u[1:])
```

Surely a negative eigenvalue (with index `k` in this example) represents an oscillation of the corresponding eigenstate with a timscale equal to 
```
timescales = - self.lag_time / np.log(np.abs(u[k]))
```

pyEmma (in msmtools `timescales_from_eigenvalues`) uses the absolute value of the eigenvalues. I wondering whether there is a reason you didn't take absolute values?

Thanks 

Rob

**Comment by RobertArbon** [comment]
I would add that this isn't necessarily a sampling problem.  This is a perfectly good transition matrix: 
```
array([[ 0.71897773,  0.28102227,  0.        ,  0.        ],
       [ 0.5       ,  0.        ,  0.5       ,  0.        ],
       [ 0.        ,  0.40177319,  0.09822681,  0.5       ],
       [ 0.        ,  0.        ,  0.43758573,  0.56241427]])
```
Which has the following eigenvalues: 
```
array([ 1.        ,  0.80040769, -0.55250873,  0.13171984])
```

**Comment by brookehus** [comment]
I can't comment on the specific motive in this case, but see additional discussion [here](https://github.com/markovmodel/PyEMMA/issues/159)

**Comment by RobertArbon** [comment]
thanks.
