### ISSUE TITLE
Sample GMRQ code does not work when dihedrals are directly given to the estimator

### ISSUE THREAD

**Issue by mkhoshle** [msmbuilder/msmbuilder#1042]
Hi, I am trying to get the following piece of code to work but It is not working.
Here is how the code looks like:
```
pipeline = Pipeline([('tica', tICA(n_components=5)),
                     ('clusterer', MiniBatchKMeans(n_clusters=1100)),
                     ('msm', MarkovStateModel(n_timescales=5))])
ss = ShuffleSplit(n_splits=10)
cv = GridSearchCV(pipeline, param_grid={'tica__lag_time': [1, 4, 16, 64]} )
cv.fit(diheds)
```
I have got my dihedrals separately and is stored into the numpy array diheds.
And diheds has shape (n_smaple, n_features).
Does anyone know what is the problem with the following code?
Thanks,

**Comment by brookehus** [comment]
Have you checked whether your `diheds` are a `msmbuilder.dataset` object? Can you get `tICA` to run on them outside of the pipeline? If your `diheds` are just one "trajectory", make sure that it is input into `tICA` as a one-element list, since the algorithm as implement reads lists of trajectories.

**Comment by mkhoshle** [comment]
It works totally fine with tICA outside of the pipeline! Yes, they are only one trajectory and I input them into tICA as a list! But I have no idea why this keeps giving this error to me!

**Comment by msultan** [comment]
Whats the exact error? Could you paste the traceback.

**Comment by mkhoshle** [comment]
Yes, when I have diheds as a numpy array of shape (n_smaple, n_features), I get the following error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-290-6a94bff7b5ab> in <module>()
----> 1 cv.fit(features)

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/model_selection/_search.py in fit(self, X, y, groups, **fit_params)
    636                                   error_score=self.error_score)
    637           for parameters, (train, test) in product(candidate_params,
--> 638                                                    cv.split(X, y, groups)))
    639 
    640         # if one choose to see train score, "out" will contain train score info

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self, iterable)
    777             # was dispatched. In particular this covers the edge
    778             # case of Parallel used with an exhausted iterator.
--> 779             while self.dispatch_one_batch(iterator):
    780                 self._iterating = True
    781             else:

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in dispatch_one_batch(self, iterator)
    623                 return False
    624             else:
--> 625                 self._dispatch(tasks)
    626                 return True
    627 

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in _dispatch(self, batch)
    586         dispatch_timestamp = time.time()
    587         cb = BatchCompletionCallBack(dispatch_timestamp, len(batch), self)
--> 588         job = self._backend.apply_async(batch, callback=cb)
    589         self._jobs.append(job)
    590 

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py in apply_async(self, func, callback)
    109     def apply_async(self, func, callback=None):
    110         """Schedule a func to be run"""
--> 111         result = ImmediateResult(func)
    112         if callback:
    113             callback(result)

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py in __init__(self, batch)
    330         # Don't delay the application, to avoid keeping the input
    331         # arguments in memory
--> 332         self.results = batch()
    333 
    334     def get(self):

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in __call__(self)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132 
    133     def __len__(self):

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py in <listcomp>(.0)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132 
    133     def __len__(self):

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/model_selection/_validation.py in _fit_and_score(estimator, X, y, scorer, train, test, verbose, parameters, fit_params, return_train_score, return_parameters, return_n_test_samples, return_times, error_score)
    433     try:
    434         if y_train is None:
--> 435             estimator.fit(X_train, **fit_params)
    436         else:
    437             estimator.fit(X_train, y_train, **fit_params)

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/pipeline.py in fit(self, X, y, **fit_params)
    255             This estimator
    256         """
--> 257         Xt, fit_params = self._fit(X, y, **fit_params)
    258         if self._final_estimator is not None:
    259             self._final_estimator.fit(Xt, y, **fit_params)

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params)
    220                 Xt, fitted_transformer = fit_transform_one_cached(
    221                     cloned_transformer, None, Xt, y,
--> 222                     **fit_params_steps[name])
    223                 # Replace the transformer of the step with the fitted
    224                 # transformer. This is necessary when loading the transformer

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/externals/joblib/memory.py in __call__(self, *args, **kwargs)
    360 
    361     def __call__(self, *args, **kwargs):
--> 362         return self.func(*args, **kwargs)
    363 
    364     def call_and_shelve(self, *args, **kwargs):

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/pipeline.py in _fit_transform_one(transformer, weight, X, y, **fit_params)
    587                        **fit_params):
    588     if hasattr(transformer, 'fit_transform'):
--> 589         res = transformer.fit_transform(X, y, **fit_params)
    590     else:
    591         res = transformer.fit(X, y, **fit_params).transform(X)

~/anaconda36/envs/tica/lib/python3.6/site-packages/msmbuilder/decomposition/tica.py in fit_transform(self, sequences, y)
    396         sequence_new : list of array-like, each of shape (n_samples_i, n_components)
    397         """
--> 398         self.fit(sequences)
    399         return self.transform(sequences)
    400 

~/anaconda36/envs/tica/lib/python3.6/site-packages/msmbuilder/decomposition/tica.py in fit(self, sequences, y)
    280         """
    281         self._initialized = False
--> 282         check_iter_of_sequences(sequences, max_iter=3)  # we might be lazy-loading
    283         for X in sequences:
    284             self._fit(X)

~/anaconda36/envs/tica/lib/python3.6/site-packages/msmbuilder/utils/validation.py in check_iter_of_sequences(sequences, allow_trajectory, ndim, max_iter)
     46                 value = False
     47                 break
---> 48         if not isinstance(X, md.Trajectory) and X.ndim != ndim:
     49             value = False
     50             break

AttributeError: 'str' object has no attribute 'ndim'
```
And when diheds is a list with only one element of shape (n_smaple, n_features), then I get the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-291-3ff54e373f1e> in <module>()
----> 1 cv.fit(diheds)

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/model_selection/_search.py in fit(self, X, y, groups, **fit_params)
    636                                   error_score=self.error_score)
    637           for parameters, (train, test) in product(candidate_params,
--> 638                                                    cv.split(X, y, groups)))
    639 
    640         # if one choose to see train score, "out" will contain train score info

~/anaconda36/envs/tica/lib/python3.6/site-packages/sklearn/model_selection/_split.py in split(self, X, y, groups)
    328                 ("Cannot have number of splits n_splits={0} greater"
    329                  " than the number of samples: {1}.").format(self.n_splits,
--> 330                                                              n_samples))
    331 
    332         for train, test in super(_BaseKFold, self).split(X, y, groups):

ValueError: Cannot have number of splits n_splits=3 greater than the number of samples: 1.
```

**Comment by msultan** [comment]
Do you only have 1 trajectory? I think the CV is done over **full trajectories** and you cant split a single trajectory.

**Comment by msultan** [comment]
The way around this would be to split the trajectory yourself. Also this step inherently assumes that both halves are at equilibrium.

**Comment by mkhoshle** [comment]
I have many trajectory segments from one simulation and I have calculated the dihedral angles from each segment and stored them into one unique array. What is this splitting for? Now that I have one big array of features what do I need to do to get this to work?

**Comment by brookehus** [comment]
The point of shuffle split cross-validation is to build the model on a fraction of your data and to then test the model results on the other half of your data. This way, the model can't overfit to the entire dataset. A better model is assumed to be a model that explains both the data it was trained on and the data it was tested on.

For the pipeline to work, your `diheds` need to be a list of multiple arrays, so that the shuffle split algorithm can choose which subset to be the test set and which to be the training set. For example, you can take your `diheds` and split it into 10 equal-sized numpy arrays, and then give the pipeline this 10-element list.

**Comment by mkhoshle** [comment]
Thanks! It works now. But, one more question: I got the above code from [paper](http://www.sciencedirect.com/science/article/pii/S0006349516310487) (Fig. 4) and in the sample GMRQ code they do not provide any lag time for MSM as is also shown in my code above. So, my question is that what happens to the MSM lag-time? The list I have provided is only for tiICA-lag time or will it be used for both tiICA and MSM?
If it is going to be used for both tICA and MSM then I think that will not be correct because based on the following [link](http://mpharrigan.com/2016/09/29/gmrq.html) we can not optimize the MSM lag-time parameter. Is that right?

**Comment by msultan** [comment]
The MSM lagtime defaults to a value of 1 frame. If you want a higher lagtime change the CV code to be ``` ('msm', MarkovStateModel(lag_time=X, n_timescales=5))``` where X is your MSM lagtime. The code only runs CV over the provided param_grid, and only over the tICA lagtime in your setup. For actually picking your lag time, I would recommend making an initial model using some reasonable paramters to get an idea about when the models start becoming Markovian and using a lagtime equal to higher than that. 

And ,yes, you are right that you cannot optimize over MSM lagtimes using GMRQ. @brookehus wrote a short [letter](https://arxiv.org/abs/1708.08120) recently that shows exactly why.

**Comment by mkhoshle** [comment]
Awsome, thank you. So finally when I want to look at relaxation time scale vs lag-time what lag-time do I need to use for that? For example in t = - lag_time/log(Lambda) , Lambda is from MSM and lag_time is tICA lag_time? or should it be MSM Lambda and MSM lag_time? 
Sorry, I am totally new to this.

**Comment by brookehus** [comment]
Given that the MSM is your final kinetic model (as opposed to the tICA model), the tICA parameters are only intermediate for the tICA step only. Once you have gone from the tICA representation to the k-means representation, you do not need to ever incorporate the tICA lag time again.

Relaxation timescales are calculated from the MSM using the MSM lag time and the MSM eigenvalues!

**Comment by mkhoshle** [comment]
Ok, thank you. And for the initial guess of the initial lag-time, how do you Markovianity of a model and how can I say that at this lag-time my system will be Markovian? Is there any parameter that measure this?

**Comment by brookehus** [comment]
You plot the timescales of the model for various lag times and see when the plot levels out. See example code [here](https://github.com/msmbuilder/msmbuilder/blob/master/examples/advanced/implied-timescales.ipynb) and [here](https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/project_templates/msm/timescales-plot.py), and a discussion [here](https://github.com/msmbuilder/msmbuilder/issues/953). We suggest using log scales on both axes and increasing lag times on a log scale.

It is helpful to plot the identity function also, because when your longest timescale is your lag time it means that your model is not resolving any of your dynamics. In practice we need to balance (1) a model at useful resolution with (2) relatively flat timecales.

**Comment by cxhernandez** [comment]
You can also use [MSMExplorer](https://github.com/msmexplorer/msmexplorer)'s to [plot these more easily](http://msmbuilder.org/msmexplorer/development/examples/plot_implied_timescales.html). And here's a notebook with a real-world example: http://msmbuilder.org/msmexplorer/development/notebooks/Fs-Peptide.html#Construct-MSM
