### ISSUE TITLE
Performing tICA on a single trajectory

### ISSUE THREAD

**Issue by sbhakat** [msmbuilder/msmbuilder#1054]
I have a single trajectory and a corresponding pdb file and I just want to try the tICA analysis on it. From msmb tICA help command I got the following inputs
  -i INP, --inp INP     Input dataset. This can either be a glob pattern for
                        trajectories (if using metric='rmsd'), or a dataset
                        containing a collection of .npy files, for other
                        metrics.

output:
  use one or both of the following

  -o OUT, --out OUT     Path to save fit model instance. This is the model,
                        after parameterization with fit(), saved using the
                        pickle protocol
  -t TRANSFORMED, --transformed TRANSFORMED
                        Path to output transformed dataset. This will be a
                        collection of arrays, as transfomed by the model

Parameters:
  --n_components N_COMPONENTS
                        Number of components to keep.
  --lag_time LAG_TIME   Delay time forward or backward in the input data. The
                        time-lagged correlations is computed between datas
                        X[t] and X[t+lag_time]. (default: 1)
  --shrinkage SHRINKAGE
                        The covariance shrinkage intensity (range 0-1). If
                        shrinkage is not specified (the default) it is
                        estimated using an analytic formula (the Rao-
                        Blackwellized Ledoit-Wolf estimator) introduced in
                        [5].
  --kinetic_mapping, --no-kinetic_mapping
                        If True, weigh the projections by the tICA
                        eigenvalues, yielding kinetic distances as described
                        in [6].
  --commute_mapping, --no-commute_mapping
                        If True, scale/weigh the projections by the
                        sqrt(ti/2), yielding commute distance as described in
                        [7].

When I executed the command 

> msmb tICA -i traj_r1.xtc -o traj -t trans --n_components 5 --kinetic_mapping

 it gives an error 

> ValueError: "top" argument is required for load_xtc

But I didn't see any use of top argument in tICA help but anyway I ran the following 

msmb tICA -i traj_r1.xtc -o traj -t trans --n_components 5 --kinetic_mapping  --top top.pdb

which gives an error

> msmb: error: unrecognized arguments: --top top.pdb

Am I doing it completely wrong or what is the problem? Sorry I am new to python and msmbuilder.

**Comment by brookehus** [comment]
When using tICA on a MD trajectory, you are going to need to "featurize" the trajectory first. We have many options to do this. If you really want the x, y, z, coordinates (not recommended!), then you will want to use `RawPositionsFeaturizer`  before applying tICA. This means that you will be applyign tICA to the features, not to the `xtc` file. If you have a protein, we like the `DihedralFeaturizer` or the `ContactFeaturizer`. Please have a look at some of our [example notebooks](https://github.com/msmbuilder/msmbuilder/tree/master/examples) to see how this is done.

**Comment by sbhakat** [comment]
Question again:

1. When traditionally people do PCA analysis using Gromacs tool I guess they use similar to > `RawPositionsFeaturizer` that means the x, y, z, coordinates. Then why it is not recommended?
2. I have a big protein and the motions are not dominated by any dihedral collective variable. So I am not sure why to use > DihedralFeaturizer or even > ContactFeaturizer . My guess will be to use either > RawPositionsFeaturizer or > RMSDFeaturizer . Can you explainwhat leads you to suggest the above two explanations?
3. Error again. This time it is silly. When I used this command `msmb PCA -h` it gives following error

> /Users/sbhakat/anaconda/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
>   "This module will be removed in 0.20.", DeprecationWarning)
> /Users/sbhakat/anaconda/lib/python3.6/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
>   DeprecationWarning)
> /Users/sbhakat/anaconda/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
>   from pandas.core import datetools
> An unexpected error has occurred with MSMBuilder (version 3.7.0), please
> consider sending the following traceback to MSMBuilder GitHub issue tracker at:
>             https://github.com/msmbuilder/msmbuilder/issues
> 
> Traceback (most recent call last):
>   File "/Users/sbhakat/anaconda/bin/msmb", line 6, in <module>
>     sys.exit(msmbuilder.scripts.msmb.main())
>   File "/Users/sbhakat/anaconda/lib/python3.6/site-packages/msmbuilder/scripts/msmb.py", line 27, in main
>     app = MSMBuilderApp(name='MSMBuilder', description=__doc__)
>   File "/Users/sbhakat/anaconda/lib/python3.6/site-packages/msmbuilder/cmdline.py", line 452, in __init__
>     self.args = self.parser.parse_args(argv)
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 1730, in parse_args
>     args, argv = self.parse_known_args(args, namespace)
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 1762, in parse_known_args
>     namespace, args = self._parse_known_args(args, namespace)
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 1950, in _parse_known_args
>     positionals_end_index = consume_positionals(start_index)
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 1927, in consume_positionals
>     take_action(action, args)
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 1836, in take_action
>     action(self, namespace, argument_values, option_string)
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 1133, in __call__
>     subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 1762, in parse_known_args
>     namespace, args = self._parse_known_args(args, namespace)
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 1968, in _parse_known_args
>     start_index = consume_optional(start_index)
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 1908, in consume_optional
>     take_action(action, args, option_string)
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 1836, in take_action
>     action(self, namespace, argument_values, option_string)
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 1020, in __call__
>     parser.print_help()
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 2362, in print_help
>     self._print_message(self.format_help(), file)
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 2346, in format_help
>     return formatter.format_help()
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 282, in format_help
>     help = self._root_section.format_help()
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 213, in format_help
>     item_help = join([func(*args) for func, args in self.items])
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 213, in <listcomp>
>     item_help = join([func(*args) for func, args in self.items])
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 213, in format_help
>     item_help = join([func(*args) for func, args in self.items])
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 213, in <listcomp>
>     item_help = join([func(*args) for func, args in self.items])
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 519, in _format_action
>     help_text = self._expand_help(action)
>   File "/Users/sbhakat/anaconda/lib/python3.6/argparse.py", line 606, in _expand_help
>     return self._get_help_string(action) % params
> TypeError: %o format: an integer is required, not dict

Any idea how to solve it?

**Comment by brookehus** [comment]
First, MSMBuilder is much nicer to run from a [Jupyter notebook](http://jupyter.org/), so consider switching your analysis tools to that style while you are still learning the software.

Second, please use `conda install msmbuilder -c omnia` to download the latest release of MSMBuilder, since you are still running 3.7. Then report what the error is. Try calling `msmb -h` first.

For your initial questions, I assumed you were trying to build a MSM for a protein. Depending on what you are doing, different analysis tools will be useful. What is your system? Are you ultimately trying to build a MSM? For building a MSM to describe protein folding, I have written a lot about these choices in a [recent publication](http://dx.doi.org/10.1063/1.4967809). If you are looking at conformational change, @msultan might have some insight.

**Comment by sbhakat** [comment]
I am not trying to make MSM for a protein. I am just only interested in dumping first two TICA coordinates in a pdb file and compare it with my PC1 and PC2 pdb files. My aim is to use TICA vs PCA as a collective variable in enhanced sampling simulation to see which one performs better.

One suggestion: Why not give an output option of `.xtc` file as part of `msmb tICA` command besides the standard `.h5` command. That will make life much smoother.

**Comment by msultan** [comment]
Hmm, i am not sure how you are getting pdbs for PCA? PCA is a linear combination of input features that explains the variance in the current dataset the best. I dont know how you would be able to get a pdb file from that or what the pdb file even means? 


Does the PDB file encode multiple structures with weights for each structure and the rest is handled by the sampling software?

**Comment by msultan** [comment]
Also, I have written some code for converting an MSMBuilder tICA object directly into Plumed code here. That might be useful for you. It will also work with PCA objects, and work with pretty much any MSMBuilder's featurizer object. 

https://github.com/msultan/tica_metadynamics/blob/master/tica_metadynamics/plumed_writer.py#L368

**Comment by msultan** [comment]
For example for alanine the following works for the output space 
```bash
RESTART 
TORSION ATOMS=5,7,9,15 LABEL=phi_0_1 
TORSION ATOMS=7,9,15,17 LABEL=psi_1_2 
MATHEVAL ARG=phi_0_1 FUNC=sin(x)--0.815241623066 LABEL=sin_phi_0_1 PERIODIC=NO 
MATHEVAL ARG=phi_0_1 FUNC=cos(x)--0.131125790906 LABEL=cos_phi_0_1 PERIODIC=NO 
MATHEVAL ARG=psi_1_2 FUNC=sin(x)-0.286726096227 LABEL=sin_psi_1_2 PERIODIC=NO 
MATHEVAL ARG=psi_1_2 FUNC=cos(x)--0.314836222992 LABEL=cos_psi_1_2 PERIODIC=NO 
COMBINE LABEL=tic_0 ARG=sin_phi_0_1,cos_phi_0_1,sin_psi_1_2,cos_psi_1_2 COEFFICIENTS=3.78464062942,0.984827650367,0.239609635308,0.21932004493 PERIODIC=NO 
METAD ARG=tic_0 SIGMA=0.1 HEIGHT=0.2 FILE=HILLS PACE=1000 LABEL=metad 
PRINT ARG=tic_0,metad.bias STRIDE=1000 FILE=COLVAR
```
You can replace the ```COEFFICIENTS``` with the PCA coefficients and sample the principal component.

**Comment by msultan** [comment]
Also, the following script can train a single trajectory model for you. Just replace the tICA parameters with whatever you think is best for your system. 

https://github.com/msultan/tica_metadynamics_paper_1/blob/master/alanine_examples/full_md_mdl/train.py

**Comment by msultan** [comment]
@sbhakat Can I close this now?

**Comment by aasthajhunjhunwala** [comment]
I load my trajectories as follows:
**trajectory_folder_path = os.path.abspath("trajectories")**
**ds = dataset(trajectory_folder_path + "/*.dcd", topology='system.pdb', stride=10)**

However, I'm not sure how to save my pdb after performing TiCA. 
I was referring to [This work:](https://www.researchgate.net/publication/312203330_MSMBuilder_Statistical_Models_for_Biomolecular_Dynamics) for most part of the analysis, however this uses .h5 files for saving the pdb, I'm not sure of the relevant changes for saving the pdb incase of a .dcd files dataset.

Any leads will be much appreciated!
