### ISSUE TITLE
Question about msm.io.sampling sample_msm

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/msmbuilder#1055]
I want to double check with you if I should be passing all the cluster centers in the clusterer object to the `state_centers` parameter of the [`sample_msm`](https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/io/sampling/sampling.py#L76) function, or rather the centers of the microstates which are in the ergodic phase space retrieved by the msm?

I think since the function is making use of the `sample_discrete` method of the MSM, this should be centers with internal numbering of the MSM. But I get an error in the function if I pass the cluster centers that have been retained in the MSM:

```python
clusterer.n_clusters
>>> 1000
msm.n_states_
>>> 926
# Pass all the centers in the clusterer object
sample_msm(tt, clusterer.cluster_centers_, msm, n_steps=20)
>>> [(30, 1158),
 (2, 3260),
...
 (31, 2717),
 (14, 7278)]
# Now only pass the centers in the MSM
sample_msm(tt, clusterer.cluster_centers_[msm.state_labels_], msm, n_steps=20)
>>> ---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-46-3746d8fb2250> in <module>()
----> 1 sample_msm(tt, clusterer.cluster_centers_[msm.state_labels_], msm, n_steps=20)

~/Projects/msmbuilder/msmbuilder/io/sampling/sampling.py in sample_msm(trajs, state_centers, msm, n_steps, state, stride, random_state)
     83 
     84     tree = KDTree(trajs)
---> 85     dists, inds = tree.query(state_centers[untrimmed_ktraj, :], k=1)
     86     return [(fixed_indices[i], j) for i, j in inds]

IndexError: index 993 is out of bounds for axis 0 with size 926
```
Do you have any guidance on this?

Thanks in advance 😄

**Comment by brookehus** [comment]
I don't know anything about this specific method, but given your error, it seems reasonable to choose cluster centers for the ergodic trimming as you've suggested, i.e.

```
trimmed_clus_centers = [c for i, c in enumerate(clusterer.cluster_centers_) if i in msm.mapping_.keys()]
```

**Comment by jeiros** [comment]
Hi @brookehus , I don't know if I understood you correctly. Your suggested code does the same thing as `clusterer.cluster_centers_[msm.state_labels_]` only that it returns a list of arrays, instead of a single array.

If I pass it like this, I get a TypeError:
```python
sample_msm(tt, trimmed_clus_centers, msm, n_steps=20)
>>> ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-30b826fa818c> in <module>()
----> 1 sample_msm(tt, trimmed_clus_centers, msm, n_steps=20)

~/Projects/msmbuilder/msmbuilder/io/sampling/sampling.py in sample_msm(trajs, state_centers, msm, n_steps, state, stride, random_state)
     83 
     84     tree = KDTree(trajs)
---> 85     dists, inds = tree.query(state_centers[untrimmed_ktraj, :], k=1)
     86     return [(fixed_indices[i], j) for i, j in inds]

TypeError: list indices must be integers or slices, not tuple
```
I'm pretty sure `msm.sample_discrete` expects the `state` argument to be in the labeling of the `clusterer` object. For instance, my msm only has 926 centers out of the 1000 that were used in the clusterer. I can see in the `msm.mapping_` dictionary that cluster 19 is dropped in the ergodic trimming:
```python
msm.mapping_
>>> {0: 0,
 1: 1,
 2: 2,
 3: 3,
 4: 4,
 5: 5,
 6: 6,
 7: 7,
 8: 8,
 9: 9,
 10: 10,
 11: 11,
 12: 12,
 13: 13,
 14: 14,
 15: 15,
 16: 16,
 17: 17,
 18: 18,
 20: 19,
...
msm.sample_discrete(state=19)
>>> ---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-47-fbdab5079dd0> in <module>()
----> 1 msm.sample_discrete(state=19, n_steps=2)

~/Projects/msmbuilder/msmbuilder/msm/core.py in sample_discrete(self, state, n_steps, random_state)
    254             initial = np.sum(np.cumsum(state) < r[0])
    255         else:
--> 256             initial = self.mapping_[state]
    257 
    258         cstr = np.cumsum(self.transmat_, axis=1)

KeyError: 19
```
So I guess that solves it, all the cluster centers have to be passed and then internally the function takes care of finding the trimmed clusters.

**Comment by brookehus** [comment]
Ok, I misunderstood your question! My bad. I am not familiar with this part of the code at all so if you have other problems others can chime in.

**Comment by msultan** [comment]
Hmm, I will need to look into it in more detail to be sure . @jeiros is the result deterministic? I.e do the same tuples appear twice in the list? 

So the [sample_discrete](https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/msm/core.py#L216) function naturally does the inverse transform for you. And you are right that it does the mapping internally for you so just give it the cluster center that you would like to start from ( or leave None) in which case it picks the highest populated state. So start the MSM sample using what ever clusterer state you want. it will handle it internally unless that state has been discarded in which case it will throw an error.

**Comment by jeiros** [comment]
How can I check if it is deterministic? I am not sure I understand your question.

**Comment by msultan** [comment]
oh, i was just wondering if you run the same code again if it gives slightly different results. For now, i would recommend simply using the unmapped state to start the sampling.

**Comment by msultan** [comment]
Closing this now. Feel free to open another issue later on.
