### ISSUE TITLE
fit method of MarkovStateModel: ValueError: Likelihood not converged. Error code=-3

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/msmbuilder#1059]
I've noticed from time to time that some of the MSMs that I build, specially the ones with long lag times, fail to converge the MLE estimation. 

~~What is weird is that it is not reproducible.~~

I've got a dict of integer labeled trajs `wt_ktrajs` coming from a 1000 step clustering MiniBatchKMeans step on a tICA space, the usual stuff. Overall it's around 35 microseconds of data. 
```python
msm = MarkovStateModel(lag_time=500, n_timescales=10, verbose=True)
msm.fit(list(wt_ktrajs.values()))
```
```
MSM contains 50 strongly connected components above weight=0.00. Component 12 selected, with population 99.906401%
MarkovStateModel(ergodic_cutoff='on', lag_time=500, n_timescales=10,
         prior_counts=0, reversible_type='mle', sliding_window=True,
         verbose=True)
```
```python
print(msm.summarize())
```
```
Markov state model
------------------
Lag time         : 500
Reversible type  : mle
Ergodic cutoff   : on
Prior counts     : 0

Number of states : 838
Number of nonzero entries in counts matrix : 13499 (1.9222663347782252%)
Nonzero counts matrix entries:
    Min.   : 0.0
    1st Qu.: 0.0
    Median : 0.0
    Mean   : 0.0
    3rd Qu.: 0.0
    Max.   : 1.1

Total transition counts :
    306.47 counts
Total transition counts / lag_time:
    0.61294 units
Timescales:
    [22062977.70, 11166987.26, 3694134.76, 2178853.19, 1438768.40, 328939.84, 195744.90, 69117.19, 59211.29, 48373.75]  units
```
Now if I want to try different lag times:
```python
lagtimes = [
    10, # 2ns
    100, # 20 ns
    250, # 50 ns 
    500, # 100 ns
]
for lt in lagtimes:
    msm = MarkovStateModel(lag_time=lt, n_timescales=10, verbose=True)
    msm.fit(list(wt_ktrajs.values()))
```
```
MSM contains 2 strongly connected components above weight=0.10. Component 0 selected, with population 100.000000%
MSM contains 11 strongly connected components above weight=0.01. Component 1 selected, with population 99.997689%
MSM contains 21 strongly connected components above weight=0.00. Component 4 selected, with population 99.982514%

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-d35a27366151> in <module>()
      1 for lt in lagtimes:
      2     msm = MarkovStateModel(lag_time=lt, n_timescales=10, verbose=True)
----> 3     msm.fit(list(wt_ktrajs.values()))

~/Projects/msmbuilder/msmbuilder/msm/msm.py in fit(self, sequences, y)
    171             fit_method = fit_method_map[str(self.reversible_type).lower()]
    172             # step 3. estimate transition matrix
--> 173             self.transmat_, self.populations_ = fit_method(self.countsmat_)
    174         except KeyError:
    175             raise ValueError('reversible_type must be one of %s: %s' % (

~/Projects/msmbuilder/msmbuilder/msm/msm.py in _fit_mle(self, counts)
    185 
    186         transmat, populations = _transmat_mle_prinz(
--> 187             counts + self.prior_counts)
    188         return transmat, populations
    189 

~/Projects/msmbuilder/msmbuilder/msm/_markovstatemodel.pyx in msmbuilder.msm._markovstatemodel._transmat_mle_prinz()

ValueError: Likelihood not converged. Error code=-3
```
As you can see the MSM with lag time 500 frames fails to converge in this case.

This seems a bit weird to me because:
- It did not fail in the previous step where I fit it outside a loop
- The retrieved space seems to be quite large (>99%) so it should have plenty of data to fit?

In this particular example, the MSM has been built with a `ContactFeaturizer` between a handful of residues, which I think should have fast enough internal dynamics to be well sampled.

Do you know what could be the issue?

**Comment by jeiros** [comment]
Actually, I take that back.

The MSM that is failing is the one at 250 frames (the verbose print only shows three times).

But the question is then, why does convergence of a lower lag time MSM fail when it succeeds for one with double lag time? Isn't the longer one essentially using half the data? I expected the longer ones to have more issues with fitting... Where is my intuition wrong?

**Comment by msultan** [comment]
I think it has something to do with how the counts matrix is built and whether an MLE transition matrix can be obtained from it. My guess is that at the higher lag, it is getting rid of some troublesome state which is why its able to fit it in the first place.

**Comment by msultan** [comment]
A BAD fix would be to use the the transpose as the reversible estimator. I DONT recommend this since it enforces structure onto your transition matrix that wouldnt exist otherwise. 

A better solution would be try a different clustering scheme with lower resolution so that it can build a more robust counts matrix. 

Another solution would be find the trouble some set of states and get more sampling there. Which honestly would help in general for pretty much every protein.

**Comment by jeiros** [comment]
Yeah, the 'more sampling' through MSMs is what I do. Each time I get a new batch of data, I re-build the MSM and detect the states in the matrix which have the lowest amount of outwards counts in the count matrix, and spawn new simulations from them.
The thing is this data set already has taken me over a year to generate 😅 , since my solvated system is quite big and I only have access to a handful of GPUs.

I'll try the more fine-grained clustering and see what happens, thanks for the suggestion!

**Comment by msultan** [comment]
Closing this now. Feel free to open another issue later on.
