### ISSUE TITLE
[question] 'Unlikely unit cell vectors detected in PDB file likely '

### ISSUE THREAD

**Issue by AlirezaTafazzol** [msmbuilder/msmbuilder#1065]
@mpharrigan 
I am following the Tutorial (http://msmbuilder.org/3.8.0/tutorial.html) and I get the following error on part 8 of Tutorial when running "python featurize.py"

/home/ali/anaconda2/lib/python2.7/site-packages/mdtraj/formats/pdb/pdbfile.py:196: UserWarning: Unlikely unit cell vectors detected in PDB file likely resulting from a dummy CRYST1 record. Discarding unit cell vectors.
  warnings.warn('Unlikely unit cell vectors detected in PDB file likely '
Traceback (most recent call last):
  File "featurize.py", line 30, in <module>
    with Pool() as pool:
AttributeError: __exit__

I have not changed the PDB file and just followed the steps in the Tutorial. How can I fix it?

**Comment by cxhernandez** [comment]
This is a compatibility issue with Python 2.7. See here for more [info](https://stackoverflow.com/a/27065238).

Your two options are to switch to Python 3.3+ or edit `featurize.py` at line 30:

```python
from contextlib import closing
with closing(Pool()) as pool:
    ...
```

**Comment by msultan** [comment]
Closing this now. Feel free to open another issue later on.
