### ISSUE TITLE
MSMExplorer: No module named 'basesetup'

### ISSUE THREAD

**Issue by AlirezaTafazzol** [msmbuilder/msmbuilder#1066]
I tried to install msmexplorer but I got the error of "No module named 'basesetup'" that I could not find any solution for that on Google.

[ali@fermi Desktop]$ pip install msmexplorer
Collecting msmexplorer
  Using cached msmexplorer-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-467t3lee/msmexplorer/setup.py", line 15, in <module>
        from basesetup import write_version_py
    ModuleNotFoundError: **No module named 'basesetup'**
        ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-467t3lee/msmexplorer/

[ali@fermi Desktop]$ **pip install basesetup**
Collecting basesetup
  Could not find a version that satisfies the requirement basesetup (from versions: )
**No matching distribution found for basesetup**

**Comment by cxhernandez** [comment]
Please raise this issue in the MSMExplorer issue tracker: https://github.com/msmbuilder/msmexplorer/issues

**Comment by cxhernandez** [comment]
This is definitely a bug with the latest version on pypi. I'd recommend using an Anaconda distribution of Python and installing via conda:

```
$ conda install -c omnia msmexplorer
```

**Comment by AlirezaTafazzol** [comment]
$conda install -c omnia msmexplorer
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - msmexplorer
  - numba
Use "conda info <package>" to see the dependencies for each package.

**Comment by mohamedmarzouk22** [comment]
Thank u this command solve the problem 
$ conda install -c omnia msmexplorer
