### ISSUE TITLE
Problems about MSMBuilder especially for .mdcrd trajectory, thanks

### ISSUE THREAD

**Issue by Nidane** [msmbuilder/msmbuilder#1067]
1. I read about the protocol of the software provided on the website (http://msmbuilder.org/3.8.0/index.html), and if I am not mistaken, I think in both the Tutorial and Examples parts, the protocol give a brief introduction on how to build up a MSM model with the help of tICA and I think their results will be the same. I am not sure whether my understanding is correct?

2. As is mentioned above, the Tutorial part gives a brief introduction about how to build a MSM model with the help of tICA, and I have read about several articles using MSMBuilder and most of them also employed tICA for the constrcution of MSM model. I am not sure whether I can build a MSM model with the help of PCA or other methods. If I can, where can I find the related python script for it? 

3. In the diagram of the workflows of MSMBuilder, it is said that Bayesian MSM, MLE MSM and Rate Matrix MSM can all be built, but I am not sure where I can find the protocal for building these kinds of MSM and the MSM built based on the Tutorial provided on the website mentioned above is a simple MSM, I suppose?

4. According to the Tutorial, the software uses diherals angles as features to reduce dimensionality and I wonder how can I choose other parameters such as RMSD, landmarks, or diherals angles other than chi1 and chi2 (eg. phi and psi) for the purpose of reducing dimensionality? Does the software support such setting? and where can I find the relevant protocol or python script?

5. At the end of the MSMBuilder Tutorial, a sample trajectory will be generated from the MSM, and I wonder what does this trajectory mean? I think it is a trajectory of several microstates of the MSM model that we build, but I am not sure whether my understanding is correct? 

6. How to use the MSMBuilder to analyze trajectories in the ".mdcrd" format?

**Comment by brookehus** [comment]
Please take the time to search for your answers in our documentation before asking on the issues page. Many of these answers are very easy to find.

> I am not sure whether I can build a MSM model with the help of PCA or other methods. If I can, where can I find the related python script for it?

Please see the docs [here](http://msmbuilder.org/3.8.0/decomposition.html).

> In the diagram of the workflows of MSMBuilder, it is said that Bayesian MSM, MLE MSM and Rate Matrix MSM can all be built, but I am not sure where I can find the protocal for building these kinds of MSM

Please see the docs [here](http://msmbuilder.org/3.8.0/msm.html). Continuous time MSMs are described [here](http://msmbuilder.org/3.8.0/ratematrix.html).

> MSM built based on the Tutorial provided on the website mentioned above is a simple MSM, I suppose?

`MarkovStateModel` is the standard MSM. For an example of a `ContinuousTimeMSM`, see the notebook [here](https://github.com/msmbuilder/paper/blob/master/1-src/ipynbs/src_kinase_msmb_paper_mdl_creation.ipynb) from the [MSMBuilder paper](https://www.biorxiv.org/content/early/2016/10/30/084020).

> According to the Tutorial, the software uses diherals angles as features to reduce dimensionality and I wonder how can I choose other parameters such as RMSD, landmarks, or diherals angles other than chi1 and chi2 (eg. phi and psi) for the purpose of reducing dimensionality?

Please see the documentation [here](http://msmbuilder.org/3.8.0/featurization.html). Your question about the dihedral featurizer can be answered [here](http://msmbuilder.org/3.8.0/_featurization/msmbuilder.featurizer.DihedralFeaturizer.html#msmbuilder.featurizer.DihedralFeaturizer).

> At the end of the MSMBuilder Tutorial, a sample trajectory will be generated from the MSM, and I wonder what does this trajectory mean? I think it is a trajectory of several microstates of the MSM model that we build, but I am not sure whether my understanding is correct?

The MSM is a transition probability matrix that contains the probability of transitioning from any state to any other state. The sample trajectory chooses a starting state, and then takes as many steps as you designate in a stochastic way according to the MSM transition probability matrix.

> How to use the MSMBuilder to analyze trajectories in the ".mdcrd" format?

You will have to load this using [mdtraj](https://github.com/mdtraj/mdtraj). See an example [here](https://github.com/mdtraj/mdtraj/blob/master/tests/test_mdcrd.py), where `n_atoms` is passed to the loader.

**Comment by Nidane** [comment]
thank you very much for your answers, for part of the problems, i have read about the related content in the protocol that you provided on the website but I just want to know whether there are related tutorial or examples or scripts rather than the theory. thank you.

**Comment by brookehus** [comment]
I suggest looking at the two python notebooks used as examples for the msmbuilder paper, which are linked [here](https://github.com/msmbuilder/paper/blob/master/1-src/ipynbs/src_kinase_msmb_paper_mdl_creation.ipynb) and [here](https://github.com/msmbuilder/paper/blob/master/2-gmrq/gmrq.ipynb). There are also lots more examples [here](https://github.com/msmbuilder/msmbuilder/tree/master/examples).

**Comment by Nidane** [comment]
thank you for your help and I still have one question about the mdtraj and the test_mdcrd.py file, do I need to load it before I carry out the construction of my MSM or how to use it otherwise? thanks

**Comment by cxhernandez** [comment]
Yes, you need to load the mdcrd trajectory using MDTraj in order to carry out analysis in MSMBuilder:

```python
import mdtraj
from msmbuilder.featurize import DihedralFeaturizer
from msmbuilder.cluster import KMeans
from msmbuilder.msm import MarkovStateModel

traj = md.load('my_trajectory.mdcrd', top='my_topology.prmtop')

featurizer = DihedralFeaturizer(types=['phi', 'psi'], sincos=True)
features = featurizer.transform(traj)

clusterer = KMeans(n_clusters=8)
labels = clusterer.fit_transform(features)

msm = MarkovStateModel(lag_time=10)
msm_labels = msm.fit_transform(labels)
```

**Comment by brookehus** [comment]
Note that you do not need the test_mdcrd file at all. That was just to show you an example of how loading .mdcrd files works.

**Comment by r7Mozart** [comment]
excuse me, I wonder would you please show me a complete version of python script for loading trajectories in .mdcrd format and building up the MSM model ? Thank you!

**Comment by brookehus** [comment]
Use the script Carlos pasted above.

**Comment by r7Mozart** [comment]
I have read about the script he posted but I am not sure. I think his script contains various part such as featurization, clustering and building up MSM. Whether I should run this script directly or edit multiple scripts in the Tutorial for different steps based on the script he pasted ?? Thank you.

**Comment by brookehus** [comment]
Before you run MSMBuilder on your own system, make sure you can complete and understand one of the tutorials. Choose one of the fs-peptide tutorials listed [here](https://github.com/msmbuilder/msmbuilder/tree/master/examples) according to your preferences (command line, pipeline, dataset). Make sure you can complete it and understand it, and then apply it to your own system. We are happy to help with msmbuilder bugs but for general familiarity with python please seek other resources.
