### ISSUE TITLE
[questions] how to deal with .mdcrd trajectory instead of .xtc ?

### ISSUE THREAD

**Issue by Nidane** [msmbuilder/msmbuilder#1068]
I try to analyze trajectories in .mdcrd format but the server shows "ParseWarning: Could not determine the number of frames for trajss/trajectory-146.mdcrd: To open a mdcrd file in mode="r", you must supply the number of atoms, "n_atoms" " and I wonder how I can deal with this problem? thank you!

**Comment by brookehus** [comment]
Please paste the code that gave you the warning. The warning is pretty unambiguous: try adding `n_atoms=x` for however many atoms you have to the function.

**Comment by Nidane** [comment]
thank you and the error is as follows:
/home/customer/anaconda2/lib/python2.7/site-packages/msmbuilder/io/gather_metadata.py:84: ParseWarning: Could not determine the number of frames for trajss/trajectory-146.mdcrd: To open a mdcrd file in mode="r", you must supply the number of atoms, "n_atoms"
  .format(fn, e), ParseWarning)
that's what I get when I type in "python gather-metadata.py"

**Comment by brookehus** [comment]
You are going to have to change the `gather-metadata.py` script for your file format.

**Comment by Nidane** [comment]
change the .py script in line 84 i suppose? or use the "mdtraj" instead? for the former one, i guess i have to add n_atoms=** directly on that line and as for the latter one, i guess i have to run mdtraj first before building my MSM model ? thank you !

**Comment by brookehus** [comment]
You can try to edit the tutorial, or you can code it yourself. [Here](https://github.com/msmbuilder/paper/blob/master/2-gmrq/gmrq.ipynb) is an example where a trajectory is loaded using mdtraj. When a trajectory is loaded into msmbuilder, it uses the software mdtraj under the hood, although this may not be immediately obvious from the tutorial.

**Comment by Nidane** [comment]
I have tried and edited the "gather-metadata.py" script as follows:
(in line 83-84)
warnings.warn("Could not determine the number of Frames for { }: { }"
                       .format(fn, "natoms=2667"), ParseWarning)
and it comes out as:
ParseWarning: Could not determine the number of Frames for ......
and I wonder how to deal with this now, thank you!

**Comment by Nidane** [comment]
Also,  in the original python script "gather-metadata.py", at the beginning, "mdtraj" has already been imported, it goes as follows:
import glob
import os
import re
import warnings

import mdtraj as md
import pandas as pd
..........
so I guess in the original python script, the trajectories were already loaded with MDTraj? but still it shows error with the "n_atoms" issue
thank you!

**Comment by brookehus** [comment]
Read the error message and do what it says: supply the number of atoms using n_atoms.

**Comment by Nidane** [comment]
I read about this and edited the script line82-line84 as below:
except Exception as n_atoms:
      warnings.warn("Could not determine the number of Frames for { }: { }"
                             .format(fn, "natoms=2667"), ParseWarning)
and it comes to "ParseWarning: Could not determine the number of Frames for ......" ??

**Comment by brookehus** [comment]
I'm not too familiar with that error. @msmbuilder/developers feel free to chime in. Otherwise it seems like the pipeline setup may not be ideal for you. I suggest following my advice in my most recent comment in #1067. Choose an fs-peptide tutorial [here](https://github.com/msmbuilder/msmbuilder/tree/master/examples) and make sure you can complete it and understand it. Maybe if you need to edit code the pipeline is not the best way to do it, and you should consider the dataset version. We can help you with msmbuilder but it's difficult to walk you through line by line; seek some other resources for more comfort with python.

**Comment by Nidane** [comment]
the tutorial for fs_peptide can be carried out successfully but when I try to cope with my own trajectories which are in mdcrd format problems occurs. I try to edit the code in the tutorial by simply replacing the code related to xtc file with the ones related to mdcrd file but still the software comes out warning and ask me to enter the "n_atoms" or the "could not determine the number of Frames..." here. I am not very familiar with python script since I am only an undergraduate in biomedical science and I am seeking for other solutions for these issues such as using VMD instead to convert the mdcrd file into trr or xtc file. thanks

**Comment by msultan** [comment]
@Nidane, two possible things might be happening

1). you used natoms instead of n_atoms . Note the extra _ . 
2). you used extra quotations marks i.e "n_atoms=2667" instead of n_atoms=2667.



If you want to bypass this problem entirely, the following script will convert your mdcrd files into xtcs

``` python

import os, glob
import mdtraj as md 

file_list = glob.glob(*.mdcrd")
top_traj = md.load("./top.pdb")

for file in file_list:
   traj = md.load(file, top = top_traj, n_atoms = 2667)
   out_file_name = os.path.splitext(file)[0]
   assert not os.path.isfile(out_file_name)
   traj.save_xtc(out_file_name +".xtc")
   
```

Now, the folder with the mdcrd files should have the same files as xtc, and everything will hopefully be fine after this.

**Comment by msultan** [comment]
Also, the following link is useful for learning basics of python, https://www.learnpython.org/. All of us still look up python commands basically on a daily basis. Additionally jupyter notebooks are an amazing resource for playing around with python interactively (http://jupyter.org/)

**Comment by Nidane** [comment]
thank you very much for you help and I guess maybe I ran into the second problem you mentioned. As for your script, I ran it but it comes out as a TypeError as follows:
File ".....mdtraj/core/trajectory.py", line 430, in load
value = loader(filename, **kwargs)
TypeError: load_mdcrd() got an unexpected keyword argument 'n_atoms'

**Comment by msultan** [comment]
try it without n_atoms

```
   traj = md.load(file, top = top_traj)
```

**Comment by Nidane** [comment]
then it comes :
 File "/home/customer/anaconda2/lib/python2.7/site-packages/mdtraj/formats/mdcrd.py", line 337, in _read
    self._n_atoms, self._line_counter))
IOError: mdcrd parse error: specified n_atoms (1355) is likely incorrect. Incorrect buffer size encountered on line=408
and I guess it's  the problems with my trajectory or my PDB file ?

**Comment by Nidane** [comment]
File "/home/customer/anaconda2/lib/python2.7/site-packages/mdtraj/formats/mdcrd.py", line 337, in _read
    self._n_atoms, self._line_counter))
IOError: mdcrd parse error: specified n_atoms (1355) is likely incorrect. Incorrect buffer size encountered on line=408

**Comment by msultan** [comment]
Interesting, there is definitely something up with your mdcrd file. Can you load it in VMD and then save it to xtc? This might be an error with the mdtraj mdcrd reader in which case, we should raise an issue on mdtraj's github and get the devs involved there.

**Comment by Nidane** [comment]
yes, when I try it using VMD, it can be saved into trr and the convert into xtc using MDTraj. the only difference may be in VMD I used .prmtop file(topology file) and mdcrd file (trajectory). while here I load pdb file and mdcrd file instead.

**Comment by msultan** [comment]
hmm, i think there might be something with the pdb file then. A quick check for this could be to save a frame from the mdcrd using VMD to a PDB file, and then use the script with the new pdb file. If that works, then the original pdb file has something wrong.

**Comment by Nidane** [comment]
i will try with my pdb file. the pdb file that i used and get the error that I posted just now is exactly the one I use to generate my simulation trajectory but I will follow your advice and have a try to get a new pdb. as for the analysis related xtc trajectory, I have successfully run through the tutorial in which the trajectories are all in xtc format and I guess the whole workflow is OK as for my own trajectory, since I am still struggling to convert them from mdcrd file into trr or xtc file, so I have got any time to carry out MSM analysis, thanks .

**Comment by Nidane** [comment]
i try to generate a pdb file from the first frame of my trajectory and then use it into the script you posted previously and it still comes as an IOError:
 File "/home/customer/anaconda2/lib/python2.7/site-packages/mdtraj/formats/mdcrd.py", line 337, in _read
    self._n_atoms, self._line_counter))
IOError: mdcrd parse error: specified n_atoms (2676) is likely incorrect. Incorrect buffer size encountered on line=805

**Comment by msultan** [comment]
Can you raise this issue in mdtraj's [github](https://github.com/mdtraj/mdtraj), there is definitely some minor edge case issue going on with the mdcrd reader. They will likely ask you to upload a toplogy file and maybe a single frame of the mdcrd file as a test. hopefully thats okay.

**Comment by msultan** [comment]
If you can get the MSMBuilder pipeline to work, feel free to close this issue. And happy MSM constructing!

**Comment by Nidane** [comment]
of course I can carry out MSM analysis but in a much complex way, using VMD to first transform my mdcrd trajectory into xtc trajectory and that's why I try my best to figure out how to tackle this problem. if i can load mdcrd trajectories and carry MSM construction it will be much easier. 
I will try and follow your advice and raise an issue in mdtraj's github and hopefully it can come out smoothly. 
thank you very much!

**Comment by Nidane** [comment]
actually the most important issue that I am concerned is how to directly load mdcrd file and carry out MSM construction and I am not sure if there exists such case/problem, whether I can carry out my MSM analysis successfully. thank you !
