### ISSUE TITLE
cluster centers in the Kmeans

### ISSUE THREAD

**Issue by asgharrazavi** [msmbuilder/msmbuilder#1074]
I noticed that the cluster centers reported by the "cluster.cluster_centers_" don't exist in the input data. I created the cluster object using:

    from msmbuilder.cluster import KMeans, KCenters
    cluster = KMeans(n_clusters=100,n_jobs=-1,verbose=0)

I thought cluster centers are picked from the input data. Isn't this correct?

**Comment by juanmit** [comment]
Kmeans calculate the averages of your high-dimension coordinates.  For example, if your input has 8 tica-coordinates, the centers can not be viewed correctly on tICA1 and tICA2 coordinates.

**Comment by cxhernandez** [comment]
If you want cluster centers that are actual data points you can use the [_k_-mediods](https://en.wikipedia.org/wiki/K-medoids) algorithm (see [`KMediods`](http://msmbuilder.org/3.8.0/_cluster/msmbuilder.cluster.KMedoids.html#msmbuilder.cluster.KMedoids)).
