### ISSUE TITLE
Do I have enough samples?

### ISSUE THREAD

**Issue by AlirezaTafazzol** [msmbuilder/msmbuilder#1079]
I have a large system (~200k solvated atoms) which takes time for MD simulations. I am analyzing ligand-free (structure A) and ligand-bounded structures (structures B and C) and wish to find differences between the dynamics of these structures. All structures are retrieved from PDB website.  I have a total of 4.8 micro-second for each system (i.e., 4 trajectories of 1.2 ns). First of all, I remove the first 200 ns of each trajectory for equlibration and consider the rest 1000ns for each trajectory and then build my MSMs on the 4 micro-second;
1. Does this look logical?

I made a MSM (dihedral featurizer, msm lag_time = 1ns, # of clusters = 100, tICA lag_time = 2ns, tICA n_components = 6) for one of the chains of structure A to see how it looks like:
![image](https://user-images.githubusercontent.com/24233022/38753104-3439e774-3f12-11e8-8ead-7fa8ef270a45.png)

Comparing to other papers and examples on protein folding, I have a lot of empty spaces ==> 
2. Does it show that I need more samples? Or can it be just because of the nature of the protein that I am studying? (and basically it does not get all conformations in the space)

*The other question is about the "#how much of the data was retained during model creation?"(msm_mdl.percent.retained) as in example (https://github.com/msmbuilder/paper/blob/master/1-src/ipynbs/src_kinase_msmb_paper_mdl_creation.ipynb). In that example, that number is around 98% while for my case is around 26.51%.
3. Does this show that my MSM is not a good one? (because it seems that the model is just built based on some specific states and not all states) --> It is also obvious in the following MSM picture (the big white circle) 
4. Should this number be ideally 100% and with hyperparameter optimizations (like GMRQ scoring) we try to maximize it as much as possible?

![image](https://user-images.githubusercontent.com/24233022/38753739-311a9d66-3f14-11e8-8c92-7d69526716c8.png)

I tried to find out which MSM parameters have more impact on this number:

![image](https://user-images.githubusercontent.com/24233022/38757668-b1884710-3f22-11e8-9b0d-254f5d372db6.png)

It seems that 
•	tICA and MSM lag time do not have big effects!
•	Number of clusters and tICA components are important --> if these numbers are close together >> the % would be high.
(However, I know these kind of conclusions are not accurate and one should use GMRQ/Osprey to find the best model; but based on these preliminary results I am not sure even if I do a systematic scoring the results would be drastically different)
@jeiros @msultan @cxhernandez  @mpharrigan @brookehus

**Comment by jeiros** [comment]
May I suggest the 2d trace plots from msmexplorer: https://github.com/msmbuilder/msmexplorer/pull/108

I've found them particularly useful, you can tell how much each of your individual trajectories are exploring the tIC space. Also it can be useful to see what the ones "wandering off" are doing. I get this quite a lot myself too, my system is also really big and takes a long time to simulate. So I see many individual trajectories which just walk into unexplored regions of the tIC space and never come back, so they are disconnected from the rest, and that's why if you try to build an ergodic MSM so much of your dataset is thrown away. I've done a lot of reseeding with moderate sucess, I guess for complex and large proteins some motions are super hard to converge with a modest computational resource.

**Comment by AlirezaTafazzol** [comment]
> May I suggest the 2d trace plots from msmexplorer: msmbuilder/msmexplorer#108

Here are the results of the 2d trace plots for 4 trajectories (each 1 micro-s):

![image](https://user-images.githubusercontent.com/24233022/38829620-869a84b6-416e-11e8-9dea-5f660879891c.png)

There are no transitions between some  trajectories.  

If I don't want to run more simulations for now, do you think I would be able to get some interesting results/conclusions by clustering (MSMs) such data or not really?

**Comment by msultan** [comment]
I think you should first try and understand what the tICs are learning. I.e what separates the blue trajectory from the rest of them. One thing I would recommend is using the msmbuilder's featurizer objects feature_descriptor module. Its designed to show what each feature means at the atomic scale so you can back-calculate what the tIC represents (approximately)

Assuming that you using the dihedrals here is what the code would look like approximately:

```python
import pandas as pd 
import numpy as np
import mdtraj as md 
from msmbuilder.featurizer import DihedralFeaturizer


tica_model = #load FITTED tICA model

feat = DihedralFeaturizer()
traj = md.load("./blue_traj.pdb")

data_frame = pd.DataFrame(feat.describe_features(traj))

# argsort goes from smallest to biggest so we get the last 10 as being the 10 most important dihedrals needed to describe the tIC
important_inds = np.argsort(abs(tica_model.components_[0,:]))[-10:]

print(data_frame.iloc[important_inds])
```

**Comment by jeiros** [comment]
Adding to @msultan 's comment (and actually asking for myself as well):

Sparse tICA is useful as it gives more interpretable models, but of less quality (lower GMRQ scores). Do you know if the sparse tICs that are found correspond more or less to the procedure you've mentioned above? What I've usually done myself is run regular tICA to build MSMs on, as that is what gives higher quality models. But then on the side I run sparse tICA to visualize and interpret the non-zero tICs. I usually leave the regularization term of the sparse tICA class on its default value unless it gives many (>10) tICs back (which does not really happen that often)

Does that sound like a reasonable approach? Maybe @AlirezaTafazzol finds this approach useful too.

**Comment by AlirezaTafazzol** [comment]
BTW, what is the recommended value for ergodic_cutoff in the msmbuilder.msm.MarkovStateModel?
Should it be always integers?

If I put it 0, it will consider all available states and retains 100% data but if I change it to 0, it retains only around 22% of data (which is obvious based on the graphs already discussed). But if I change it to "1/400", it retains ~68% in some cases. What does it mean to have ergodic_cutoff as 1/400?

> ergodic_cutoff : float or {‘on’, ‘off’}, default=’on’

    Only the maximal strongly ergodic subgraph of the data is used to build an MSM. Ergodicity is determined by ensuring that each state is accessible from each other state via one or more paths involving edges with a number of observed directed counts greater than or equal to ergodic_cutoff. By setting ergodic_cutoff to 0 or ‘off’, this trimming is turned off. Setting it to ‘on’ sets the cutoff to the minimal possible count value.
http://msmbuilder.org/3.8.0/_msm/msmbuilder.msm.MarkovStateModel.html#msmbuilder.msm.MarkovStateModel

**Comment by AlirezaTafazzol** [comment]
@jeiros 
> I run sparse tICA to visualize and interpret the non-zero tICs.

Do you have a jupyter notebook or python example in case? 
I'm just curious what you calculate or what you plot to interpret/visualize those non-zero tICs.

**Comment by jeiros** [comment]
I actually have done something quite similar to what @msultan suggested. [Here](https://github.com/jeiros/msmbuilder/blob/my-template/msmbuilder/project_templates/tica/sparse-tica.py) is an example of how to do sparse tICA (I actually do over different values of the regularization parameter, starting from 0 which is regular tICA). Then [here](https://github.com/jeiros/msmbuilder/blob/my-template/msmbuilder/project_templates/tica/sparse-tica-plot.py) is an example of the visualization of those non-zero tICs.

To actually check which features are the non-zero ones, you can do something like this (I don't write the relevant imports):
```python
# Assume here traj is an mdtraj.Trajectory
# feat is an msmbuilder featurizer object
# sptica is your pre-fit sparse tica object
tic1_loads = list(np.nonzero(sptica.components_[0, :])[0])

# See what the loading values are
sptica.components_[0, tic1_loads]

# See what features are non-zero
print(pd.DataFrame(feat.describe_features(t)).iloc[tic1_loads])

```

**Comment by msultan** [comment]
Also, it might help to color the important residues in VMD to get an insight into what they might be doing.

**Comment by msultan** [comment]
Closing this now. Feel free to open another issue later on.
