### ISSUE TITLE
TPT on a set of macrostates

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/msmbuilder#1080]
I've been looking around in the documentation but haven't figured out a way of doing TPT analysis on the macrostates obtained from a lumping algorithm. My idea would be to get a simplified macrostate model of an MSM and then calculate quantities of interest like MFPTS, net fluxes, commitor probabilities etc. on the macrostates, for easier interpretability. I know these would be of lower quality than if I did them on the full MSM, but I'm having trouble interpreting my results on an MSM built with hundreds of microstates.

Something like figure 2a of [this paper](https://www.nature.com/articles/nchem.1821) is what I had in mind, just haven't found a straight forward way to do it.

Also, do you have any recommendations on how to proceed for selecting the number of macrostates if there is no clear gap in the timescales?

Thanks for any directions!

**Comment by msultan** [comment]
Hmm, I would try one of two things:
1). Try a different featurization, maybe that can separate out the timescales?
2). Pick a timescale cutoff and select states based on that. Its a bit hacky but most of the MSM lumping stuff is built on top of the idea of having some kind of separation.

@brookehus has some really nice work with MVCA based macro-state clustering that doesnt depend on timescales that might be very useful here too. Iirc, BACE (from Bowmen's lab) might also work though it has some issues. Alternatively, Xuhui Huang had some macrostating/clustering stuff in the pipeline though I am not sure if that ever got published.

**Comment by jeiros** [comment]
Thanks for the tips! Yeah, I've played around with MVCA directly from the master branch in github, as it is not yet released, right? I've also tried different featurizations for my system,  I think the reason why I don't get a clear separation of timescales is from not having sufficient sampling of the slow movements.

As far as doing TPT analysis on the set of macrostates, is that even feasible? One thing that I've noticed is that PCCA+ gives the macrostates different ids every time you run it, so it's kind of hard to automate the analysis.

Also, can I access the populations of the macrostates? Or the lumped transition matrix? Calling `pcca.transmat_` at the moment just gives back the full MSM transition matrix.

**Comment by brookehus** [comment]
MVCA is not in the current release but there's no reason we couldn't do a release any day (we probably should). All the lumping methods have a `microstate_mapping_` attribute and you can use the `partial_transform` method to transform your original data using this mapping (the mapping doesn't need to be input, just telling you it exists) and then you can make a macrostate MSM the same way you would make a regular MSM using the transformed trajectories. Then you could do TPT on your macrostate MSM the same way you do TPT on a regular MSM, and similarly grab your populations from your new MSM. Does that make sense?

i.e.

`macro_trajs = macro_mdl.partial_transform(trajs)`
`macro_msm = MarkovStateModel(macro_trajs)`

@kmckiern might also have some insight on doing this in practice.

**Comment by brookehus** [comment]
You probably need a longer lag time with a macrostate MSM and maybe also need to play with the ergodic cutoff but I don't have too much intuition on the latter.

**Comment by jeiros** [comment]
Ahh, it totally does. Had not thought of re-estimating an MSM out of the macrostate labelled trajectories. Thanks for the tips!
