### ISSUE TITLE
Generate pkl file of MD trajectories

### ISSUE THREAD

**Issue by daipayans** [msmbuilder/msmbuilder#1082]
Hi, Can someone help me with the procedure  on how to convert a set of dcd trajectories into a pkl format using the msmbuilder tool? At the moment, I do not want to perform any transformation on the trajectories as suggested in the example (DihedralFeaturizer). Thanks!

**Comment by msultan** [comment]
I would recommend just leaving the trajectories as dcd files. The pkl format was not really designed to save trajectories. You can simply re-run your script at a later date and MSMBuilder's featurizer object will work with the saved trajectories (in pretty much as format that mdtraj can understand).

**Comment by daipayans** [comment]
@msultan : Thanks for your help.
