### ISSUE TITLE
 transition probabilities (Rates per ns)

### ISSUE THREAD

**Issue by mkhoshle** [msmbuilder/msmbuilder#1085]
Hi all,
Does anyone know how can I create such a [(plot)](http://www.emma-project.org/latest/generated/pentapeptide_msm.html#coarse-grained-kinetic-model-using-a-hidden-markov-model) in MSMBuilder? I want to show the transition rate values between state. 
I have been able to plot free energy landscape [(here)](http://msmbuilder.org/msmexplorer/development/notebooks/Fs-Peptide.html#Construct-MSM) and transition path between states, but how can I understand which time scale corresponds to what transition path?

Thanks

**Comment by cxhernandez** [comment]
This might eventually be a good addition to MSMExplorer. One way to do it would be to use NetworkX's [`draw_networkx_edge_label`](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.drawing.nx_pylab.draw_networkx_edge_labels.html#draw-networkx-edge-labels)— similar to [what's being done here](https://github.com/msmbuilder/msmexplorer/blob/master/msmexplorer/plots/msm.py#L86-L105)— and set the `edge_labels` parameter to a list of the transition rates.

**Comment by mkhoshle** [comment]
Thanks, I will have a look at it. Also, how can I get plot the change in the probability of going from state i to state j vs lag time? How can one know the most probable transitions  between states?

**Comment by cxhernandez** [comment]
> Also, how can I plot the change in the probability of going from state i to state j vs lag time?

Maybe make MSMs at different lag-times, and plot certain probabilities in the transition matrix as a function of the lag-time used.

> How can one know the most probable transitions between states?

There's a whole field known as [transition path theory (TPT)](http://msmbuilder.org/3.8.0/tpt.html) for just this purpose.
