### ISSUE TITLE
conversion of the trajectory data to MSMBuilder format ？

### ISSUE THREAD

**Issue by caoyingtianjin** [msmbuilder/msmbuilder#1088]
I'm a beginner of  MSMBuilder,and I want to study how to convert the trajectory data to MSMBuilder format ? （I want to make a map of the conformational space according to dihedral and it is consist of a set of states and a matrix of transition probabilities,）

Thanks for any directions!

**Comment by cxhernandez** [comment]
Take a look at our [Examples section](http://msmbuilder.org/3.8.0/examples/Fs-Peptide-with-dataset.html#The-dataset-object) in our documentation. You can load trajectories in most formats using the `dataset` object.

**Comment by caoyingtianjin** [comment]
Thank you very much for your answer，I have just noticed that MSMBuilder has been upgraded to an upgraded version. I'm going to reinstall the new version. My English level is not very good. Thank you for your guidance.

**Comment by caoyingtianjin** [comment]
I have installed a new version of MSMBuilder and are learning to use it. Now, I am learning the Tutorial.pdf file, and are practicing "Move to tutorial directory, prepare trajectories" and "Create an MSMBuilder Project".
I type in my terminal: "ConvertDataToHDF.py -s native.pdb -i XTC".

caoying@caoying:~/msmbuilder/Tutorial$ ConvertDataToHDF.py -s native.pdb -i XTC
/home/caoying/anaconda2/lib/python2.7/site-packages/scipy/spatial/__init__.py:94: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/home/caoying/anaconda2/lib/python2.7/site-packages/scipy/spatial/__init__.py:95: ImportWarning: Not importing directory '/home/caoying/anaconda2/lib/python2.7/site-packages/scipy/spatial/qhull': missing __init__.py
  from .qhull import *
/home/caoying/anaconda2/lib/python2.7/site-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/home/caoying/anaconda2/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/home/caoying/anaconda2/lib/python2.7/site-packages/scipy/spatial/distance.py:121: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
--------------------------------------------------------------------------------

MSMBuilder version 2.7.dev.dev-Unknown

See file AUTHORS for a list of MSMBuilder contributors.

--------------------------------------------------------------------------------

Copyright 2011 Stanford University.

MSMBuilder comes with ABSOLUTELY NO WARRANTY.

MSMBuilder is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

--------------------------------------------------------------------------------

Please cite the following references:

GR Bowman, X Huang, and VS Pande. Methods 2009. Using generalized ensemble 
simulations and Markov state models to identify conformational states.

KA Beauchamp, GR Bowman, TJ Lane, L Maibaum, IS Haque, VS Pande.  JCTC 2011.
MSMBuilder2: Modeling Conformational Dynamics
at the Picosecond to Millisecond Timescale

IS Haque, KA Beauchamp, VS Pande.  In preparation.
A Fast 3 x N Matrix Multiply Routine for Calculation of Protein RMSD.

--------------------------------------------------------------------------------
{'input_dir': 'XTC',
 'min_length': 0,
 'pdb': 'native.pdb',
 'project': 'ProjectInfo.yaml',
 'quiet': False,
 'rmsd_cutoff': -1,
 'source': 'file',
 'stride': 1}
Traceback (most recent call last):
  File "/home/caoying/anaconda2/bin/ConvertDataToHDF.py", line 4, in <module>
    __import__('pkg_resources').run_script('msmbuilder==2.7.dev0', 'ConvertDataToHDF.py')
  File "/home/caoying/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/caoying/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/home/caoying/anaconda2/lib/python2.7/site-packages/msmbuilder-2.7.dev0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/ConvertDataToHDF.py", line 150, in <module>
    args.min_length, args.stride, rmsd_cutoff)
  File "/home/caoying/anaconda2/lib/python2.7/site-packages/msmbuilder-2.7.dev0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/ConvertDataToHDF.py", line 57, in run
    stride=stride, project=project)
  File "/home/caoying/anaconda2/lib/python2.7/site-packages/msmbuilder-2.7.dev0-py2.7-linux-x86_64.egg/msmbuilder/project/builder.py", line 97, in __init__
    self._check_out_dir()
  File "/home/caoying/anaconda2/lib/python2.7/site-packages/msmbuilder-2.7.dev0-py2.7-linux-x86_64.egg/msmbuilder/project/builder.py", line 175, in _check_out_dir
    raise IOError('%s already exists' % self.output_traj_dir)
IOError: Trajectories already exists

What should I do now?

Or, as you suggested yesterday, I should first learn Examples section in your documentation?
Thank you very much for your guidance！
