### ISSUE TITLE
Dumping representative snapshots from microstate, macrostate

### ISSUE THREAD

**Issue by sbhakat** [msmbuilder/msmbuilder#1089]
Hi,

I still didn't find out how to dump snapshots of microstates after Kmenas clustering which corresponds to each basin. In the attached picture I want to have clusters corresponding to each micro states so that I can see the conformations in VMD. Is there a script to do it. Maybe it is repeatation question. The same also apply for macrostates.
![screenshot-2018-6-1 bpti_msm_gly56](https://user-images.githubusercontent.com/33577253/40852686-802bd78e-65cb-11e8-89af-0670ecc31e24.png)

I guess transition pathway images and how to do it is missing from MSM Builder tutorial. Is there any way to generate plots like the following

![msm_bpti_122_1](https://user-images.githubusercontent.com/33577253/40852843-3aaa05e0-65cc-11e8-8393-04f2bfcb2611.png)

**Comment by cxhernandez** [comment]
> I still didn't find out how to dump snapshots of microstates after Kmenas clustering which corresponds to each basin. In the attached picture I want to have clusters corresponding to each micro states so that I can see the conformations in VMD. Is there a script to do it. Maybe it is repeatation question. The same also apply for macrostates.


You can use `msmbuilder.utils.KDTree` as in this example: https://github.com/msmbuilder/paper/blob/master/1-src/ipynbs/src_kinase_msmb_paper_mdl_analysis.ipynb

> I guess transition pathway images and how to do it is missing from MSM Builder tutorial. Is there any way to generate plots like the following

We have a separate project, [MSMExplorer](https://github.com/msmbuilder/msmexplorer), which can handle plotting. One of the examples shows how to make this sort of plot: http://msmbuilder.org/msmexplorer/development/notebooks/Fs-Peptide.html#Free-Energy-Landscape

**Comment by sbhakat** [comment]
@cxhernandez Hi, Carlos I managed to do the transition path thing. However in one case I got an error like following

ValueError: 'vertices' must be a 2D list or array with shape Nx2

A version of my notebook is with the following link (**See page no 42 for the error**)

. I am not sure what makes this value error. Any input will be highly appreciated. Thanks a lot again.

[bpti_msm_leu6n.pdf](https://github.com/msmbuilder/msmbuilder/files/2067678/bpti_msm_leu6n.pdf)

**Comment by msultan** [comment]
From your code on page 42

```
pos = dict(zip(range(clusterer.n_clusters), clusterer.cluster_centers_))
```
this is wrong, please change it to :

```
pos = clusterer.cluster_centers_[:,:2]

```

So now the positions for each state are the positions of the cluster centers as inferred by the clustering model.

**Comment by msultan** [comment]
closing this now.
