### ISSUE TITLE
center conformations of the macrostates

### ISSUE THREAD

**Issue by musaoz** [msmbuilder/msmbuilder#1090]
Dear all,

What is the best way to obtain a representative conformation of each of the macrostates extracted from the microstates? Perhaps like a center obtained when structures are clustered to obtain microstates. I have read a few publications mentioning about the representative conformations obtained using MSMbuilder with no clear explanation to how they were obtained and I have read some of the issues previously raised, but couldn't find a satisfactory answer so far. Any help would be appreciated!

Thanks in advance!

**Comment by cxhernandez** [comment]
You can use a `KDTree` as mentioned here: https://github.com/msmbuilder/msmbuilder/issues/1089#issuecomment-393961824

**Comment by musaoz** [comment]
The macrostate representatives chosen in that example is arbitrary, isn't it?
From the two lines below, I see that the two centers are chosen as the first in the list of cluster_centers_ with an x value larger than 1.0 and, for some reason, the second in the same list with an x value smaller than -0.75. Does pcca computes a center with a certain criteria? or is it completely up to the user to define a center such as one based on geometric centers of the microstates that make a macrostate?
Thanks!

```
ind1 = np.where(kmeans_mdl.cluster_centers_[:,0]>1)[0][0]
ind2 = np.where(kmeans_mdl.cluster_centers_[:,0]<-0.75)[0][1]
```

**Comment by cxhernandez** [comment]
PCCA is completely independent of the geometry of the original feature-space. What I would suggest is that you take all the microstate cluster centers within each macrostate and take a population-weighted average of the coordinates of this to be the macrostate center. Maybe something like this:

```python
macro_centers = []
for microstate_indices in macrostate:
    center = np.average(kmeans_mdl.cluster_centers_[microstate_indices], axis=0,
                        weights=microstate_msm_mdl.populations_[microstate_indices])
    macro_centers.append(center)
```

Then you can proceed with using the `KDTree`.
