### ISSUE TITLE
Checking states are at minimums in the Free Energy landscape and wrt to which tICA axes

### ISSUE THREAD

**Issue by orthonalmatrix** [msmbuilder/msmbuilder#1092]
Is there an easy way to get the 1st and second derivatives of the free energy surface wrt different tICA axis?
I'd like to know if the MSM states are in Free energy minimums. I get MSM states that are at the edge of a tICA 1 and tICA2 axis potential well and may be a transition state or may be stable (just not evidently wrt tICA1 & 2). Are there any built in functions?

**Comment by cxhernandez** [comment]
Not yet.

The way we usually compute free energy landscapes is using a KDE estimator. So if you can take the derivative of that sum of Gaussians wrt to the tICs, then you've got your answer.
