### ISSUE TITLE
msm.transmat to MSMExplorer

### ISSUE THREAD

**Issue by girodat** [msmbuilder/msmbuilder#1095]
I have been trying to generate a transition probability matrix to upload into msmexplorer. However, the output that I am getting from msmbuilder consists of:

%%MatrixMarket matrix array real general
%
500 500
1.4552236774619964e-01
0.0000000000000000e+00
0.0000000000000000e+00
0.0000000000000000e+00
0.0000000000000000e+00
0.0000000000000000e+00
....

where there is only a single column. I have noticed in the tutorial for MSMExplorer that the matrix requires 3 columns of data; I'm assuming the source and target node followed by the weight of the edge. Here is the script I have been using to generate the transition matrix. 

"""Make a microstate MSM

msmbuilder autogenerated template version 2
created 2018-06-25T11:45:07.398981
please cite msmbuilder in any publications
"""

from msmbuilder.io import load_trajs, save_trajs, save_generic
from msmbuilder.msm import MarkovStateModel
from scipy import io as sio
import msmexplorer as msme

## Load
meta, ktrajs = load_trajs('ktrajs')

## Fit
msm = MarkovStateModel(lag_time=1, n_timescales=5, verbose=False)
msm.fit(list(ktrajs.values()))

## Transform
microktrajs = {}
for k, v in ktrajs.items():
    microktrajs[k] = msm.partial_transform(v)
#Transition Matrix 
sio.mmwrite('wt-trasmat.mtx', msm.transmat_)

## Save
print(msm.summarize())
save_generic(msm, 'msm.pickl')
save_trajs(microktrajs, 'microktrajs', meta)

Any help would be much appreciated

**Comment by msultan** [comment]
tagging @cxhernandez since he might know exactly what format the online MSMExplorer takes.

**Comment by cxhernandez** [comment]
Matrix market format is the correct format for msmexplorer-d3; and your code looks fine to me. Did you try uploading the file? Did it not work?

My only suggestion would be to try explicitly converting `msm.transmat_` into a [sparse matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html#scipy.sparse.coo_matrix).
