### ISSUE TITLE
Information on kerneltICA

### ISSUE THREAD

**Issue by orthonalmatrix** [msmbuilder/msmbuilder#1099]
Hi,
I can find the publication on kerneltICA, but I can't find much on the msmbuilder website about the class. What is the calling sequence and how can I use it instead of the usual tICA?
Thanks!

**Comment by cxhernandez** [comment]
Here's the original publication by Schwantes and Pande: https://pubs.acs.org/doi/abs/10.1021/ct5007357

Here's a preprint about the version currently implemented in MSMBuilder: https://www.biorxiv.org/content/early/2017/04/04/123752

**Comment by cxhernandez** [comment]
> What is the calling sequence and how can I use it instead of the usual tICA?

It's the same workflow as the `tICA`, except for an optional `landmarks` parameter, which is typically the output of some clustering method. If you don't provide landmarks, the module will subsample frames from your trajectories to use as landmarks.
