### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by ahy3nz** [msmbuilder/msmbuilder#1139]
Is the [website](http://msmbuilder.org/) down? Is this also related to https://github.com/openmm/openmm/issues/2908 and https://github.com/mdtraj/mdtraj/issues/1593? This package doesn't look like it's being actively maintained, but I noticed a message on the mailing list from someone who's interested

**Comment by jchodera** [comment]
We've just resolved the AWS issues, and the website is back up! Thanks for your patience.
