### ISSUE TITLE
Featurizer base class should have `n_features` attribute

### ISSUE THREAD

**Issue by kyleabeauchamp** [msmbuilder/msmbuilder#116]
The idea being that _all_ featurizers should have some information about the shape its output will be.

**Comment by kyleabeauchamp** [comment]
Can someone remind me about the outcome / discussion of this issue?  Is `n_features` a required member of featurizer subclasses?  If so, should we formalize it in some way?  If not, do we have a workaround / better idea?

I guess my confusion was that *most* of the featurizer subclasses have this object stored, but it's not mentioned in the base class.

**Comment by rmcgibbo** [comment]
I can't remember. Is there some reason it's really needed? Seems superfluous to me.

**Comment by kyleabeauchamp** [comment]
Jan-Hendrik wanted it to help keep track of data shape metadata in opentis when he generates various reaction coordaintes

**Comment by rmcgibbo** [comment]
It's not clear to me that it can alway be precomputed. eg with dihedrals, you ask for phi/psi, and the transformed shape is going to depend on the number of residues in the input.
