### ISSUE TITLE
Strided clustering in pipelines

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#192]
Currently, I'm writing a lot of code like

```
pipeline = Pipeline([
    ('tica', tICA(n_components=1, gamma=0.001, lag_time=lag_time)),
    ('cluster', KMeans(n_init=1, n_clusters=20)),
    ('msm', MarkovStateModel(n_timescales=3, n_states=20, lag_time=lag_time))
])
```

When `lag_time` is relatively large and the time step in the actual data set is short, most of the time is spent in KMeans, and doing a stride (i.e. cluster with only every N-th frame, but assign every frame) is a pretty good idea. I'm not totally sure what the best way to do it is though. One option is to add a `stride` argument to all of the clustering classes, but that doesn't seem great. Another might be -- i'm not sure if this is possible? -- to add some kind of extra step into the pipeline that goes before the clustering (`subsampler`) that looks like

```
class Subsampler
    def __init__(self, fit_stride=1, transform_stride=1):
        self.fit_stride = fit_stride
        self.transform_stride = transform_stride
    def fit(self, sequences):
        return [s[::self.fit_stride] for s in sequences]
    def transform(self, sequences):
        return [s[::self.transform_stride] for s in sequences]
```

And then adding a `Subsampler` into the pipeline with a positive `fit_stride` and transform_stride=1` right before the clustering. I'm not 100% sure that this would actually work (I haven't tried it yet), because I don't really know how pipeline is implemented.

**Comment by mpharrigan** [comment]
MiniBatchKMeans is probably sufficient here
