### ISSUE TITLE
Dataset loader for siegetank datasets

### ISSUE THREAD

**Issue by jchodera** [msmbuilder/msmbuilder#256]
I really liked the idea of the [`alanine_dipeptide.py`](https://github.com/rmcgibbo/mixtape/blob/master/Mixtape/datasets/alanine_dipeptide.py) loader when @kyleabeauchamp covered it in his talk today.

I think this kind of idiom could work really well for creating and updating a local cache of siegetank datasets for rapid experimentation (though @kyleabeauchamp thinks the performance may be awful for this, especially if water needs to be stripped).  I've started a little attempt to try to get this to work.

Will file a WIP PR when I have something close to working.

**Comment by mpharrigan** [comment]
This is outside the scope of the project
