### ISSUE TITLE
example_datasets should be `dataset` objects

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#348]
The return value from `mixtape.example_datasets.fetch_alanine_dipeptide` should be a dataset object, not a dict.

**Comment by kyleabeauchamp** [comment]
Any thoughts on how this should work for the in-memory datasets like Brownian1D?  From my understanding, the new BaseDataset class seems to have a constructor that is hard-coded for data on disk:

```
def __init__(self, path, mode='r', verbose=False):
```

**Comment by kyleabeauchamp** [comment]
OK I think I have a better idea now, still reading through the classes

**Comment by kyleabeauchamp** [comment]
So given that this might involve slightly more refactoring than I had imagined, I'm also fine if we want to punt this to 3.3.  I suppose it makes sense to do this right the first time, rather than rush a refactor out the door in 3.2

**Comment by mpharrigan** [comment]
I'd vote to not rush and do later properly

**Comment by cxhernandez** [comment]
@mpharrigan: what's the status of this?
