### ISSUE TITLE
Implement kernel tICA

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#389]

**Comment by evanfeinberg** [comment]
I'm writing my own functions to do the Nystorem approximation with tICA. I'll post it when it's done so others can use it pretty easily. Unless this has been done already and I'll just use that?

**Comment by rmcgibbo** [comment]
see http://scikit-learn.org/stable/modules/kernel_approximation.html

**Comment by cxhernandez** [comment]
for the landmark kernel stuff this may or may not be helpful: https://www.aaai.org/ocs/index.php/AAAI/AAAI11/paper/viewFile/3484/3883

**Comment by mpharrigan** [comment]
For fun, I re-did the 1d potential figures from christian's paper with nystorem using sklearn+linear tica and it worked and was easy. I don't know if we actually need any new code in msmbuilder, unless we want a convenience class

**Comment by msultan** [comment]
Maybe put in the code here so that there is a reference for the future ?
Muneeb

**Comment by rmcgibbo** [comment]
i think we should just add a wrapper class for nystroem that converts the sklearn class to msmb api, like the PCA class

**Comment by mpharrigan** [comment]
Oh yeah that makes sense

**Comment by evanfeinberg** [comment]
Thanks everyone. That link was very relevant @cxhernandez . 

@mpharrigan would you be so kind as to share your code for the 1d potential so as to minimize wheel reinvention?

**Comment by evanfeinberg** [comment]
I'm sure there's a trivial answer to this that I'm not just seeing, but how does one specify landmark points or some non-random-subsampling of the trajectory? In the link @rmcgibbo shared http://scikit-learn.org/stable/modules/generated/sklearn.kernel_approximation.Nystroem.html#sklearn.kernel_approximation.Nystroem there is a parameter "n_components", and then once one runs fit_transform, the Nystroem object has a "component_indices_" attribute, but I don't see a way to choose those component_indices_ up front.

**Comment by evanfeinberg** [comment]
OK thanks for your help everyone! I created a custom version of class Nystroem, listed in module LandmarkNystroem.py, that allows the user to specify their own basis set instead of generating one to define the landmark points. When one initializes an instance of class Nystroem, simply pass "basis = L" where L is your array of vectors representing the landmark points. Here is the code:

https://gist.github.com/evanfeinberg/43e2b7e7d358565d6364

Here is example of a code that uses that class: 

```
from LandmarkNystroem import Nystroem as LandmarkNystroem
from msmbuilder.decomposition.base import MultiSequenceDecompositionMixin
from msmbuilder.utils import verbosedump, verboseload
import numpy as np

class Nystroem(MultiSequenceDecompositionMixin, LandmarkNystroem):
	pass

features = verboseload(combined_features_dir)
landmarks = verboseload(landmarks_dir)
nys = Nystroem(n_components = np.shape(landmarks)[0], basis = landmarks)
nyx = nys.fit_transform(features)
verbosedump(nyx, nystroem_data_filename)

tica_model = tICA(n_components = tica_components, lag_time = lag_time)
fit_model = tica_model.fit(nyx)
verbosedump(fit_model, fit_model_filename)
transformed_data = fit_model.transform(nyx)
verbosedump(transformed_data, projected_data_filename)
```

Thanks again! Hope this is useful to someone.
Evan

**Comment by mpharrigan** [comment]
cc #390

**Comment by mpharrigan** [comment]
@evanfeinberg , do you want to create a PR for your code into msmbuilder?

**Comment by evanfeinberg** [comment]
yep yep, will do right after yom kippur ends

**Comment by cxhernandez** [comment]
done in https://github.com/msmbuilder/msmbuilder/pull/807
