### ISSUE TITLE
Unify GaussianHMM and VonMisesHMM.

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#402]
Another place where we could potentially get some help from @peastman is in rearchitecting the HMM code. Currently, we have two HMM classes that differer mathematically in a relatively small way -- they use a different emission distribution (Gaussian vs. Von Mises). But the code is 100% different. The Von mises model also uses a base class from `sklearn` which has been deprecated -- so that's not good.

The Gaussian model is able to use multiple threads in parallel, which is very nice, but it's not very extensible. The Von mises code uses a nicer subclassing design to avoid having the "von mises" part of the code reimplement functionality which is shared with other models. But that is all in python, and with the way the GIL works, it prevents the code from working on each of the sequence in parallel, which is the natural point of parallelism to decompose of the problem for multiple threads.

The most rational solution is to port everything into C++, because then you can do both parallelism and subclassing correctly. I tried this at one point, but I basically got stuck, because I don't understand C++ OO very well. https://github.com/msmbuilder/msmbuilder/pull/98/files

**Comment by mpharrigan** [comment]
This has been done
