### ISSUE TITLE
Implement APM clustering

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#433]
- New [paper](http://pubs.acs.org/doi/pdf/10.1021/ct5007168) on ASAP from the Huang group at HKUST.
- Looks fairly computationally cheap.
- Potentially nice for situations where the diffusion constant is highly position dependent (e.g. multi-body systems with an bound vs. unbound state)
- Their code is GPL, which isn't compatible w/ our LGPL. I sent an email to Xuhui asking if they would consider (dual/re)-licensing under a compatible license.

**Comment by mpharrigan** [comment]
closed by #748
