### ISSUE TITLE
[FR] Map features back to atom indices

### ISSUE THREAD

**Issue by msultan** [msmbuilder/msmbuilder#448]
I think that the DihedralFeaturizer class should include a method that maps each of the calculated feature to the residue index(using maybe the CA or something). I was thinking something like the following 
```
dihedral_feat = DihedralFeaturizer(["phi","psi","chi1"])
d_features = dihedral_feat.partial_transform(trj)

dihedral_feat.mapping(40)
=23
```

I think it would make the analysis a lot easier. Probably a lot of the other featurizers could benefit as well.

**Comment by msultan** [comment]
I can work on this if people are busy but I would like some input on how to best implement it.

**Comment by kyleabeauchamp** [comment]
I think having a more full-featured feature exploration API is a good idea, let's discuss.

**Comment by msultan** [comment]
Ideally, it should be able to take in a featurizer or a list of featurizer and fit/transform using all/subset of them and be aware of what features went it and their atomic mapping. 

Personally, I would prefer each featurizer have a mapping method from the column index to atom indices/residue indices used. For RMSD and contacts, this could be a list. 

Also, scikit learn has the feature_extraction but its very awkward imho. 
http://scikit-learn.org/stable/modules/feature_extraction.html

**Comment by msultan** [comment]
It would be nice/though not necessary, if the feature explorer perhaps took in any of the decomposition method like pca/tica/s-tica and returned the top m features in the top n components.

**Comment by kyleabeauchamp** [comment]
So I also have some incomplete code for selecting subsets of features: https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/featurizer/subset_featurizer.py

I'd love to figure out what to do with that incomplete piece of code.  

I also had some code that used monte carlo to attempt to find the "best" subset of an existing group of featurizers.  I never had time to finish it though, and now you and Robert both have competing approaches as well.  

IMHO, the most pressing questions are:

1.  What do we need in terms of feature extraction / choosing subsets of features
2.  How do we best keep track of feature metadata
3.  How do we build a nice way to get human-readable visualizations / representations of geometric features-e.g. for writing papers on what the features *mean*

**Comment by msultan** [comment]
1). Imo, i think its still an open question which feature selection method is "best" within a biological context. There are some problems with each(including mine). Which is why, I think we should support a few of them. 
2). Not so sure. 
3). I think a lot of the visualization mostly comes down to histograms of the covariates against the target. An intelligent labeling scheme that figures out that the xlabel is "chi_32" or "distance 34-23" should be enough for at least a simple release.

**Comment by kyleabeauchamp** [comment]
Sounds good.  I think we can build up some shared functionality here even as we support multiple feature selection methods--we're mostly in agreement.

**Comment by rmcgibbo** [comment]
It seems to me that the initial feature request here, the `mapping` to go from c-alpha to feature index (or maybe from feature index to c-alpha, I'm not sure which is the desired direction), is a pretty good idea that is totally independent from these more general questions about feature selection or subset featurizers. Easy enough to do these things one at a time.

**Comment by msultan** [comment]
Here is what I propose based on what Kyle already had. 

```
    def describe_features(self, traj):
        """Return a Pandas Dataframe describing the features."""
        x = []
        for a in self.types:
            func = getattr(md, 'compute_%s' % a)
            aind, y = func(traj)
            n = len(aind)

            resSeq = [(np.unique([traj.top.atom(j).residue.resSeq for j in i])) for i in aind]
            resid = [(np.unique([traj.top.atom(j).residue.index for j in i])) for i in aind]
            resnames = [[traj.topology.residue(j).name for j in i ] for i in resid]


            bigclass = ["dihedral"] * n
            smallclass = [a] * n

            if self.sincos:
                #x.extend([np.sin(y), np.cos(y)])
                aind = aind * 2
                resnames = resnames * 2
                resSeq = resSeq * 2
                resid = resid * 2
                trig = (["sin"] * n) + (["cos"] * n)
                bigclass = bigclass * 2
                smallclass = smallclass * 2
            else:
                trig = ["nosincos"] * n

            for i in range(len(resnames)):
                d_i = dict(resname=resnames[i], atomind=aind[i], resSeq=resSeq[i], resid=resid[i], \
                           trig=trig[i], bigclass=bigclass[i], smallclass=smallclass[i])
                x.append(d_i)

        return x
```

The output is something like this. 
```
In [47]: df[:2]
Out[47]: 
            atomind  bigclass  resSeq   resid     resname smallclass      trig
0  [22, 24, 26, 34]  dihedral  [1, 2]  [0, 1]  [LYS, ASP]        phi  nosincos
1  [34, 36, 38, 50]  dihedral  [2, 3]  [1, 2]  [ASP, VAL]        phi  nosincos


```

And we can concatenate the data frames to mix multiple featurizers probably without issues.

**Comment by mpharrigan** [comment]
Is this done with the "describe features" function?

**Comment by mpharrigan** [comment]
@msultan says this is done with "describe features"
