### ISSUE TITLE
msmb MarkovStateModel doesn't tell you how much of your data gets trimmed

### ISSUE THREAD

**Issue by sryckbos** [msmbuilder/msmbuilder#457]
when I do the following:

$ msmb MarkovStateModel -i superpose-and-solvent-200states.h5 -o superpose-and-solvent-200states-msm --lag_time 15

The output I get is described below.  The info seems correct, but it doesn't look like ergodic trimming is described like in the old BuildMSM.py.

MarkovStateModel(ergodic_cutoff=1, lag_time=15, n_timescales=10,
         prior_counts=0, reversible_type='mle', sliding_window=True,
         verbose=True)
MSM contains 1 strongly connected component above weight=1.00. Component 0 selected, with population 100.000000%
*********
*RESULTS*
*********
Markov state model
------------------
Lag time         : 15
Reversible type  : mle
Ergodic cutoff   : 1
Prior counts     : 0

Number of states : 200
Number of nonzero entries in counts matrix : 9773 (24.4325%)
Nonzero counts matrix entries:
    Min.   : 1.0
    1st Qu.: 2.0
    Median : 7.0
    Mean   : 37.8
    3rd Qu.: 26.0
    Max.   : 1546.0

Total transition counts :
    369010.0 counts
Total transition counts / lag_time:
    24600.6666667 units
Timescales:
    [531.94, 285.40, 170.10, 99.98, 97.67, 78.00, 73.68, 71.83, 71.67, 64.50]  units

--------------------------------------------------------------------------------
Saving "superpose-and-solvent-200states-msm.pkl"... (<class 'msmbuilder.msm.msm.MarkovStateModel'>)
To load this MarkovStateModel object interactively inside an IPython
shell or notebook, run:

  $ ipython
  >>> from msmbuilder.utils import load
  >>> model = load('superpose-and-solvent-200states-msm.pkl')

**Comment by schwancr** [comment]
Stephen and I talked about this offline

**Comment by mpharrigan** [comment]
For anyone stumbling on this question in the future, the trimming is given near the top:
```
Component 0 selected, with population 100.000000%
```

**Comment by sryckbos** [comment]
Just to clarify my question, I didn't realize this was related to trimming
and that this meant 0% of the data was trimmed (which is how it was phrased
in BuildMSM.py previously).

**Comment by rmcgibbo** [comment]
Perhaps we could clarify this by moving the trimming info from the separate
print to the summary with the rest of the info.
