### ISSUE TITLE
The dataset object does not implement ```keys``` correctly

### ISSUE THREAD

**Issue by schwancr** [msmbuilder/msmbuilder#458]
When doing ```dataset.__get__(i)```, i corresponds to the i'th item **after** sorting.

But when iterating through the dataset the keys are never sorted, which means anything that does: ```for item in dataset``` (unless the keys come out sorted {certainly not the case for HDF5 datasets}) the trajectories get scrambled. 

https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/dataset.py#L308-L312

**Comment by schwancr** [comment]
Thanks to @sryckbos for finding this problem.

**Comment by schwancr** [comment]
@rmcgibbo @mpharrigan maybe an arduino can fix this issue?

**Comment by rmcgibbo** [comment]
Fixed by #460.
