### ISSUE TITLE
msmb ConvertChunkedProject makes bad trajectories from fah datasets

### ISSUE THREAD

**Issue by sryckbos** [msmbuilder/msmbuilder#464]
In my fah datasets, when something goes wrong for one reason or another, the assignment server creates a directory inside the given CLONE where it went wrong named something like 0x0#########.  Inside this folder is one or two .xtc files from when things went badly.  As far as I remember, ConvertDataToHDF had a fah option for specifying datasets, and it did not convert the data in the 0x0######## directory to their own trajectories.  msmb ConvertChunkedProject, however, does go into these folders and makes these things into their own trajectories, and I don't think it should.  

Right now I'm going through and deleting the 0x0######## directories before conversion to avoid this, but is there a way to recover the fah functionality of ConvertDataToHDF?  Or am I remembering incorrectly such that ConvertDataToHDF also had this problem?

**Comment by rmcgibbo** [comment]
I'm not sure if I understand. Is it correct to say that you have a `CLONE` directory which contains a set of xtc files that you _want_ to convert, but also contains another directory containing xtc files you don't want to convert?

Like
```
CLONE10/
   frame0.xtc
   frame1.xtc
   ...
   frameN.xtc
   0x0########/
      bad-thing-0.xtc
      bad-thing-1.xtc
```

**Comment by kyleabeauchamp** [comment]
Correct.  The 0x0 directory is garbage output.

FWIW, I've got some intermediate scripts for Core17/18 here (https://github.com/FoldingAtHome/FAHMunge) that convert, merge, and strip trajectories in stages and runs continuously in the background.

**Comment by rmcgibbo** [comment]
Is it always named exactly `0x0########/`, or is that a placeholder?

**Comment by mpharrigan** [comment]
placeholder

**Comment by sryckbos** [comment]
That's a placeholder.  It's 0x0 followed by a lot of alphanumeric
characters and some dashes (see PROJ9007/RUN1002/CLONE0 on vspg14e for an
example).

And thanks Kyle, I'll check it out.

On Thu, Feb 5, 2015 at 2:21 PM, Robert T. McGibbon <notifications@github.com

**Comment by mpharrigan** [comment]
I think this is out of the scope of msmbuilder
