### ISSUE TITLE
Should HMM example use example dataset loader?

### ISSUE THREAD

**Issue by kyleabeauchamp** [msmbuilder/msmbuilder#471]
Right now it looks like the HMM example is not something that runs out of the box (e.g. `xtal = md.load('crystal-structure.pdb')`).

**Comment by kyleabeauchamp** [comment]
Another way to do this is to have a folder that contains all the necessary files.  There's also value in people learning how to use `md.load` and munge their data (e.g. without the example loader).  I just think we want most of the example code to be "batteries included".

**Comment by rmcgibbo** [comment]
+1 for just changing it to use the example dataset.

**Comment by cxhernandez** [comment]
@mpharrigan: what's the status of this?
