### ISSUE TITLE
Docs: Use latest release by default?

### ISSUE THREAD

**Issue by kyleabeauchamp** [msmbuilder/msmbuilder#473]
It might be useful to have the docs default to the latest *released* version, rather than `latest`.  Same for MDTraj

**Comment by rmcgibbo** [comment]
I don't have a strong feeling about this. As long as we're releasing often, it doesn't make much difference.

**Comment by kyleabeauchamp** [comment]
Looks like we don't have any docs for 3.1

**Comment by rmcgibbo** [comment]
I'll build them and push manually.

**Comment by rmcgibbo** [comment]
docs up.

**Comment by kyleabeauchamp** [comment]
cool, I'm happy closing this issue too
