### ISSUE TITLE
Docs and README.md: Use conda installer?

### ISSUE THREAD

**Issue by kyleabeauchamp** [msmbuilder/msmbuilder#476]
Right now, the main installation instructions are manual.  Two options:

1.  Include conda instructions?
2.  Include conda instructures as the *preferred* installation mechanism?

**Comment by mpharrigan** [comment]
+1

**Comment by kyleabeauchamp** [comment]
I'm going to vote for option (2), where we direct all non-expert users to the conda packages.  Maybe we can have a separate section for compiling from source "installation from source: expert users"

**Comment by rmcgibbo** [comment]
Agree with (2). Whoever writes this can crib a lot of material from the
mdtraj docs.
