### ISSUE TITLE
msmbuilder v3.1 release timeline

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#484]
Lots of bugfixes have happened. We should make a release

**Comment by kyleabeauchamp** [comment]
1.  We should make a pass through the tracker
2.  Make sure we don't need any features from MDTraj 1.3, which hasn't been released

**Comment by rmcgibbo** [comment]
All the tests were running with mdtraj 1.2, so that's not problem.

**Comment by rmcgibbo** [comment]
Nothing else in the tracker is really low-hanging. I'm going to do this now.

**Comment by kyleabeauchamp** [comment]
OK, looks like all the conda packages built themselves overnight, as well.

**Comment by rmcgibbo** [comment]
I built the win-32 ones too.
