### ISSUE TITLE
MSMBUILDER 3.0 tutorial

### ISSUE THREAD

**Issue by akiikius** [msmbuilder/msmbuilder#485]
Is there any way to get a quick run through of msmbuilder 3.0 that is similar to the msmbuilder 2.8 tutorial. Am new to using msmbuilder and am having a hard time figuring out the processes on the website. A quick 1,2,3 list would help. Thanks!

**Comment by mpharrigan** [comment]
There's this:
http://msmbuilder.org/latest/commandline.html

It looks slightly out of date. I'll run through it to check
