### ISSUE TITLE
Sparsity and lag time

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#493]
Looking at the fit models as a function of lag time, one interesting behavior is that the number of nonzero elements in the rate matrices increases with lag times. The models fit at the shortest lag time are more sparse than those at longer lag times. This is what you'd expect, but it's interesting.

In this dataset (Shaw WW), the shortest lag time (200 ps) is much too short to good timescales, but it is quite sparse (~90%), and that is useful information.

![download 1](https://cloud.githubusercontent.com/assets/641278/6497368/5dfe57c4-c293-11e4-8fc0-b9a566c2d9fd.png)

The suggestion here is that we should try constraining the models built with lag time > 1 to have a sparsity pattern that we'd get from the model at lag time 1.

**Comment by jchodera** [comment]
Well, this is presumably due to the prior you're using, which enforces rate constants of zero between states you have observed no transitions.

Statistical mechanics says that, for *any* fixed lag time tau, the rate constant will be nonzero between any two regions of configuration space because there is a nonzero probability that a trajectory can begin in one state and terminate in another state, even if the states do not share an interface in configuration space.

**Comment by rmcgibbo** [comment]
I think you're confusing the rate constant (continuous time master equation) and the finite-lag transition probabilities. The finite-lag transition probabilities are dense and positive, but the rate constants are only non-negative.

**Comment by rmcgibbo** [comment]
The models I'm working with here are continuous-time master equations, estimated from discrete-time data.

**Comment by jchodera** [comment]
Not at all.  The rate matrix K is related to the transition matrix by exp[Kt] = T(t).  It is not the same as an instantaneous time generator with sparse structure.  It will, in general, have strictly positive entries in the off-diagonal.  I can point you to some literature on this if it would help.

**Comment by rmcgibbo** [comment]
I can share the manuscript that describes this code with you, if you like. The key quantity estimated by [the code I'm talking about](https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/msm/ratematrix.py#L21) is a sparse instantaneous time generator, `K_{ij} = lim_{\tau -> 0} P(x_{t+\tau} = j | x_t = i) / \tau`.

When K is irreducible (though sparse), `T(\tau) = exp[K\tau]` is strictly positive (dense).

**Comment by jchodera** [comment]
No, no, you definitely don't want the zero-time limit.  That won't give you what you want at all.  We've been through this several times in the past with other collaborators.

Let me dig up some literature for you, but a Skype call may be the easiest way to clear this up.

**Comment by jchodera** [comment]
Important papers in multistate rate theory (which point out the difference between the matrix of phenomenological rate constants and the instanteous-time generator, and how the generator isn't what you want):
* J. E. Adams and J. D. Doll, Surface Science, 111, 492 397 (1981).
* A. F. Voter and J. D. Doll, J. Chem. Phys., 82, 80 (1985).

**Comment by msultan** [comment]
Sorry for jumping in but I would love to see the reference.

**Comment by jchodera** [comment]
More forthcoming, but these two build on Chandler's reactive flux theory to generalize it to multiple states.  There is a clear difference between the t->0 limit (which will be a strict overestimate of all rates and give you very poor estimates of the time correlation functions and transition matrix when exponentiated) and the matrix of phenomenological rate constants (estimated for sufficiently large t by exp[T t] = T(t)) that will give you an excellent estimate of the observed correlation functions and transition matrix.

There *is* a way to estimate the correlation functions and finite-time transition matrices accurately from an instantaneous time generator, but only if you permit negative rates, which is frankly weird.  

Digging up references.

**Comment by jchodera** [comment]
Here's an interesting technical report from Markus Weber and Susana Röblitz (neé Kube) on the exact approximation of finite-time transition matrices using infinitesimal rate matrices, which leads to negative off-diagonal elements:
http://webdoc.sub.gwdg.de/ebook/serien/ah/reports/ZIBreport/ZR-05-43.pdf

**Comment by rmcgibbo** [comment]
I don't think you're clear on what we're actually doing in this code. Perhaps this is my fault for using the wrong terminology (e.g. infinitesimal generator vs. phenomenological rate matrix).

In general, I would suggest that discussing this on github issues is not the most productive way to go. It's too easy to come off as inappropriately patronizing, and too difficult to attach math. Frankly, I'd rather keep the discussion here more based on the software and model development aspects. If you want to conduct this over email, that would be better.

**Comment by jchodera** [comment]
> I can share the manuscript that describes this code with you, if you like.

Happy to take a look!

**Comment by jchodera** [comment]
> In general, I would suggest that discussing this on github issues is not the most productive way to go. It's too easy to come off as inappropriately patronizing, and too difficult to attach math. Frankly, I'd rather keep the discussion here more based on the software and model development aspects. If you want to conduct this over email, that would be better.

Sorry!  Definitely didn't mean to be patronizing.  Just wanted to point out some stuff you might find useful.

**Comment by rmcgibbo** [comment]
lol. perhaps you can see how others might get the wrong impression though?

**Comment by jchodera** [comment]
Again, apologies.  Happy to chat over email instead---I just didn't see your suggestion about that appear until I was a few more replies in.
