### ISSUE TITLE
Model is *not* saved with the pickle protocol

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#496]
The help text for the command lines say 

>Path to save fit model instance. This is the model,
>                        after parameterization with fit(), saved using the
>                        pickle protocol

But the models are *not* saved using the pickle protocol. They are saved using joblib, and if you try to `pickle.load` them, you get `Key error: Z`

cc @apeck12

Solutions:
 1. save using pickle format
 1. Change help text

I think we should do (1)

**Comment by rmcgibbo** [comment]
I don't have strong feelings. (1) is fine.

**Comment by kyleabeauchamp** [comment]
I'm happy with either, although I suppose we should double check that pickle isn't insanely slow for tICA models with modest numbers of features.

**Comment by mpharrigan** [comment]
Empirically, I pickle tica models all the time (with O(1000) features) with no problems, although I think py3.4 has a fancier pickle protocol

**Comment by kyleabeauchamp** [comment]
Sounds fine to me.

**Comment by mpharrigan** [comment]
Steps
- [ ] measure a couple filesizes to make sure it's not different
- [ ] change to saving pickle
- [ ] change to load as pickle, load as joblib if that fails (backwards compatible)

**Comment by mpharrigan** [comment]
```python
data = np.random.rand(500, 1000)
tica = tICA()
tica.fit([data])
print(tica.timescales_) # force solve
```

what | size | time
-------|------|---------
joblib | 29 mb | 900 ms
pickle 4 | 31 mb | 291 ms
pickle 3 | 31 mb | 281 ms
pickle 2 | 44 mb | 488 ms

note: joblib does some limited compression

**Comment by kyleabeauchamp** [comment]
Cool

**Comment by rmcgibbo** [comment]
+1
