### ISSUE TITLE
Issue with running clustering?

### ISSUE THREAD

**Issue by acadev** [msmbuilder/msmbuilder#497]
I was trying out the clustering algorithm using K-means using the example code on the web-page and I am getting this error: 

>>> cluster = KMeans(n_clusters=10);
>>> cluster.fit(dataset)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/v33/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/msmbuilder-3.1.0.dev0-py2.7-macosx-10.6-x86_64.egg/msmbuilder/cluster/base.py", line 47, in fit
    check_iter_of_sequences(sequences, allow_trajectory=self._allow_trajectory)
  File "/Users/v33/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/msmbuilder-3.1.0.dev0-py2.7-macosx-10.6-x86_64.egg/msmbuilder/utils/validation.py", line 48, in check_iter_of_sequences
    if not isinstance(X, md.Trajectory) and X.ndim != ndim:
AttributeError: 'tuple' object has no attribute 'ndim'

Am not entirely sure if I have any error in loading the file - but I did not get any error in loading the trajectories. 

Any help will be really appreciated. 

Best,
Arvind

**Comment by kyleabeauchamp** [comment]
What is the type and shape of dataset?

**Comment by acadev** [comment]
The data set I was loading was a DCD file with a PDB file as the topology. 

The shape of the dataset is (50000, 30).

**Comment by schwancr** [comment]
How did you load ```dataset``` in the above example?

**Comment by acadev** [comment]
import mdtraj
 import numpy
dataset = [];
for trajFile in ['IDR1.dcd']:
     t = md.load(trajFile, top='IDR1.pdb');
     dataset.append(md.compute_phi(t));

from msmbuilder.cluster import KMeans
cluster = KMeans(n_clusters=10);
cluster.fit(dataset);

This is what I was using. May be I am doing something. I was just using the same code that was on the geometric clustering web page.

**Comment by synapticarbors** [comment]
I can reproduce this:

```python
from msmbuilder.example_datasets import AlanineDipeptide
import mdtraj as md

dataset = AlanineDipeptide().get()
trajectories = dataset.trajectories
topology = trajectories[0].topology

dataset = []
for t in trajectories:
    dataset.append(md.compute_phi(t))

from msmbuilder.cluster import KMeans
cluster = KMeans(n_clusters=10)
cluster.fit(dataset)
```

With the error:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-c0d018af695f> in <module>()
      5 from msmbuilder.cluster import KMeans
      6 cluster = KMeans(n_clusters=10)
----> 7 cluster.fit(dataset)

/Users/lev/Projects/github/msmbuilder-1/msmbuilder/cluster/base.pyc in fit(self, sequences, y)
     45         self
     46         """
---> 47         check_iter_of_sequences(sequences, allow_trajectory=self._allow_trajectory)
     48         super(MultiSequenceClusterMixin, self).fit(self._concat(sequences))
     49 

/Users/lev/Projects/github/msmbuilder-1/msmbuilder/utils/validation.pyc in check_iter_of_sequences(sequences, allow_trajectory, ndim, max_iter)
     46                 value = False
     47                 break
---> 48         if not isinstance(X, md.Trajectory) and X.ndim != ndim:
     49             value = False
     50             break

AttributeError: 'tuple' object has no attribute 'ndim'
```

**Comment by synapticarbors** [comment]
The issue is that `md.compute_phi` returns a tuple:

http://mdtraj.org/latest/api/generated/mdtraj.compute_phi.html#mdtraj.compute_phi

The tuple is the indices and the angles. Try the following:

```python
dataset = []
for t in trajectories:
    dataset.append(md.compute_phi(t)[1])
```

or 

```python
dataset = []
for t in trajectories:
    indices, phi = md.compute_phi(t)
    dataset.append(phi)
```

**Comment by mpharrigan** [comment]
We also have featurizers to help with this sort of thing
```
from msmbuilder.dataset import dataset
from msmbuilder.featurizer import DihedralFeaturizer
ds = dataset(["IDR1.dcd"])
dihed = DihedralFeaturizer(['phi'])
dihedrals = dihed.fit_transform(ds)
```
The syntax of the above may be a bit off but it's something along those lines

**Comment by acadev** [comment]
Thank you all so much for your help! Much appreciate it!
