### ISSUE TITLE
Add gilliespie / waiting_time sampler to ratematrix?

### ISSUE THREAD

**Issue by kyleabeauchamp** [msmbuilder/msmbuilder#504]
It should be reasonable for these functions to be shared between the MSM and RateMatrix classes, at least under the assumption that we use $T = exp(-Kt)$ to draw samples in the RateMatrix classes.

I figured we might want to discuss this before making a PR as there are a few ways to do it.

The generalization to bayesian models is another thing to think about, but I imagine most people will probably want to use the MCMC average (or perhaps the MAP) rate matrix for such situations.

**Comment by mpharrigan** [comment]
Seems like a good idea to me

**Comment by rmcgibbo** [comment]
The description of the first argument for `MarkovStateModel.draw_samples` isn't correct. It's not really obvious what that function does.

**Comment by rmcgibbo** [comment]
For `sample`, which propagates the model, there is a more subtle decision to make.
 -  You could either sample a discrete-time sequence (state of the system at t=[0,1,2,3,...]) from `exp(Kt)`.
 - You could could use Gillespie to sample the continuous-time process, which would be represented like a list of tuples of `(state, waiting_time_before_jumping_to_next_state)`.

**Comment by kyleabeauchamp** [comment]
Agreed.  Maybe two functions? `ContinuousTimeMSM.sample()` and `ContinuousTimeMSM.sample_waiting_time()` where the first one is the same as for MSM?

**Comment by rmcgibbo** [comment]
Not sure about the names, but +1 to having both available as separate functions.

**Comment by kyleabeauchamp** [comment]
Regarding implementing `sample()`: is the cleanest way to do this to add a `SampleMixin` upstream of both MSM and ContinuousTimeMSM?

**Comment by mpharrigan** [comment]
Not having one function with a `method="discrete, gillespie"` kwarg?

**Comment by kyleabeauchamp** [comment]
The output data types are so different for gillespie that I think it merits a separate function.  Otherwise the docstring will be hideous.

**Comment by rmcgibbo** [comment]
@mpharrigan if that choice just changed the way it ran the calculation, then +1 to a flag. but here, it changes the semantics of the return value. you really are simulating different things.

**Comment by rmcgibbo** [comment]
> Regarding implementing sample(): is the cleanest way to do this to add a SampleMixin upstream of both MSM and ContinuousTimeMSM?

Whichever is simplest.

**Comment by kyleabeauchamp** [comment]
OK, this is mostly done in #507.  The outstanding issue is the waiting time / gillespie part, which will require actual work that I am too lazy to do.  The title of this issue has been changed to reflect the remaining agenda item.
