### ISSUE TITLE
KMedoids cluster_ids_ is in concatenated space

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#514]
The indices would ideally be of the `form (traj_i, frame_i)`

**Comment by rmcgibbo** [comment]
Yeah, that would be ideal. `KMedoids` could override `fit()` from
`_KMedoids` to call super, and then remap this.

**Comment by mpharrigan** [comment]
This functionality might be best in `MultiSequenceClusterMixin`?

**Comment by rmcgibbo** [comment]
Maybe? But not every clustering has the concept of `cluster_ids_`. e.g. for kmeans or something, no remapping is necessary.

**Comment by rmcgibbo** [comment]
Maybe putting a method/staticmethod that is capable of doing the remapping into `MultiSequenceClusterMixin` makes sense, but then actually "manually" calling it from `KMedoids`  with `self.cluster_ids_` would make sense.

**Comment by mpharrigan** [comment]
I agree

**Comment by rmcgibbo** [comment]
:+1:

**Comment by mpharrigan** [comment]
Can I de-double-underscore `MultiSequenceClusterMixin.__lengths`

**Comment by rmcgibbo** [comment]
yeah sure. whatever makes sense.
