### ISSUE TITLE
Why libdistance instead of scipy.spatial.distance?

### ISSUE THREAD

**Issue by pfrstg** [msmbuilder/msmbuilder#516]
libdistance appears to be a fork of some earlier version of code that went into scipy.

I can see that you have several methods not available in the c code backing scipy.spatial.distance (assign_nearest, sumdist) but these should be easily implementable on top of scipy.spatial.distance.

The downside of libdistance is that you don't have the wide variety of distance metrics available in scipy.spatial.distance

**Comment by rmcgibbo** [comment]
- `scipy.spatial.distance` doesn't support RMSD
 - the distance calculations that we commonly do for clustering, e.g. `assign_nearest`, are often labeling a large college of data points with thee index of their nearest neighbor from amongst a relatively small collection. The individual pairwise distance calculations required for this are fast enough that the python call overhead is really significant, so having the whole loop in cython is a big win.

**Comment by rmcgibbo** [comment]
also, if you want to calculate say,` pdist(X, X[[1,10,20], :])`, the numpy overhead of copying out those particular elements of `X` is usually more expensive than the entire distance calculation, which is why I wanted to have the `X_indices` argument to all the functions.

**Comment by kyleabeauchamp** [comment]
I think this has been pretty well discussed by Robert, feel free to re-open otherwise
