### ISSUE TITLE
[CI] HTTP timeout when testing command line

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#517]
It would be nice if we could:
 1. wait longer
 2. try again
 3. catch this

So these timeouts don't result in a failing build.

**Comment by rmcgibbo** [comment]
i agree. i think at minimum we could try repeating the request up to, say, 3 times. or maybe move the files somewhere else, since figshare is flakey.

**Comment by rmcgibbo** [comment]
(fixing this now)

**Comment by rmcgibbo** [comment]
This could be fixed by #534. Not really 'fixed', but worked around by retrying the request.
