### ISSUE TITLE
DihedralFeaturizer Command

### ISSUE THREAD

**Issue by kyleabeauchamp** [msmbuilder/msmbuilder#524]
IMHO, we should update the helpstring for the command line Dihedral featurizer.  Below is the actual command line string that works, but it took me like 15 minutes to figure out how to properly provide this input.  The current helpstring is misleading, IMHO:

```
current helpstring:
Parameters:
  --types TYPES [TYPES ...]
                        One or more of ['phi', 'psi', 'omega', 'chi1', 'chi2',
                        'chi3', 'chi4'] (default: ['phi', 'psi'])


working command line
msmb DihedralFeaturizer --trj "./trajectories/*.h5" --out dihedrals-withchi/ --types "phi" "psi" "chi1"
```

**Comment by rmcgibbo** [comment]
+1 to adding something. I'm not exactly sure how to do it though, because the docstring is pulled from the  class. Maybe just adding a string with an example cmdline invocation into the `DihedralFeaturizerCommand` class, that can be appended into help text?

**Comment by kyleabeauchamp** [comment]
Agreed.  After figuring out how this all works, that seemed to me like the least painful way to do this.
