### ISSUE TITLE
support scikit-learn 0.16

### ISSUE THREAD

**Issue by pfrstg** [msmbuilder/msmbuilder#525]
scikit-learn 0.16 removes utils.array2d which is used by
   cluster/ndgrid.py
   decomposition/tica.py /tmp

I've gotten this to work by just replacing array2d with check_array but I'm not 100% sure this is the right fix and this can not be used to support both scikit-learn versions (since check_array does not exist in < 0.16). Any thoughts on how you want to handle this?

**Comment by rmcgibbo** [comment]
we could simply copy-paste the appropriate validation function into `msmbuilder.utils`, and not depend on scikit-learn for this function.

**Comment by kyleabeauchamp** [comment]
+1, I thought they were supposed to give us deprecation warnings on shit like this

**Comment by rmcgibbo** [comment]
(a) I don't think the `utils` subpackage was officially part of their public api. (b) I think I saw this on their mailing list, but forgot about it. sry.

**Comment by kyleabeauchamp** [comment]
Another possibility is to upgrade to `check_array`: see, e.g. 

 https://github.com/scikit-learn/scikit-learn/pull/4484

**Comment by mpharrigan** [comment]
see @pfrstg 's first post :)

**Comment by kyleabeauchamp** [comment]
lol

**Comment by rmcgibbo** [comment]
Fixed by #528.
