### ISSUE TITLE
Change `dataset` to `open_dataset` or the like?

### ISSUE THREAD

**Issue by kyleabeauchamp** [msmbuilder/msmbuilder#526]
So I personally find it a bit confusing that we have a dataset module, a  `_BaseDataset` class, and a helper function called `dataset`.  

I propose that the function call gets renamed to something like `open_dataset` or `load_dataset`.  Any thoughts?

**Comment by mpharrigan** [comment]
-1 `dataset()` is a factory function that takes care of constructing a dataset object

**Comment by kyleabeauchamp** [comment]
I suppose I'm flexible on this one.
