### ISSUE TITLE
When to release 3.2.0?

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#530]
In light of #529, we should probably discuss the release timeline for 3.2.0. The last (3.1) release was on Feb 27, and there have been 60 commits since.

We could either decide on a particular data to do the release, or start to enumerate (tag them with a milestone here on github) the particular features and bugfixes that we want to implement before then.

**Comment by mpharrigan** [comment]
I would vote asap so people can install using conda

**Comment by kyleabeauchamp** [comment]
I think I agree, I will make a sweep this evening.

**Comment by kyleabeauchamp** [comment]
I made pass and assigned several issues to the v3.2 milestone.  I basically picked things that seemed like easy low-hanging fruit that can be fixed with minimal effort.  I'll try to attack a couple of them this evening.

**Comment by mpharrigan** [comment]
This is the only issue left in the 3.2 milestone

**Comment by kyleabeauchamp** [comment]
+1

**Comment by mpharrigan** [comment]
- [x] github tag
- [x] pypi
- [ ] conda builds (in progress?)
- [ ] windows conda build
- [ ] docs

**Comment by kyleabeauchamp** [comment]
Some conda builds are uploaded already:

https://binstar.org/omnia/msmbuilder/files

**Comment by kyleabeauchamp** [comment]
OSX 64 done, linux is building now AFAIK

**Comment by mpharrigan** [comment]
great

**Comment by mpharrigan** [comment]
@rmcgibbo can you push the docs?

**Comment by rmcgibbo** [comment]
docs done, modulo some problems with the ipython notebook css

**Comment by mpharrigan** [comment]
If I can get windows building on appveyor soon, what do you think about releasing a quick 3.2.1 with the windows fixes, deprecation fix, and doc building fix

**Comment by kyleabeauchamp** [comment]
Fine with me
