### ISSUE TITLE
DOC: Link to papers referenced in docstrings

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#537]
If you look in the docs on the web, the references section of each methods documentation doesn't ever either link to a footnote or to the paper itself.

e.g. http://msmbuilder.org/latest/generated/msmbuilder.msm.MarkovStateModel.html#msmbuilder.msm.MarkovStateModel.uncertainty_timescales

It would be nice if these linked directly to the paper. I'm not sure how to do this. Maybe by adding the DOI to the plain text citation and then modifying numpydoc/sphinx?

Not a high priority, but it would be nice.

**Comment by mpharrigan** [comment]
The latest docs seem to include a footnote. This still isn't a link, but it's probably good enough.

http://msmbuilder.org/development/_msm/msmbuilder.msm.MarkovStateModel.html#msmbuilder.msm.MarkovStateModel.uncertainty_timescales
