### ISSUE TITLE
Indexing semantics for dataset are all wrong

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#539]
Is it like a list with "keys" as contiguous indices and a `len`? Or are they filenames, integers? It's kind of a mess right now.

**Comment by mpharrigan** [comment]
+1 for figuring this out

**Comment by kyleabeauchamp** [comment]
I guess I'd vote for something that feels like pandas

**Comment by mpharrigan** [comment]
I think it should be pandas-y too, but we may have to convince @rmcgibbo :panda_face:

**Comment by mpharrigan** [comment]
@msultan is writing a "pull structures" script right now where he keeps track of trajectories in a dictionary keyed on trajectory filename. This involves patterns like:
```python
transformed_dict = {}
for k in traj_dict:
   transformed_dict[k] = tica.partial_transform(traj_dict[k])
```

**Comment by mpharrigan** [comment]
I've sketched out my ideal view of dealing with datasets in this gist
https://gist.github.com/mpharrigan/c2b68d8d015133f1e387

**Comment by mpharrigan** [comment]
I'm working incrementally towards improving this with #610 and #722 

Datasets should be dictionary-like with meaningful keys

**Comment by cxhernandez** [comment]
@mpharrigan: was this done in #722 and #768?
