### ISSUE TITLE
Save pickled object when using command line?

### ISSUE THREAD

**Issue by kyleabeauchamp** [msmbuilder/msmbuilder#542]
It might be useful for applying the same transformation to some new data in a script.  

The example that springs to mind is making figures, where one might want to transform a trajectory containing just the crystal structure.

**Comment by mpharrigan** [comment]
We already do this :)

**Comment by kyleabeauchamp** [comment]
Oh did you implement this in your pickle PR?

**Comment by mpharrigan** [comment]
The commands save the object using `utils.dump`. The docstrings always said "pickle protocol" but it had been using joblib.dump. Now it uses pickle (but `utils.load` can load either)

https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/commands/fit_transform.py#L82

**Comment by kyleabeauchamp** [comment]
Ah.  What about dihedral featurization?  Should we also pickle the
featuriZer?

**Comment by mpharrigan** [comment]
That's something to consider. No reason not to give the option

**Comment by mpharrigan** [comment]
This is related to #392

**Comment by kyleabeauchamp** [comment]
I think this is implemented in PR #546
