### ISSUE TITLE
potential bug with tICA fitting

### ISSUE THREAD

**Issue by evanfeinberg** [msmbuilder/msmbuilder#553]
Hello MSMBuilders, 

It's been a great pleasure to learn how to use this software package. I believe I've found a bug with tICA fitting. 

I first instantiate a tICA object, then use it to fit to a set of features, and then try to project the result into a reduced data set. Unfortunately, no matter which method I use -- fit_transform() or fit() then transform() -- I get the same error, that I must fit the model before using it. 

Here is the relevant code:

```python
traj = md.load(traj_files, top = "/home/enf/b2ar_analysis/H-05/system.pdb", stride=100)
phi_psi_chi2 = DihedralFeaturizer(types=['phi','psi','chi2'])
features = phi_psi_chi2.transform(traj_list = tram)
tica_model = tICA(n_components=4)
fitted_model = tica_model.fit(features)
reduced_data = fitted_model.transform(features)
```

The same error is thrown if I use this code instead:
```
tica_model = tICA(n_components=4)
reduced_data = tica_model.fit_transform(features)
```
Here is the error itself:
```
  File "find_states.py", line 65, in <module>
    reduced_data = fitted_model.transform(features)
  File "/home/enf/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/decomposition/tica.py", line 306, in transform
    X_transformed = np.dot(X, self.components_.T)
  File "/home/enf/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/decomposition/tica.py", line 213, in components_
    return self.eigenvectors_[:, 0:self.n_components].T
  File "/home/enf/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/decomposition/tica.py", line 198, in eigenvectors_
    self._solve()
  File "/home/enf/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/decomposition/tica.py", line 166, in _solve
    raise RuntimeError('must fit the model before using it')
RuntimeError: must fit the model before using it
```
Thanks for any help in resolving this.

Cheers,
Evan

**Comment by evanfeinberg** [comment]
PS when I use "partial_fit()" on the same set of featurized data I receive the following error:

Traceback (most recent call last):
  File "find_states.py", line 64, in <module>
    fitted_model = tica_model.partial_fit(features)
  File "/home/enf/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/decomposition/tica.py", line 282, in partial_fit
    self._fit(X)
  File "/home/enf/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/decomposition/tica.py", line 372, in _fit
    self._outer_0_to_T_lagged += np.dot(X[:-self.lag_time].T, X[self.lag_time:])
ValueError: shapes (1490,1,2777) and (2777,1,1490) not aligned: 2777 (dim 2) != 1 (dim 1)

**Comment by rmcgibbo** [comment]
Yeah, that looks weird. I'll take a look shortly.

**Comment by evanfeinberg** [comment]
Thanks! Go to sleep first?

On Thu, Apr 16, 2015 at 12:47 AM, Robert T. McGibbon <
notifications@github.com> wrote:

> Yeah, that looks weird. I'll take a look shortly.
> On Apr 16, 2015 12:41 AM, "Evan N. Feinberg" <notifications@github.com>
> wrote:
>
> > PS when I use "partial_fit()" on the same set of featurized data I
> receive
> > the following error:
> >
> > Traceback (most recent call last):
> > File "find_states.py", line 64, in
> > fitted_model = tica_model.partial_fit(features)
> > File
> >
> "/home/enf/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/decomposition/tica.py",
> > line 282, in partial_fit
> > self._fit(X)
> > File
> >
> "/home/enf/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/decomposition/tica.py",
> > line 372, in _fit
> > self._outer_0_to_T_lagged += np.dot(X[:-self.lag_time].T,
> > X[self.lag_time:])
> > ValueError: shapes (1490,1,2777) and (2777,1,1490) not aligned: 2777 (dim
> > 2) != 1 (dim 1)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/msmbuilder/msmbuilder/issues/553#issuecomment-93667713>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msmbuilder/msmbuilder/issues/553#issuecomment-93668823>
> .
>



-- 
Evan N. Feinberg | Ph.D. Student,
     Stanford University, 2018 | M.D. Student,
          Yale School of Medicine, 2022

**Comment by mpharrigan** [comment]
This may happen if all of the trajectories are too short and none of them can be used to fit

**Comment by cxhernandez** [comment]
we should add a warning then

**Comment by evanfeinberg** [comment]
Is there a rule of thumb for minimum number of trajectories needed for
fitting and minimum for how many frames each needs to contain?

**Comment by cxhernandez** [comment]
has to be longer than the tICA lagtime

**Comment by evanfeinberg** [comment]
Thanks to all for your help. It's resolved.
