### ISSUE TITLE
Ghmm does not build on windows x64

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#559]
The sse math functions have a lot of `#ifdef USE_SSE2` which seems to not be set.

This might be because x64 visual studio enables sse2 by default an ignores `/arch:SSE2` command line flags.

Adding a macro define to `setup.py` (setting `USE_SSE2`) fixes the compile error.

I'm trying to figure out how to include this macro define only for msvs x64 and welcome ideas

**Comment by mpharrigan** [comment]
I actually don't know if this flag gets set on 32 bit windows builds. It falls back on MMX which is *not* supported for x64 (but is for x86_32)

**Comment by mpharrigan** [comment]
After discussion with @rmcgibbo , it seems the `USE_SSE2` macro was never defined in our codebase. Perhaps it has been falling back on MMX for all platforms. We're going to try defining the macro unconditionally

**Comment by rmcgibbo** [comment]
do you want to try this again w/ the new code?

**Comment by mpharrigan** [comment]
Works on my laptop!
