### ISSUE TITLE
Featurizing and definition of protein residues

### ISSUE THREAD

**Issue by evanfeinberg** [msmbuilder/msmbuilder#563]
Dear MSMBuilders,

I've been attempting to featurize with phi, psi, and chi2 dihedral angles a set of trajectories, each of the same receptor in slightly different conditions. For example, in one simulation, a residue might be a charged Asp, while in another, it is neutral. However, the publishers of these simulations renamed the charged residue as "ASH". Therefore, when I tell msmbuilder to only read in protein atoms, with selection language:

top = md.load_frame(filename, 0).topology
atom_indices = [a.index for a in top.atoms if a.residue.chain.index == 0 and a.residue.is_protein]
traj = md.load(filename, stride=stride, atom_indices=atom_indices)

, it includes the Asp for one simulation but does not when it has been renamed to Ash. I circumvented the issue by changing my atom selection to:

atom_indices = [a.index for a in top.atoms if a.residue.chain.index == 0 and a.residue != "POPC"]

, but it would be nice to be able to use "is_protein".

It may be worth some consideration to change the way "is_protein" attribute is defined to encompass "engineered" residues as well, with non-standard three letter names. Maybe we can discuss sensible ways to make "is_protein" definition more flexible without having too wide of a scope? 

Cheers and thanks as always for your thoughts,
Evan

**Comment by cxhernandez** [comment]
Just an FYI, this should be written as an issue for [mdtraj](https://github.com/mdtraj/mdtraj).

The way residue selection works is by checking with the lists in [`residue_names.py`](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/residue_names.py). You can file a pull request to add Ash (and other non-canonical residue names) to this list.

As a quick hack, I'd suggest making a PDB of the engineered protein and sed replace 'Ash' with 'Asp'. Then you can load that topology and use it for atom selection.

**Comment by evanfeinberg** [comment]
Thank you. Totally agreed. Will add the issue there. It turns out it's a bigger problem. Even for different protonation states of histidine (HIE, HID, HIP, etc.) some dihedrals are recognized, and some ain't. These are relatively common naming conventions so I may not be the only one this is impacting. Going to post it there now.

**Comment by evanfeinberg** [comment]
OK everyone, I have an update! I should've gone to sleep about 5 hours ago but I'm pretty sure I've narrowed down what the problem is.

the issue appears to be that MDtraj is looking for the ["CA", "CB", "CG", "ND1"] sequence (as defined in line 289 of dihedral.py) in the trajectory by calling _atom_sequence from the function compute_chi2. In the loop in that function, it checks all the residue objects for those that contain that sequence. And therein lies the problem. Even though, for example, HIS93 is chemically one combined residue, in the PDB file it is split up into two parts, one containing N, CA, C, O, and then a ton of lines corresponding to other residues, and then more lines pertaining to CB, CG, ND1, CD2, CE1, etc. So, even though they all have the residue number "93", and they all have the same residue name "HIE", and even though they're all in the same chain, when MDTraj reads in this trajectory/topology, it must assume that these are two separate residues understandably because they are physically separated in the PDB file. 

To test this, I opened an ipython notebook and ran:

for residue in topology.chain(0).residues:
     if str(residue)[0] == "H": print residue

output (notice how they are all repeated, even though each instance of His93, His172, etc. should be combined into a single residue object)

HIS93
HIS172
HIS178
HIS93
HIS172
HIS178
HIS269
HIS296
HIS269
HIS296

So that would mean there are two potential options for fixing the problem:

1. Fixing topology reading, wherein atoms with the same residue name, number, and chain are combined into a single object. 


2. _atom_sequence is modified to be more flexible. This is probably the easier one.

Please let me know if any contributions would be helpful if any revisions of code are necessary. 

Best,
Evan

**Comment by evanfeinberg** [comment]
![screen shot 2015-04-22 at 5 01 25 am](https://cloud.githubusercontent.com/assets/1760982/7273871/a6f1d6d8-e8ac-11e4-8b3b-688eaa17a04c.png)
![screen shot 2015-04-22 at 5 01 09 am](https://cloud.githubusercontent.com/assets/1760982/7273872/a6f9bd44-e8ac-11e4-919c-47a178c3ecc7.png)

**Comment by evanfeinberg** [comment]
![screen shot 2015-04-22 at 5 02 09 am](https://cloud.githubusercontent.com/assets/1760982/7273881/c3cc8ef6-e8ac-11e4-8ff9-65fead02a059.png)

**Comment by evanfeinberg** [comment]
Darn, just realized this should've been posted to MDTraj. Consequences of doing this at 5am...

**Comment by mpharrigan** [comment]
continued at mdtraj/mdtraj#805
