### ISSUE TITLE
Supported compilers

### ISSUE THREAD

**Issue by peastman** [msmbuilder/msmbuilder#571]
Is there any official list of what compiler versions are supported/required?  I'm wondering whether I can assume that certain compiler features are available: C++11, OpenMP (and if so, what version), AVX, AVX2.

**Comment by rmcgibbo** [comment]
I don't think we have anything official. I know we require SSE3. Maybe gcc 4.4.7?

**Comment by rmcgibbo** [comment]
What would you suggest?

**Comment by peastman** [comment]
The biggest restriction will be Windows, since you need to use the same version of Visual Studio that was used to compile Python.  According to http://docs.continuum.io/anaconda/faq.html#compile-cpython, Anaconda is compiled with VS 2008 for 2.6/2.7, and VS 2010 for 3.3/3.4.

Neither one of those supports C++11, so that's out.  VS 2010 officially supports AVX, but I've found it to be buggy and I disable it on OpenMM.  As for OpenMP, here's what they say at http://openmp.org/wp/openmp-compilers.  "Implements OpenMP 2.0  Not all versions support OpenMP. Visual Studio 2008 supports OpenMP in the Standard, Professional and Team System Editions. Visual Studio 2010 supports OpenMP in the Professional, Premium and Ultimate Editions."

As for other compilers:

gcc has had reasonably complete C++11 support since 4.8 and AVX support since 4.6.  OpenMP support includes 2.5 since GCC 4.2, 3.0 since GCC 4.4, and 3.1 since GCC 4.7.

clang has reasonably full C++11 support since 3.3, AVX since 3.0.  OpenMP support still seems to be "in progress".  The standard version of clang doesn't include it, but there's a separate project (https://clang-omp.github.io) that has added it.

So, um... what features can I use?  Are there any of these features that you *already* use?

**Comment by rmcgibbo** [comment]
We already use SSE3 (but not SSE4.1) and OpenMP. I'm not sure which particular version of OpenMP we use -- probably the most basic one. The OpenMP features we've used so far are essentially just `#pragma omp for`

**Comment by peastman** [comment]
Ok, I'll assume that's what I can use.
