### ISSUE TITLE
Feature request: NaN handling

### ISSUE THREAD

**Issue by Trayder** [msmbuilder/msmbuilder#585]
Throughout the code NaNs are either treated as infinity or cause errors. I'd like the option for them to be zero.

In Msmbuilder 2.0 I found that boolean contacts were the best choice for clustering my system.
It's simple enough to reimplement boolean in MSMbuilder 3.0 (sidenote: clustering methods are inconsistent in regards to accepting/rejecting integers) but I quickly run into trouble with handling NaNs.

The difficulty in this, is that the distance calculations are spread out between scipy, fastcluster, and cython and if you miss one there isn't necessarily an error.

**Comment by rmcgibbo** [comment]
Can you give any particular tracebacks  or examples of the particular
pieces of code you're talking about?

**Comment by Trayder** [comment]
from kcenters.py
d = libdistance.dist(X, X[new_center_index], metric=self.metric)
Returns distance matrix d including NaNs

from agglomerative.py
d = pooling_func(dists[:, self.landmark_labels_ == i])
returns distance matrix with NaNs

from minibatchkmedoids.py
dmat = libdistance.pdist(X, metric=self.metric, X_indices=minibatch_indices)
returns distance matrix with NaNs

from minibatchkmedoids.py
self.labels_, self.inertia_ = libdistance.assign_nearest(
            X, self.cluster_centers_, metric=self.metric)
empties my all 0's cluster because distance (all 0's to all 0's) is NaN

from fastcluster.py
X = pdist(X, metric)
returns X containing NaNs

**Comment by rmcgibbo** [comment]
Do you have any sense of what properties of the input data is causing you to get NaNs? For example, does the input data itself contain NaNs or infs? Or maybe extremely large values? What metric are you using?

**Comment by Trayder** [comment]
I'm using jaccard, and I've converted my featurization to boolean. I expect NaNs in the 0 contacts case, which is the only time I get them. There isn't a bug, I would just like to treat NaNs as 0 so that my zero contact vectors will be assigned to the same cluster.

**Comment by rmcgibbo** [comment]
Maybe others can chime in tomorrow, but I don't think converting NaNs to anything else is the right approach -- the presence of NaNs in a calculation indicates that something is wrong.

The fact that `jacard([0,0], [0,0])` is NaN indicates, IMO, that if `[0,0]` is taken to be inside the problem domain, then the Jaccard metric is inappropriate.

**Comment by rmcgibbo** [comment]
If the metric you actually want to use for clustering is `d(x,y) := all(x==0) && all(y==0) ? 0 : jaccard(x,y)`, then that's fine, and will avoid the NaNs.

**Comment by Trayder** [comment]
I think you're right that custom metrics are the best way to do it. That way we can skip the "It makes sense but not mathematically" argument.

In which case this just becomes a request for custom metric support.

**Comment by rmcgibbo** [comment]
We don't support custom metrics, but the easiest thing for your purposes might simply be to add the particular metric that you're interested in to the code.

If you're up for implementing this feature, it shouldn't require too much work. Basically the steps would be:

1. pick a name, and add the name here: https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/libdistance/libdistance.pyx#L17-L19
2. add the name to the appropriate docstrings too, e.g. https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/libdistance/libdistance.pyx#L229-L230
3. add an implementation of the metric to distance_kernels.h https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/libdistance/src/distance_kernels.h#L191-L202
4. modify metric_double and metric_float to return appropriate the function pointer by adding it to the list https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/libdistance/src/distance_kernels.h#L270
5. add a test to test_libdistance.py
