### ISSUE TITLE
Free energy values and Markov models

### ISSUE THREAD

**Issue by akiikius** [msmbuilder/msmbuilder#598]
Is it possible to use the msmbuilder software to generate and associate a given macro state to a free energy value (e.g. kcal/mol)?

Thanks!

**Comment by rmcgibbo** [comment]
Sure. `MarkovStateModel.populations_` is an estimator for the stationary distribution of the dynamics. The free energies are proportional to their logs.

**Comment by akiikius** [comment]
Thanks for the tip. Is there a link i can go to and find some flags that i can look at or use as an example to follow?

**Comment by rmcgibbo** [comment]
There aren't any examples in the docs, but there's not much to do... Just $\Delta G_{ij} = -kT \ln \frac{\pi_j}{\pi_i}$.

**Comment by akiikius** [comment]
I already have some macrostates from a
previous analysis. I also have specific probabilities associated with each of
the states that are linked to each state. I guess I have to re-analyze the data
from scratch or this can be an added step to obtain the log data?

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Sat, Jun 6, 2015 at 5:13 PM, msmbuilder/msmbuilder
<reply@reply.github.com>
wrote:
There aren't any examples in the docs, but there's not much to do... Just
$\Delta G_{ij} = -kT \ln \frac{\pi_j}{\pi_i}$.

—
Reply to this email directly or view it on GitHub
[https://github.com/msmbuilder/msmbuilder/issues/598#issuecomment-109654200] .[https://github.com/notifications/beacon/AFdls3-3w-NP4BBlpPplaTZCtu2gm1mYks5oQ2fygaJpZM4E6ecb.gif]

**Comment by cxhernandez** [comment]
@akiikius are you familiar with [NumPy](http://www.numpy.org/)? Like @rmcgibbo said, it should be fairly easy to calculate a change in free energy:

``` python
import numpy as np

k = 1.38*1E-23 # Boltzmann Constant (m^2*kg*s^-2*K^-1)
T = 300 # Temperature of Simulation (K)

dG = -k*T*np.log(Pi/Pj)
```

where `Pi` is the equilibrium probability of the macrostate you're interested in, and `Pj` is the macrostate you want to compare too (e.g. the ground state).

**Comment by akiikius** [comment]
Hi, Am marginaly familiar with numpy but I should be able to perform the proposed steps. I appreciate the help you have given.
