### ISSUE TITLE
single h5 trajectory and count matrix

### ISSUE THREAD

**Issue by bhaskardg08** [msmbuilder/msmbuilder#600]
Dear MSMbuilders,
    I am new to latest version (3.2) and used your legacy version from command line before (more than 5 months). In current version I am having some problem somewhere in loading trajectory, featurize, transform, assignment and MarkovStateModel pipeline (as shown in your Ala-dipeptide tutorial). What I did is as follows:
1) Importing stuffs,
2) Reading in AtomIndex file for my system (index),
3) Load h5 trajectory: ds = md.load('Trajectories/trj0.h5')
4) Featurize: featurizer = SuperposeFeaturizer(index, ds[0])
5) Transform: sequences = featurizer.transform(ds)
6) An initial guess about clustering: assignments = KCenters(n_clusters=25).fit_predict(sequences)
7) MSM: MarkovStateModel(lag_time=1, verbose=True).fit(assignments)
showing : "MSM contains 25 strongly connected components above weight=1.00. Component 0 selected, with population nan%"
In 7) step I see that code selects component 0 with population nan%, and possible reason for this is not in restricting to  strongly_connected_subgraph as I still have 25 components (see above). If I change step 7) to a very approximate computation
 MarkovStateModel(lag_time=1,ergodic_cutoff=0.0,reversible_type='none',verbose=True).fit(assignments) then code catches error: 
"
/home/bhaskar/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/msm/msm.py:221: RuntimeWarning: invalid value encountered in true_divide
  transmat = rc.astype(float) / rc.sum(axis=1)[:, None]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bhaskar/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/msm/msm.py", line 194, in fit
    self.transmat_, self.populations_ = fit_method(self.countsmat_)
  File "/home/bhaskar/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/msm/msm.py", line 223, in _fit_asymetric
    u, lv = scipy.linalg.eig(transmat, left=True, right=False)
  File "/home/bhaskar/anaconda/lib/python2.7/site-packages/scipy/linalg/decomp.py", line 146, in eig
    a1 = asarray_chkfinite(a)
  File "/home/bhaskar/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 613, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
"
So I added a few print statements in core.py under _transition_counts following line 453:
print(len(sequences)) # shows 10101 = the number of frames in my trajectory
print(classes)             # shows [ 0  1  2  3  ... 23 24] correctly
for y in sequences[:10]:    # iterate over first 10
      y = np.asarray(y)                                    # doing what code will do next
      from_states = y[: -lag_time: 1]               # doing what code will do next
      to_states = y[lag_time::1]                       # doing what code will do next
      print(y)                    # shows [1]
      print(from_states)   # shows []
      print(to_states)       # shows []

That is count matrix will be empty in this case.
So my guess is either 1) above steps 1-7 are faulty in dealing with loading one h5 trajectory and processing it correctly. or 2) there is a strange bug somewhere associated to one h5 trajectory.

**Comment by kyleabeauchamp** [comment]
You should be passing a list of trajectories as your ds

**Comment by rmcgibbo** [comment]
we should do a better job catching this with a good error message

**Comment by bhaskardg08** [comment]
Thanks for prompt answer. However it is not obvious from Ala-dipeptide tut.

**Comment by rmcgibbo** [comment]
yeah, @bhaskardg08, you're right.

**Comment by bhaskardg08** [comment]
I am closing it. Thanks.
