### ISSUE TITLE
Timescales calculation

### ISSUE THREAD

**Issue by bhaskardg08** [msmbuilder/msmbuilder#601]
Dear MSMBuilders,
    This is not serious may be, but may worth looking at. 
     I have a trajectory for which I am approximately calculating MSM (I assigned 25 clusters before this to my data), by 
msm = MarkovStateModel(lag_time=1,ergodic_cutoff=0.0,reversible_type='none',verbose=True).fit(assignments)
followed by, timescales = msm.timescales_ 
showing a warning about invalid divide coming line 302 in core.py under _normalize_eigensystem. The problem is that one of the eigenvector component becomes zero. So normalizing will yield nan in left and right vectors.
This means either 25 cluster decomposition is bad or I must use ergodic trimming. (In case of ergodic trimming no such problem). But such warning cannot be ignored and it is actually an error.
Suggestion please.

**Comment by bhaskardg08** [comment]
I little addition. Since we are working with stochastic matrices having one eigenvector component to be zero is impossible. This only means the count matrix contains disconnected component and that can happen if reversible_type='none'. However, if count matrix is symmetrized then ergodicity is imposed. So eigenvectors must be positive. 
Therefore reversible_type='none' is very error-prone and may break the code downstream. Please think about raising appropriate error.

**Comment by mpharrigan** [comment]
symmetrization does not enforce ergodicity; `ergodic_cutoff='on'` does. This option finds the largest connected component and throws out unconnected states.

Please use the recommended `ergodic_cutoff='on', reversible_type='mle'` unless you have a compelling reason not to (and a very well-sampled dataset)

**Comment by bhaskardg08** [comment]
My mistake. symmetrization enforces reversibility not ergodicity. so in my feeling if reversible_type='transpose' or 'mle' we enforce that the system is reversible and it is possible to find a stationary distribution. My comment was reversible_type='none' may lead to entirely wrong calculation of eigenvectors. And my concern is why reversible_type='mle' and ergodic_cutoff='off' lead to problems in eigenvector calculations?

**Comment by mpharrigan** [comment]
The mle estimator only works on a fully connected graph
