### ISSUE TITLE
Wrong lumping results when using PCCA/PCCA+ with more than 10 macrostates

### ISSUE THREAD

**Issue by gfzhou** [msmbuilder/msmbuilder#603]
I believe this bug is due to that the number of eigenvectors calculated by the class MarkovStateModel() is limited by the n_timescales which is default to 10. In class PCCA/PCCA+() the n_macrostates will not update the n_timescales. So if I use more than 10 macro states, the results will still give me only 10 macro states.
Could you check on that please? Thanks.

**Comment by Trayder** [comment]
Was just running into the same problem.
Quick fix is to pass n_timescales=None so it'll be calculated from n_macrostates, e.g.:
PCCA(n_macrostates=20, n_timescales=None)

The default of 10 also causes issues with implied_timescales(), which requires passing n_timescales twice, e.g.:
implied_timescales(n_timescales=20, msm=MarkovStateModel(n_timescales=20)

**Comment by mpharrigan** [comment]
Thanks for pointing this out. Should be an easy enough fix
