### ISSUE TITLE
Implement tICA scaling

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#605]
see Noe and Clementi, 2015 (http://arxiv.org/abs/1506.06259)

**Comment by kyleabeauchamp** [comment]
It's quite similar to the weighted transform option that we have, IIRC

**Comment by rmcgibbo** [comment]
Yeah, it's not very different practically, but the theory is better.

**Comment by mpharrigan** [comment]
Closed in #766
