### ISSUE TITLE
msmb AtomIndices does not heed exact output name

### ISSUE THREAD

**Issue by Trayder** [msmbuilder/msmbuilder#606]
Small bug, but nevertheless well positioned to confuse people.

Using the command line:
`msmb AtomIndices -p system.pdb -d --minimal -o Contacts_protein.dat`
The output is written to Contacts_protein.txt
I would expect output to be written to Contacts_protein.dat and used the wrong file :(

**Comment by rmcgibbo** [comment]
This was intentional. Especially for the other file formats, we want to
encourage a consistent file type <-> extension mapping across users. It
especially makes debugging easier.
