### ISSUE TITLE
How to use v2.8 tutorial on v3.3

### ISSUE THREAD

**Issue by SBolo** [msmbuilder/msmbuilder#607]
Hi everybody,
I'm new with MSMBuilder and I'm looking for a simple tutorial to get started. More precisely, what I want to obtain is to cluster a set protein folding trajectories to obtain the corresponding Markov States and, more importantly, the transition matrix between those states for further use. The tutorial I found is valid for the 2.8 version (available on the corresponding page) of MSMBuilder and seems not to work on the latest version. Do you have any idea of what can I do? Any other source where I can learn basic features of the software in order to achieve what I need? Since I'm really new with this software, the examples proposed on the latest version page seem a bit too advanced for me and never show (maybe I didn't look well enough!) how to get the transition matrix between Markov States in practice (for example loading the topology file and the .dcd's??). 
I'm not really sure if this is the correct place where to ask this kind of questions, so let me know if I'm off-topic. Thank you very much for your help.

**Comment by mpharrigan** [comment]
Hi, you may be interested in the command line tutorial http://msmbuilder.org/latest/commandline.html

**Comment by SBolo** [comment]
Thank you for your help! I should have been clearer in explaining what I
need: beyond clustering trajectories, I need to obtain the transiton matrix
between the markov states. How should I do that (hypotetically after the
procedure described in the tutorial you suggested me)?
Thank you again!!
Il 16/lug/2015 19:01, "Matthew Harrigan" <notifications@github.com> ha
scritto:

**Comment by cxhernandez** [comment]
Hi @SBolo,

You could try:
```shell
$ msmb MiniBatchKMeans --inp tica_trajs.h5 --out clustered_traj.pkl  --n_clusters 100
$ msmb MarkovStateModel --inp clustered_traj.pkl --out msm.pkl
```
Then open `msm.pkl` in Python:
```python
>>> import pickle
>>> msm = pickle.load('msm.pkl')
```

The transition matrix should be stored in `msm.transmat_`.

**Comment by SBolo** [comment]
Perfect, thank you!!! I have a few questions more: how do I know how many components I need for tICA? And how do I know how many clusters to choose for clustering (you choose 100 for example) and how to validate the results? I'm sorry but this information is very hard to find online anywhere else!

**Comment by SBolo** [comment]
Also, the MarkovStateModel command drops me the following error:
"IOError: Sorry, no loader for filename=clustered_traj.pkl (extension=.pkl) was found. I can only load files with extensions in ['.xtc', '.pdb.gz', '.hoomdxml', '.restrt', '.h5', '.lammpstrj', '.xml', '.inpcrd', '.mdcrd', '.xyz.gz', '.stk', '.xyz', '.crd', '.lh5', '.dtr', '.nc', '.hdf5', '.pdb', '.dcd', '.rst7', '.mol2', '.netcdf', '.trr', '.gro', '.ncdf', '.ncrst', '.binpos', '.arc']"

**Comment by cxhernandez** [comment]
@SBolo: Sorry I was mistaken above. To use `MarkovStateModel`, you will need to use the `--transformed` flag during clustering:

```shell
$ msmb MiniBatchKMeans --inp tica_trajs.h5 --out cluster.pkl --transformed clustered_traj.h5 --n_clusters 100
$ msmb MarkovStateModel --inp clustered_traj.h5 --out msm.pkl --lag_time 1
```

As far as which tICA lag time to select, there are a couple of options: 1) systematically search throughout the space of possible MSM parameters (see [Osprey](https://github.com/pandegroup/osprey)) or 2) if you have any prior knowledge of the process you are modeling pick a handful of tICA lag times that are a few orders of magnitude faster (e.g. if a protein folds in tens of microseconds, choose a lag time in the 100s of nanoseconds to microseconds range). 

Picking the number of clusters is a similar challenge, but we've found when using tICA models that 100-300 states fare pretty well. Of course, the *right* number of clusters is also somewhat sampling-dependent, as too small of a number leads to a very coarse-grained model and too large of one could lead to poor statistics. You can always use Osprey to optimize this parameter as well.

**Comment by SBolo** [comment]
Thank you @cxhernandez for your explanation. Your help is priceless to me! One last thing: if I execute the Python command 
>>> import pickle
>>> msm = pickle.load('msm.pkl')

I get another error, which is: "AttributeError: 'str' object has no attribute 'readline' ". Any clue?

**Comment by mpharrigan** [comment]
Hi, the output of the `msmb MarkovStateModel` command should include something like:
```
Saving "msm.pkl"... (<class 'msmbuilder.msm.msm.MarkovStateModel'>)
To load this MarkovStateModel object interactively inside an IPython
shell or notebook, run: 

  $ ipython
  >>> from msmbuilder.utils import load
  >>> model = load('msm.pkl')
```

Use these command instead!

[The reason why @cxhernandez's code doesn't work is that `pickle` expects a file-like object, not a filename. You would have to do 
```python
import pickle
f = open("msm.pkl", 'rb')
msm = pickle.load(f)
```
the `load()` function in msmbuilder *does* take a filename, and will always work with the output of the command line commands]

**Comment by cxhernandez** [comment]
+1 my bad

**Comment by SBolo** [comment]
Now I have a more physical question. I obtained the transition matrix as you told me to do but there's something about it that puzzels me: if I look at its spectrum it doesn't show a zero eigenvalue, the presence of whose should tell me that the system reaches thermal equilibrium at some time, as it should be. Is this a sampling problem due to wrong parameters (I used the ones in the command line tutorial and the ones you listed me) or is it a more subtle one?

**Comment by mpharrigan** [comment]
The equilibrium process has eigenvalue 1

**Comment by SBolo** [comment]
Ok, I get it. We have different conventions for the transiton matrix! Your
matrix T is e^(-beta K), where K is mine.
Il 18/lug/2015 23:43, "Matthew Harrigan" <notifications@github.com> ha
scritto:

**Comment by rmcgibbo** [comment]
If you want a continuous time model, see the ContinuousTimeMSM class, and
http://arxiv.org/abs/1504.01804

**Comment by SBolo** [comment]
@rmcgibbo thank you! What I wanted to obtain is exactly the rate matrix for the WW domain of Fip 35 from ANTON trajectories (after the test with alanine). I'm reading the paper right now for the theoretical background. However, on a practical point of view, what does it change in the procedure described by @cxhernandez and @mpharrigan to obtain the ContinuousTimeMSM? And, is it possible to "visualize" the Markov States in some way? If so, how?

**Comment by cxhernandez** [comment]
If you save the transition/rate matrix as a matrix market file, like so:

```python
>>> from scipy import io as sio
>>> sio.mmwrite('transmat.mtx', msm.transmat_)
```

Then you can upload this file to [MSMExplorer](http://msmexplorer-d3.herokuapp.com/) (beta) to visualize the states and any transition paths.

**Comment by SBolo** [comment]
I tried, but it returns me an error: "Aw shucks! MSMExplorer-d3 requires a Matrix Market file as input.". Moreover: is there any way in which I can obtain a .pdb representation of the Markov states for further use? Maybe it's too much..

**Comment by cxhernandez** [comment]
Hmm, perhaps the format has been updated in the past year...? I'll have to update the code. In the meantime, maybe the older [desktop version](https://simtk.org/home/msmexplorer) still works?

**Comment by SBolo** [comment]
Perfect! I'm downloading it right now. What about the .pdb's? Any clue?

**Comment by cxhernandez** [comment]
Maybe @rmcgibbo or @mpharrigan know an easier way, but you could use [MDTraj](mdtraj.org) to load your Shaw trajectories and the clustered trajectories, `clustered_traj.h5`, and then pick a few frames for a particular state (e.g. state 10 in your 100-state model):

``` python
>>> import numpy as np
>>> import mdtraj as md
>>> from mdtraj.io import loadh
>>> #Load Data
>>> traj = md.load('shaw_traj.xtc', top='shaw_pdb.pdb')
>>> clust_traj = loadh('clustered_traj.h5')
>>> #Find Relevant Frames
>>> state = 10
>>> keys = clust_traj.keys()
>>> frames = np.where(clust_traj[keys[0]] == state)[0]
>>> #Save 5 random frames from state 10 to PDB
>>> np.random.shuffle(frames)
>>> traj[frames[:5]].save_pdb('state10.pdb')
```

**Comment by SBolo** [comment]
This works perfectly! If I get correctly, I have to refer to a particular
choice of shaw_traj.xtc (of course I have more of them and I can load just
one of them at the time with this method), so I guess that the result
should not be trajectory dependent thanks to the clustering. Am I right?

Il giorno dom 19 lug 2015 alle ore 19:29 Carlos Hernández <
notifications@github.com> ha scritto:

**Comment by cxhernandez** [comment]
I believe `keys`, from the snippet above, is a list of the names of the clustered trajectories contained within `clust_traj` (I definitely could be wrong). Either way, you should be able to match the elements of `keys` to the specific trajectories you started with, and presumably even loop over `keys` to perform state extraction automatically:

``` python
>>> for key in keys:
        traj = md.load(key + '.xtc', top='shaw_pdb.pdb')
        [do other stuff here...]
```

**Comment by cxhernandez** [comment]
@SBolo: I updated [MSMExplorer-d3](https://msmexplorer-d3.herokuapp.com/), so it should be compatible with latest version of MSMBuilder.

**Comment by SBolo** [comment]
Thank you! Now it works perfectly for the creation of the pathways. Still I get some problems with logos: if I try to load a .pdb file for a logo (created as you previously suggested, but with just a frame for state) I get a blank circle and nothing more. Should I set the .pdb in some other way? Moreover: how should I acknowledge the use of MSMExplorer-d3 for my master thesis and, in case, a research paper?

**Comment by cxhernandez** [comment]
Could you send one of your PDB files to cxh[at]stanford.edu for testing?

You can cite MSMExplorer-d3 using this bibtex entry:
```
@misc{carlos_hernandez_2015_20726,
  author       = {Carlos Hernández},
  title        = {msmexplorer-d3: v0.3},
  month        = jul,
  year         = 2015,
  doi          = {10.5281/zenodo.20726},
  url          = {http://dx.doi.org/10.5281/zenodo.20726}
}
```

**Comment by rmcgibbo** [comment]
@mpharrigan, @cxhernandez: can you look through this issue and add any appropriate examples or explanations to http://msmbuilder.org/latest/commandline.html
