### ISSUE TITLE
v3.3 release planning

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#613]
Probably would be a good idea to do a release (~130 commits). I think the latest release doesn't contain the new-ish HMM code.

**Comment by mpharrigan** [comment]
I agree. 

There are some outstanding issue that we should take care of first. Tagging with milestones

**Comment by mpharrigan** [comment]
Ok, I tagged everything aggressively for 3.3. It's probably too ambitious. I'm thinking it would make more sense to punt the documentation and dataset related issues to 3.4, make sure we fix bugs, and release the new hmm code for 3.3

**Comment by mpharrigan** [comment]
I moved most of the "new feature" open issues/prs to the 3.4 milestone.

Now 3.3 contains things that (IMO) need to be finished before we release

**Comment by mpharrigan** [comment]
This is the last remaining issue tagged with v3.3. I'm going to work on performing the release

**Comment by mpharrigan** [comment]
- [x] pypi
- [ ] conda packages
- [x] docs

**Comment by mpharrigan** [comment]
This is done
