### ISSUE TITLE
Lag-time/number of MS trade-off and non-reversible MSM

### ISSUE THREAD

**Issue by SBolo** [msmbuilder/msmbuilder#616]
Hi everyone,
when building a good MSM with tICA and ContinuousTimeMSM (or simply MSM) I understand that there are 4 critical parameters: 
- the number of tICA components
- the correlation lag-time
- the number of Markov States
- the Markov State lag-time

Now, I read some papers in the last few days (Efficient maximum likelihood parametrization of continuous-time Markov process, Statistical Model for Markov Models of Biomolecular Dynamics, Improvements in Markov State Model Construction Reveal Many Non-Native interactions in the folding of NTL9 and others) and faced the fact that those parameters need to be validated in some way because, of course, there is no a priori way to assign them. The validation method proposed in those papers is the same for all the last three parameters: look for a plateau in the relaxation time-scales. Now the first question: how can I use the same validation method for all the three parameters? Should I do a sort of three-parameter optimization or there are some better methods to establish the best values for the three parameters singularly? Furthermore: what is the dimension of lag-times in MSMBuilder functions? Nanoseconds, microseconds or what?

The second question is about the first paper in the list, Efficient maximum [...]. I will have to deal, in a close future, with non-reversible trajectories and the paper proposes a method to build MSM without imposing detailed balance. Is this feature implemented in MSMBuilder? If so, how can I use it?

Thank you very much for your support!

**Comment by mpharrigan** [comment]
Hi, check out this paper for performing cross-validation to tune adjustable parameters *except* for the final model's lag time. This is usually chosen as 1-10 ns

There is an example of doing GMRQ model selection here: http://msmbuilder.org/latest/examples/gmrq-model-selection.html

To not impose detailed balance, pass `reversible_type=None` to the constructor for `MarkovStateModel` http://msmbuilder.org/latest/generated/msmbuilder.msm.MarkovStateModel.html#msmbuilder.msm.MarkovStateModel

**Comment by rmcgibbo** [comment]
> The second question is about the first paper in the list, Efficient maximum [...]. I will have to deal, in a close future, with non-reversible trajectories and the paper proposes a method to build MSM without imposing detailed balance.

It does? I don't recall discussing the non-reversible case.

**Comment by SBolo** [comment]
@rmcgibbo for what I remember you started with the general case and then included also the detailed balance condition!!

**Comment by rmcgibbo** [comment]
Sure, but it's not very detailed computationally. There's no discussion of the parameterization K(\theta) for the non-reversible case, except I guess the the full n^2-n case.

Anyways, there is no implementation in MSMBuilder of the nonreversible continuous time estimator.

**Comment by SBolo** [comment]
Yes you're right! 
Oh I see. I will use the standard MSM for that then!

**Comment by SBolo** [comment]
So how do I obtain the rate matrix (not the transition matrix) from the standard MSM?

**Comment by rmcgibbo** [comment]
It's not so simple. You can't just pull out a continuous-time Markov model directly from a discrete-time Markov model -- if you could I wouldn't have written that paper. For more background on this problem, look up the literature of the "markov embedding problem", e.g. http://ejp.ejpecp.org/article/view/733

**Comment by SBolo** [comment]
Sorry if I ask again but: what is the unit time in the ContinouosTimeMSM lag-time and tICA lag-time?

**Comment by mpharrigan** [comment]
frames of input data

**Comment by SBolo** [comment]
You mean that if I have a 10ns trajectory composed by 10.000 snapshots, then lag-time 1 is equivalent to 0.001ns? Additionally: the rates by which the rate matrix is composed are in 1/lag-time units?

**Comment by mpharrigan** [comment]
yes
