### ISSUE TITLE
standardized features

### ISSUE THREAD

**Issue by evanfeinberg** [msmbuilder/msmbuilder#621]
When a tICA model is fit by msmbuilder, it is my understanding that some standardization scheme is conducted on each of the features. Something like, for each column in the data X, the mean of each column is subtracted and then it is divided by its feature standard deviation, or something similar. What is the exact standardization process done? Is there any way to verbosedump or save the standardized data matrices? This may be very useful in tIC analysis. 

Thanks!
Evan

**Comment by mpharrigan** [comment]
Featurizers don't do anything like this.

The dimensionality reduction techniques (tICA and PCA) normalize by the variance. Check docstrings to be sure. tICA also has `weighted_transform`, which will scale tics by their slowness. The Noe group has a new thing (http://publications.mi.fu-berlin.de/1567/) which is analogous (as I understand it) to the "percent explained variance" in PCA. It might do something different wrt normalization. This isn't implemented in msmbuilder (yet)

**Comment by evanfeinberg** [comment]
Thanks, Matt. I just printed out the paper you referred to, checking it out
now.

On Tue, Aug 4, 2015 at 9:50 AM, Matthew Harrigan <notifications@github.com>
wrote:

> Featurizers don't do anything like this.
>
> The dimensionality reduction techniques (tICA and PCA) normalize by the
> variance. Check docstrings to be sure. tICA also has weighted_transform,
> which will scale tics by their slowness. The Noe group has a new thing (
> http://publications.mi.fu-berlin.de/1567/) which is analogous (as I
> understand it) to the "percent explained variance" in PCA. It might do
> something different wrt normalization. This isn't implemented in msmbuilder
> (yet)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msmbuilder/msmbuilder/issues/621#issuecomment-127672450>
> .
>



-- 
Evan N. Feinberg | Ph.D. Student,
     Stanford University, 2018 | M.D. Student,
          Yale School of Medicine, 2022
