### ISSUE TITLE
scipy：ValueError: On entry to DGEEV parameter number 5 had an illegal value

### ISSUE THREAD

**Issue by liyigerry** [msmbuilder/msmbuilder#632]
I run this [tutorial](http://msmbuilder.org/latest/examples/hmm-and-msm.html) with my MD trajectory.
But I got this error. How can I solve it?

```python
import mdtraj as md

traj = md.load('md.pdb')
top = traj.topology
```

```python
traj[0]
```

    <mdtraj.Trajectory with 1 frames, 4018 atoms, 401 residues, and unitcells at 0x7fbb2d053c90>

```python
from msmbuilder.featurizer import SuperposeFeaturizer

indices = [atom.index for atom in top.atoms if atom.element.symbol in ['C', 'O', 'N']]
featurizer = SuperposeFeaturizer(indices, traj[0])
sequences = featurizer.transform(traj)
```

```python
sequences
```

    [array([[  2.38418579e-07,   3.57627869e-07,   2.38418579e-07, ...,
               3.72529030e-09,   3.37174782e-07,   2.01165676e-07]], dtype=float32),
     array([[  0.18999685,   0.19535545,   0.18493104, ...,  13.97593117,
               0.19982722,   0.18160734]], dtype=float32),
     array([[  0.31719765,   0.3062093 ,   0.34325635, ...,  13.87491608,
               0.22319701,   0.12363409]], dtype=float32),
     array([[ 0.68303543,  0.64916712,  0.61398292, ...,  0.10289033,
              0.52415812,  0.16349769]], dtype=float32),
     array([[  0.74398297,   0.72333276,   0.67631149, ...,  13.98940659,
              13.8490696 ,  13.9800024 ]], dtype=float32),
     array([[ 14.13575363,  14.06112099,  13.96469307, ...,  14.09330273,
               1.8607614 ,  14.12775135]], dtype=float32),
     array([[ 14.38491631,  14.33718395,   2.39974141, ...,  13.79321671,
               1.56526268,  13.81032658]], dtype=float32)]

```python
%matplotlib inline
from matplotlib import pyplot as plt

plt.hist(sequences, bins=50, log=True)
plt.ylabel('Frequency')
plt.show()
```

![output_5_0](https://cloud.githubusercontent.com/assets/10556381/9325513/6dd1a8d0-45c5-11e5-974f-4532b8d1724f.png)

```python
from msmbuilder.cluster import KCenters
from msmbuilder.msm import MarkovStateModel

msmts0, msmts1 = {}, {}
lag_times = [1, 10, 20, 30, 40]
n_states = [4, 8, 16, 32, 64]

for n in n_states:
    print n
    msmts0[n] = []
    msmts1[n] = []
    for lag_time in lag_times:
        print lag_time
        assignments = KCenters(n_clusters=n).fit_predict(sequences)
        msm = MarkovStateModel(lag_time=lag_time, verbose=False).fit(assignments)
        timescales = msm.timescales_
        msmts0[n].append(timescales[0])
        msmts1[n].append(timescales[1])
        print('n_states=%d\tlag_time=%d\ttimescales=%s' % (n, lag_time, timescales[0:2]))
    print()
```

    4
    1

    ---------------------------------------------------------------------------

    ValueError                                Traceback (most recent call last)

    <ipython-input-6-f39c791f1ebe> in <module>()
         14         assignments = KCenters(n_clusters=n).fit_predict(sequences)
         15         msm = MarkovStateModel(lag_time=lag_time, verbose=False).fit(assignments)
    ---> 16         timescales = msm.timescales_
         17         msmts0[n].append(timescales[0])
         18         msmts1[n].append(timescales[1])

    /usr/local/lib/python2.7/dist-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/msm/msm.pyc in timescales_(self)
        495         Generation and validation." J. Chem. Phys. 134.17 (2011): 174105.
        496         """
    --> 497         u, lv, rv = self._get_eigensystem()
        498 
        499         # make sure to leave off equilibrium distribution

    /usr/local/lib/python2.7/dist-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/msm/msm.pyc in _get_eigensystem(self)
        347 
        348         k = n_timescales + 1
    --> 349         u, lv, rv = _solve_msm_eigensystem(self.transmat_, k)
        350         self._eigenvalues = u
        351         self._left_eigenvectors = lv

    /usr/local/lib/python2.7/dist-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/msm/core.pyc in _solve_msm_eigensystem(transmat, k)
        282         The normalized right eigenvectors (:math:`\psi`) of ``transmat``
        283     """
    --> 284     u, lv, rv = scipy.linalg.eig(transmat, left=True, right=True)
        285     order = np.argsort(-np.real(u))
        286     u = np.real_if_close(u[order[:k]])

    /usr/local/lib/python2.7/dist-packages/scipy/linalg/decomp.pyc in eig(a, b, left, right, overwrite_a, overwrite_b, check_finite)
        163     lwork, info = geev_lwork(a1.shape[0],
        164                              compute_vl=compute_vl,
    --> 165                              compute_vr=compute_vr)
        166     if info != 0:
        167         raise LinAlgError("internal *geev work array calculation failed: %d" % (info,))

    ValueError: On entry to DGEEV parameter number 5 had an illegal value

```python

```

**Comment by mpharrigan** [comment]
Nothing jumps out to me as obviously wrong. It's failing while trying to get the eigensystem of the transition matrix. What does `msm.transmat_` look like?

**Comment by mpharrigan** [comment]
Oh wait. It's because `n_timescales` > `n_states` (ie 4). As a workaround, pass in `n_timescales=3` to the constructor

**Comment by mpharrigan** [comment]
#603 is also due to the default n_timescales not being appropriate. To solve this, maybe we should keep it as `None` if not specified and check for none everywhere.

In this case, we should also give a better error message if the user explicitly sets a bad value for number of timescales

**Comment by liyigerry** [comment]
I captured the error in this code

``` python
timescales = msm.timescales_
```
And I changed the n_timescales and n_states. Setting n_timescales=3 got the same error. And passing n_timescales >= n_state or <nstate also got the same error.

```python
from msmbuilder.cluster import KCenters
from msmbuilder.msm import MarkovStateModel

msmts0, msmts1 = {}, {}
lag_times = [20, 30, 40]
n_states = [16, 32, 64]

for n in n_states:
    print n
    msmts0[n] = []
    msmts1[n] = []
    for lag_time in lag_times:
        print lag_time
        assignments = KCenters(n_clusters=n).fit_predict(sequences)
        msm = MarkovStateModel(n_timescales=10, lag_time=lag_time, verbose=False).fit(assignments)
        timescales = msm.timescales_
        msmts0[n].append(timescales[0])
        msmts1[n].append(timescales[1])
        print('n_states=%d\tlag_time=%d\ttimescales=%s' % (n, lag_time, timescales[0:2]))
    print()
```

    16
    20



    ---------------------------------------------------------------------------

    ValueError                                Traceback (most recent call last)

    <ipython-input-12-f7596dfcef05> in <module>()
         14         assignments = KCenters(n_clusters=n).fit_predict(sequences)
         15         msm = MarkovStateModel(n_timescales=10, lag_time=lag_time, verbose=False).fit(assignments)
    ---> 16         timescales = msm.timescales_
         17         msmts0[n].append(timescales[0])
         18         msmts1[n].append(timescales[1])


    /usr/local/lib/python2.7/dist-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/msm/msm.pyc in timescales_(self)
        495         Generation and validation." J. Chem. Phys. 134.17 (2011): 174105.
        496         """
    --> 497         u, lv, rv = self._get_eigensystem()
        498 
        499         # make sure to leave off equilibrium distribution


    /usr/local/lib/python2.7/dist-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/msm/msm.pyc in _get_eigensystem(self)
        347 
        348         k = n_timescales + 1
    --> 349         u, lv, rv = _solve_msm_eigensystem(self.transmat_, k)
        350         self._eigenvalues = u
        351         self._left_eigenvectors = lv


    /usr/local/lib/python2.7/dist-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/msm/core.pyc in _solve_msm_eigensystem(transmat, k)
        282         The normalized right eigenvectors (:math:`\psi`) of ``transmat``
        283     """
    --> 284     u, lv, rv = scipy.linalg.eig(transmat, left=True, right=True)
        285     order = np.argsort(-np.real(u))
        286     u = np.real_if_close(u[order[:k]])


    /usr/local/lib/python2.7/dist-packages/scipy/linalg/decomp.pyc in eig(a, b, left, right, overwrite_a, overwrite_b, check_finite)
        163     lwork, info = geev_lwork(a1.shape[0],
        164                              compute_vl=compute_vl,
    --> 165                              compute_vr=compute_vr)
        166     if info != 0:
        167         raise LinAlgError("internal *geev work array calculation failed: %d" % (info,))


    ValueError: On entry to DGEEV parameter number 5 had an illegal value

**Comment by mpharrigan** [comment]
what does msm.transmat_ look like

**Comment by mpharrigan** [comment]
what does it say when you set `verbose=True` in the markovstatemodel constructor

**Comment by mpharrigan** [comment]
I can reproduce this with ``scipy.linalg.eig(np.zeros((0,0)))`, which is possible from `_strongly_connected_subgraph`:

```python
if n_components == n_states_input and counts[np.ix_(keys, keys)] == 0:
    return np.zeros((0,0)), {}
```

This is only possible if you have a collection of trajectories each of length 1. Looking back at your original report, `featurizer.transform()` expects a **list** of trajectories. Since you pass it a single trajectory, it iterates over the frames of that trajectory, giving you `n` length-1 trajectories, from which dynamics cannot be modeled. Please use
```python
featurizer.transform([traj])
```

Maybe we should add some error checking, although I don't know how to do this without running afowl of duck-typing, pun very much intended

**Comment by liyigerry** [comment]
I used the 

```  python
featurizer.transform([traj])
```

and I got the
``` python
timescales_ = [ 16.73445894   9.36748681          nan          nan          nan         nan]
transmat_ = [[ 0.          0.          0.          0.88075908  0.          0.11924092
   0.        ]
 [ 0.          0.          0.12354068  0.54578118  0.0836953   0.04691406
   0.20006879]
 [ 0.          0.31468895  0.          0.68531105  0.          0.          0.        ]
 [ 0.04471534  0.46016602  0.22683612  0.18749998  0.04903884  0.0317437
   0.        ]
 [ 0.          0.43722855  0.          0.30384466  0.          0.25892679
   0.        ]
 [ 0.04065064  0.26560829  0.          0.21315728  0.28061327  0.
   0.19997053]
 [ 0.          0.84994842  0.          0.          0.          0.15005158
   0.        ]]
```

**Comment by mpharrigan** [comment]
I don't understand. If you got the timescales, then you didn't get the same error

**Comment by mpharrigan** [comment]
Can you clarify what you mean?

**Comment by liyigerry** [comment]
@mpharrigan Thanks.
I changed the trajectories I used, but always got the NAN in the timescales_
```
n_states=4	lag_time=1	timescales=[ 20.51711373  13.89153342]
n_states=4	lag_time=10	timescales=[ 30.23027371  21.09159064]
n_states=4	lag_time=20	timescales=[ 68.45980732  21.31863572]
n_states=4	lag_time=30	timescales=[ 58.99969027  15.6418585 ]
n_states=4	lag_time=40	timescales=[ 38.21221646          nan]
()
n_states=8	lag_time=1	timescales=[ 35.91054997  17.8466378 ]
n_states=8	lag_time=10	timescales=[ 96.02837307  27.93512461]
n_states=8	lag_time=20	timescales=[ 103.34055366   28.17943523]
n_states=8	lag_time=30	timescales=[ 38.17328012  20.75978116]
n_states=8	lag_time=40	timescales=[ 83.90513101  16.48940985]
()
n_states=16	lag_time=1	timescales=[ 44.56910722  12.6918147 ]
n_states=16	lag_time=10	timescales=[ 638.83406204   11.28717456]
n_states=16	lag_time=20	timescales=[ 14.37311236          nan]
```
It dues to the MD timescales I used? My trajectories run 2*50000=1000ps=1ns in each trajectory.
