### ISSUE TITLE
Problems with ContactFeaturizer

### ISSUE THREAD

**Issue by SBolo** [msmbuilder/msmbuilder#633]
Hi everyone,
I'm having some troubles using the ContactFaturizer. I'm in a directory called "msm" and to access trajectories and topology I need to follow the path '../ww_1-protein/'. But if I write the following command

msmb ContactFeaturizer --transformed features --top '../ww_1-protein/topology.pdb' --trjs '../ww_1-protein/*.dcd'

it tells me that I supplied no topology. I also tried to change the position of the file and even to change the path to something else expecting a different error but I always get the same problem. Moreover, I tried the same with AtomPairsFeaturizer and it works correctly. Any clue?

Thank you!

**Comment by mpharrigan** [comment]
Can you paste the whole error message

**Comment by mpharrigan** [comment]
Does any other featurizer work?

**Comment by SBolo** [comment]
Here's the whole message:

"Traceback (most recent call last):
  File "/Users/Simone/anaconda/bin/msmb", line 6, in <module>
    sys.exit(main())
  File "/Users/Simone/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/scripts/msmb.py", line 28, in main
    app.start()
  File "/Users/Simone/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/cmdline.py", line 440, in start
    instance.start()
  File "/Users/Simone/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-macosx-10.5-x86_64.egg/msmbuilder/commands/featurizer.py", line 66, in start
    for i, chunk in enumerate(input_dataset.iterload(key, chunk=self.chunk)):
  File "/Users/Simone/anaconda/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 455, in iterload
    topology = _parse_topology(top)
  File "/Users/Simone/anaconda/lib/python2.7/site-packages/mdtraj/core/trajectory.py", line 174, in _parse_topology
    raise TypeError('A topology is required. You supplied top=%s' % str(top))
TypeError: A topology is required. You supplied top=None"

Yes, Dihedral and AtomPairs work just fine but they generate like 80Gb of geatures and tICA never converges.

**Comment by mpharrigan** [comment]
1. I tried the contact featurizer on the fs_peptide example dataset with msmb v3.2.0 and it worked.

2. I looked at the source code near where it fails. If the given topology file path does not exist it silently sets `top = None`, which would explain the issue. Could you try launching an ipython shell
```
ipython
>>> import os
>>> os.path.exists(os.path.expanduser("../ww_1-protein/topology.pdb")
True
```

3. The traceback doesn't make any sense. The frame below `line 66, in start` immediately jumps to `line 455, in iterload` *in trajectory.py* instead of iterload in `dataset.py`. I don't fully understand this

**Comment by mpharrigan** [comment]
I could reproduce the traceback by misspelling the topology filename, however

**Comment by SBolo** [comment]
Thank you. The python code solved the problem, since the topology file was (for some unknown reasons??) corrupted and even if it was exactly there, the path resulted wrong. The error traceback made me think of an error of a different kind, sorry if I bothered. I changed the file and everythink worked correctly.
