### ISSUE TITLE
Easy way to extract centroids after clustering

### ISSUE THREAD

**Issue by lucentdm** [msmbuilder/msmbuilder#635]
Hi Everybody, I'm using MSMbuilder to do kmeans clustering on contact maps from a villin dataset.  I want to extract the index/file of each frame that is a final cluster center.  Is there an easy way to do this once the data has been featurized?

**Comment by cxhernandez** [comment]
If you have the `MarkovStateModel` object you can use [`draw_samples`](http://msmbuilder.org/latest/generated/msmbuilder.msm.MarkovStateModel.html?highlight=sample#msmbuilder.msm.MarkovStateModel.draw_samples).

**Comment by mpharrigan** [comment]
Note that that won't give you centroids.

With kmeans, the center of the cluster is not necessarily a data point (ie it works on the complete vector space of dihedrals, not discrete samples). You can use `msmbuilder.utils.KDTree` as a wrapper around sklearn's kdtree to find the nearest sample(s) to the cluster centers.

This will give you tuples of `(traj_i, frame_i)` like @cxhernandez 's answer above. It's up to you to turn those indices into molecular conformations by pulling frames (e.g. using `mdtraj`). We'd like to include this functionality built-in in the future

**Comment by jchodera** [comment]
Perhaps you want to use [K-medoids](http://msmbuilder.org/latest/generated/msmbuilder.cluster.KMedoids.html#msmbuilder.cluster.KMedoids), @lucentdm?  That would give you cluster generators that are actual data points.

**Comment by lucentdm** [comment]
Thanks all.  @jchodera K-medoids with the .cluster_ids_ attribute was exactly what I was looking for.
