### ISSUE TITLE
GMRQ analysis error

### ISSUE THREAD

**Issue by juanmit** [msmbuilder/msmbuilder#641]
Hi,

I am trying to do GMRQ analysis on MSMs, and it keeps giving me this error. I thought it was caused by different length of independent simulations but decreasing the lagtime did not help. Are there any ideas why?  Thank you for helping.

```
 test_score = msm.score(assignments_test)
  File "/home/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/msm/msm.py", line 449, in score
    V = self._map_eigenvectors(V, m2.mapping_)
  File "/home/anaconda/lib/python2.7/site-packages/msmbuilder-3.2.0-py2.7-linux-x86_64.egg/msmbuilder/msm/msm.py", line 468, in _map_eigenvectors
    source_indices, dest_indices = zip(*transform_mapping.items())
ValueError: need more than 0 values to unpack
```

**Comment by rmcgibbo** [comment]
Oh right. This comes from the training and test sets having no states in common after ergodic trimming -- i.e. the training set only traveled among states {0,1,2}, and the test set only visited states {3,4,5}.

**Comment by juanmit** [comment]
Thanks for helping. I will check all the trjs to make sure they are all making sense.
