### ISSUE TITLE
Optional arguments are required in Featurizers

### ISSUE THREAD

**Issue by jadeshi** [msmbuilder/msmbuilder#651]
Hey all, a potential bug in MSMBuilder 3.3.0:
I'm trying to featurize my trajectories using the ContactFeaturizer, so I'm running:

msmb ContactFeaturizer --out native_contact_features --top ../confout.gro --trjs "../results*/*.xtc" --contacts native_contacts_0-index

However, the script asks me for the --transformed argument as well, but it's listed in the help string as optional and it isn't passed in the tutorial. This issue exists for the AtomPairsFeaturizer as well.

**Comment by mpharrigan** [comment]
We need to update the documentation to be clear that `--transformed` is the new `--out`

**Comment by mpharrigan** [comment]
Calling it an optional argument is misleading, but it's `argparse`'s fault. It's as optional as the `--trjs` option
