### ISSUE TITLE
Featurization and parameters

### ISSUE THREAD

**Issue by HiddenTesla** [msmbuilder/msmbuilder#652]
Good morning,
I have a few questions about the use of MSMBuilder. They follow:
- suppose I have 2 trajectories which are divided in many different dcd files. Can I use the featurizer by just linking every separate file or should I merge the corresponding files into two separate trajectories? If it is of some information, I should use the ContactFeaturizer function;
- suppose the integration time step of my trajectories is T picoseconds. Then, to achieve a lag-time of T nanoseconds, should I specify '--lag_time 1e3' in the command line? The question regards both Time-structure Independent Components Analysis and Continuous Time Markov-State Model. 
- after the Markov State Model has been created, it returns me the timescales of the system, which I suppose are expressed in rationalized units. What should I do to convert them in nanoseconds? Multiply them by the equivalent of my lag-time in nanoseconds (in this case, T)? Or by T * lag_time maybe?

Thank you.

**Comment by HiddenTesla** [comment]
I also forgot to ask: after the Markov State Model has been created, it returns me the timescales of the system. What should I do to convert them in nanoseconds?

**Comment by mpharrigan** [comment]
1. You should concatenate the chunks at some point before doing tICA or MSM estimation. Featurization and clustering are independent to the order of data points. From the command line, read the help text for `msmb ConvertChunkedProject -h` carefully. It may do what you want.

2. The units in the code are always "frames". If your data is saved every picosecond and you want a lag time of 1 ns, specify lag time = 1000. Note that saving your data every picosecond is probably too often (for disk usage)

3. Still in units of "frames"

**Comment by mpharrigan** [comment]
Re-open if you have further questions
