### ISSUE TITLE
BACE in msmbuilder 3.0

### ISSUE THREAD

**Issue by juanmit** [msmbuilder/msmbuilder#655]
I am trying to use BACE method to lump the micro states into macro states. And I realize that BACE has not been built in msmbuilder 3.0. So I used BACE method in msmbilder 2.8 and get a set of .dat file. I am wondering how can I use these .dat files to build a Markov state model in msmbuilder 3.0? In other words. I am wondering that are there any ways I can convert these .dat files to a sequence for msmbuilder 3.0. Thanks a lot for helping.

**Comment by mpharrigan** [comment]
Is there a reason you don't want to use pcca+? 

Note for devs: maybe this is implemented in msmtools?

**Comment by juanmit** [comment]
Thanks for replying. 
Because one of the tutorials online is saying that PCCA+ will lead to poor macrostates so I am trying to use BACE instead of PCCA+. Is PCCA+ working well on msmbuilder 3 now?

**Comment by jchodera** [comment]
Wouldn't it be useful to have all of these methods available for comparison purposes?

Devs: What about working with the @franknoe folks to pull a full suite of lumping tools into [msmtools](https://github.com/markovmodel/msmtools) and utilizing that in both [`msmbuilder`](https://github.com/msmbuilder/msmbuilder) and [`pyemma`](https://github.com/markovmodel/PyEMMA)?

**Comment by mpharrigan** [comment]
Looks like msmtools has pcca+. I couldn't find bace

Yes, @jchodera that is how we would go about it

**Comment by mpharrigan** [comment]
@juanmit - to my knowledge, pcca+ has been the "standard" method for some time (including in msmb 2.8 tutorial)

**Comment by juanmit** [comment]
Thanks for helping. I  think I will use pcca+ for my current model.

**Comment by cxhernandez** [comment]
bace is implemented in #1050
