### ISSUE TITLE
GMRQ scores are not consistent from MSMBuilder 3.0 to 3.3

### ISSUE THREAD

**Issue by gfzhou** [msmbuilder/msmbuilder#656]
I found out that the GMRQ score of a same model from MSMBuilder3.0 is very different to the score calculated from MSMBuilder 3.3. I am wondering whether there was a big fix from 3.0 to 3.3 and which version should I trust?
Thanks.

**Comment by mpharrigan** [comment]
Can you provide a minimal working example? To my knowledge, there were no changes. Note that with cross validation GMRQ, there is a good deal of stochasticity

**Comment by rmcgibbo** [comment]
If you changed the `n_timescales`, or the code's default `n_timescales` changed, and you weren't actually specifying `n_timescales`, then you might get a change.

**Comment by gfzhou** [comment]
Thanks for the quick response. I tested it this morning and the inconsistency is due to the `n_timescales`. The default in 3.0 is 10 while 3.3 the default changed to `n_states - 1`. 
Thanks for the help and I will close the issue.
