### ISSUE TITLE
error when I run PCCA in msmbuilder 2.8.2

### ISSUE THREAD

**Issue by shabeir** [msmbuilder/msmbuilder#663]
Hi,

I got the following error when I run PCCA in msmbuilder 2.8.2:
```
alpha = scipy.optimize.anneal(
AttributeError: 'module' object has no attribute 'anneal'
```
Could you help me to solve it?

Thanks.

Best.

Beibei

**Comment by mpharrigan** [comment]
This repository is for msmbuilder >= 3. Version 2.8 is no longer supported but its repository can be found here: https://github.com/msmbuilder/msmbuilder-legacy

I believe scipy removed the anneal function. You could try downgrading scipy

**Comment by shabeir** [comment]
Thank you. How to downgrade scipy?

**Comment by rmcgibbo** [comment]
Depends how you installed scipy. If you use `conda`/anaconda, try `conda install scipy==0.13`.

**Comment by shabeir** [comment]
It works. Thanks very much.

**Comment by rmcgibbo** [comment]
Great.
