### ISSUE TITLE
cannot import name main

### ISSUE THREAD

**Issue by imanp** [msmbuilder/msmbuilder#668]
Just installed msmbuilder 3.3 and receive the following error

msmb -h
Traceback (most recent call last):
  File "/nethome/iman/anaconda/bin/msmb", line 4, in <module>
    from msmbuilder.scripts.msmb import main
ImportError: cannot import name main

Any ideas what might be causing this?

**Comment by mpharrigan** [comment]
How did you install msmbuilder? What commands did you use?

**Comment by imanp** [comment]
Used the conda install command as specified in the docs.

conda install -c https://conda.binstar.org/omnia msmbuilder

Works on my mac but not on an ubuntu machine i'm using.
What additional info do you need?

**Comment by mpharrigan** [comment]
I haven't seen this before. The error message implies it's not installed correctly or your `PYTHONPATH` isn't set properly
