### ISSUE TITLE
Periodic boundary conditions Issues 

### ISSUE THREAD

**Issue by juanmit** [msmbuilder/msmbuilder#670]
Hi All,

I am wondering are there any ways I can get rid of pbc issues when I build MSMs. I have been trying to use  trjconv  in gromacs but I do not have a tpr file now. Are there any other ways to solve it?
Thanks a lot.

**Comment by mpharrigan** [comment]
cc https://github.com/mdtraj/mdtraj/issues/956

All the analysis functions account for pbc, assuming your trajectories have box information in them
