### ISSUE TITLE
msmbuilder.org is hotel california

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#674]
You can use the back button any time you like, but you can never leave.

Pressing back from e.g. msmbuilder.org/3.3.0 moves you to http://msmbuilder.org which immediately redirects you to msmbuilder.org/3.3.0

cc #473 

@rmcgibbo do you know how to fix this?

**Comment by mpharrigan** [comment]
actually cc https://github.com/msmbuilder/msmbuilder/pull/614#issuecomment-147267213

**Comment by rmcgibbo** [comment]
http://stackoverflow.com/questions/1865837/whats-the-difference-between-window-location-and-window-location-replace

**Comment by rmcgibbo** [comment]
I think it should be `window.location.replace` instead of `window.location.assign` in the javascript.

**Comment by mpharrigan** [comment]
Changed it. Seems to have done the trick
