### ISSUE TITLE
Use alabaster theme?

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#686]
per openmm docs discussion everyone thinks msmb_theme/sphinx_rtd_theme is ugly and alabaster theme is nice. I don't disagree.

**Comment by mpharrigan** [comment]
preview: http://msmbuilder.org/alabaster/

We'd need to port the version selector code

**Comment by cxhernandez** [comment]
+1

**Comment by rmcgibbo** [comment]
+0.5. It looks pretty good, I agree, but I think the current version looks fine as well.

**Comment by msultan** [comment]
A slightly larger default font size would probably look a bit better imho.

**Comment by mpharrigan** [comment]
The font actually looks really whacky (small, italics-like) on my laptop / firefox / windows10.
