### ISSUE TITLE
conda installs build _1 not _2 - scikit-learn 0.16/0.17 / cluster.Ward

### ISSUE THREAD

**Issue by rafwiewiora** [msmbuilder/msmbuilder#694]
cc #692 
cc https://github.com/choderalab/ensembler/issues/59
cc @jchodera

`conda install msmbuilder` installs the 3.3.0-np110py27_1 rather than 3.3.0-np110py27_2 build, hence `cluster.Ward` issue, hence `conda install ensembler` leads to a non-functional installation.

**Comment by rmcgibbo** [comment]
We can just remove the `_1` builds from anaconda.org. The only difference between it and the `_2` build is the sklearn pinning -- the code is the same. cc @mpharrigan

**Comment by rmcgibbo** [comment]
I think the conda resolver is behaving properly here, but the outcome is a little unfortunate.

**Comment by mpharrigan** [comment]
What is the resolver doing? I don't think deleting the _1 will solve the problem. Won't it then just find the _0 or 3.2 if the resolver likes sklearn 0.17 so much?

**Comment by mpharrigan** [comment]
I can reproduce this in a clean environment. In my production environment, `conda update --all` resulted in the `_2` build being installed

**Comment by rmcgibbo** [comment]
Can or can't?

**Comment by mpharrigan** [comment]
I *can* reproduce with
```
conda create ...
source activate ...
conda install msmbuilder
```

**Comment by mpharrigan** [comment]
Then, in the new environment `conda update msmbuilder` doesn't do anything
`conda update msmbuilder --no-install-dependencies` will downgrade sklearn

**Comment by rafwiewiora** [comment]
`conda update msmbuilder` does nothing for me,  but `conda update msmbuilder --no-update-dependencies` downgrades ski-learn AND updates to the _2 build. I don't understand why it would do that.

**Comment by rmcgibbo** [comment]
Okay, I removed `osx-64/msmbuilder-3.3.0-py35np110_1` and `osx-64/msmbuilder-3.3.0-py35np110_0` as a test, and that leads to the proper result, in the sense that you get:

```
$ conda create -n _test msmbuilder python=3.5 numpy=1.10 msmbuilder
Fetching package metadata: ........
Solving package specifications: ...........................................
Package plan for installation in environment /Users/rmcgibbo/miniconda/envs/_test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    scikit-learn-0.16.1        |      np110py35_0         3.3 MB
    msmbuilder-3.3.0           |      np110py35_2         1.0 MB
    ------------------------------------------------------------
                                           Total:         4.3 MB
``` 

However, removing `osx-64/msmbuilder-3.3.0-py35np110_1` alone is insufficient -- it'll just take build 0.

**Comment by rmcgibbo** [comment]
The other solution would be to just make a `3.3.1` point release of msmbuilder, I guess.

**Comment by mpharrigan** [comment]
I'm backporting #685 onto a 3.3 branch https://github.com/msmbuilder/msmbuilder/tree/3.3 for a 3.3.1 release that fixes the underlying sklearn incompatibility

**Comment by jchodera** [comment]
Thanks!

**Comment by mpharrigan** [comment]
Conda package is out and seems to be working on my end

**Comment by rafwiewiora** [comment]
Confirmed, thanks guys!
