### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#697]
People analyze MSMs in different ways. This is a brainstorm of all the things people have done or might have done to look at their models.

 - tICA heatmap, maybe with hover conformations
 - microstate force directed layout, maybe colored by macrostates
 - implied timescales plot
 - structures, maybe color residues by tica component weight
 - energy landscapes
 - mfpt between paths, maybe interactive
 - movies along a tic
 - msm movies
 - sankey diagrams
 - chord diagrams for mutual information

The plan is to engineer msmbuilder to make these analysis tasks easy to perform. It should dump data that is consumable by an interactive visualization package spearheaded by @cxhernandez

**Comment by mpharrigan** [comment]
@msultan adds

 - error bars

**Comment by jchodera** [comment]
Awesome!

Two things that we have found useful:
* On tICA projections, plotting actual trajectories is often helpful for seeing if you actually have any trajectories that transition from one state to another state and actually commit to it.  @ChayaSt has some scripts for this she could share, and has found it to be very useful when figuring out when a dataset actually has no real transitions
* Similarly, extracting real trajectory subsets that connect two macrostates to look at the mechanism of interconversion can actually be useful

**Comment by jchodera** [comment]
Also, [seaborn](http://stanford.edu/~mwaskom/software/seaborn/) makes everything look prettified.

**Comment by msultan** [comment]
A few more random things 
* Integration with something like nglview for small scale analysis 
* Integration scripts for VMD for large scale analysis + some good defaults for visualization

**Comment by cxhernandez** [comment]
ugh, I'm gonna loathe having to write a python script that writes a TCL script....

**Comment by msultan** [comment]
If you go one level deeper and write a perl wrapper, we can put it next to the fah scripts.

**Comment by mpharrigan** [comment]
Thanks everyone. Let's get a good sense of what we want to visualize and then pick the best tools

**Comment by jchodera** [comment]
What about pymol?  There's even a conda-installable linux pymol in [omnia](https://anaconda.org/omnia/pymol/files) and I'm pretty close to getting the `osx` one to work.

**Comment by cxhernandez** [comment]
+1 for pymol. Just not sure how well it handles rendering thousands of structures compared to VMD.

**Comment by msultan** [comment]
Imo, VMD is better at handling trajectories, has a prettier GUI, and a simpler learner curve. Also @cxhernandez mentioned pymol has not been under active development for years now.

**Comment by cxhernandez** [comment]
>VMD is better at handling trajectories, has a prettier GUI

I question your opinion

**Comment by cxhernandez** [comment]
Additional thought/note-to-self: would be great if parts of this were incorporated into Osprey, as well.

**Comment by msultan** [comment]
>> VMD ... has a prettier GUI

>I question your opinion
>Also, the goal would be to do things in batch.

I think its easier to manipulate and play with trajectories in VMD especially since the two button version of pymol requires a lot of finessing. Also, I am not sure if all the varied rendering schemes especially surfaces and other stuff are present in pymol.

**Comment by mpharrigan** [comment]
Are there any other brainstorm ideas for what we want to visualize

**Comment by dr-nate** [comment]
>A few more random things
    Integration with something like nglview for small scale analysis
    Integration scripts for VMD for large scale analysis + some good defaults for visualization

+1

>Imo, VMD is better at handling trajectories, has a prettier GUI, and a simpler learner curve. Also @cxhernandez mentioned pymol has not been under active development for years now. 

+1. Like Dropbox, VMD is great only because everything else sucks worse.

**Comment by jchodera** [comment]
> +1 for pymol. Just not sure how well it handles rendering thousands of structures compared to VMD.

@steven-albanese has discovered that setting `defer_builds_mode` to 3 helps immensely:
http://www.pymolwiki.org/index.php/Defer_builds_mode

**Comment by jchodera** [comment]
> Also @cxhernandez mentioned pymol has not been under active development for years now.

PyMOL is under active development at Schrödinger:
http://www.schrodinger.com/pymol/

They are just slow in releasing updates to the open-source version.

**Comment by cxhernandez** [comment]
>@steven-albanese has discovered that setting defer_builds_mode to 3 helps immensely:
http://www.pymolwiki.org/index.php/Defer_builds_mode

:smiley:

**Comment by msultan** [comment]
> @steven-albanese has discovered that setting defer_builds_mode to 3 helps immensely:
http://www.pymolwiki.org/index.php/Defer_builds_mode

This kinda illustrates that there are a lot of different flags that need to be set for pymol for it to work.

**Comment by cxhernandez** [comment]
> This kinda illustrates that there are a lot of different flags that need to be set for pymol for it to work.

Which is why this tool (which would automatically set these for you) is useful.

**Comment by cxhernandez** [comment]
closing this as the conversation has continued in https://github.com/msmexplorer/msmexplorer/issues/1
