### ISSUE TITLE
Appveyor

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#715]
Having the CI just report failure on every PR is annoying. I want to

 - remove py < 3.5, so we don't have to do crazy environment setup to get old visualstudios to work
 - figure out the "unmet dependency" on 32 bit

**Comment by rmcgibbo** [comment]
I think https://github.com/ContinuumIO/anaconda-issues/issues/557

**Comment by mpharrigan** [comment]
It's supposed to be using numpy 1.10

**Comment by rmcgibbo** [comment]
Oh. Maybe try https://github.com/rmcgibbo/conda-hint and see what it says.

**Comment by mpharrigan** [comment]
It's pyhmc that's missing

**Comment by mpharrigan** [comment]
cc https://github.com/omnia-md/conda-recipes/pull/424
