### ISSUE TITLE
Move counts setup into a new mixin

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#718]
https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/msm/core.py#L29

is not related to the functionality of a mapping transformer; it should be a new mixin

**Comment by rmcgibbo** [comment]
I think the rate matrix code might be out of sync on how it handles ergodic triming, so this could help with that too

**Comment by mpharrigan** [comment]
I think @msultan may have addressed that (?) when he refactored everything into the mapping transformer; it's just not the right name imo

**Comment by rmcgibbo** [comment]
No I don't think so.

**Comment by msultan** [comment]
I only changed the msm and bayesian msm modules. The others are still using their respective counts code.

**Comment by mpharrigan** [comment]
Good to know. Then yes, let's move everything to the same counts implementation

**Comment by msultan** [comment]
closing this for now.
