### ISSUE TITLE
Get rid of references to mixtape

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/msmbuilder#730]
I first stumbled upon this in the [PCCA docstrings](https://github.com/msmbuilder/msmbuilder/blob/0183f0076535b3d34ba5038a2a528dc6f091ba6c/msmbuilder/lumping/pcca.py#L106): there are still quite a few [references to mixtape](https://github.com/msmbuilder/msmbuilder/search?utf8=%E2%9C%93&q=mixtape).

**Comment by mpharrigan** [comment]
This is still unfixed

**Comment by cxhernandez** [comment]
Oh woops. I though this was part of your sundry changes.
