### ISSUE TITLE
StrucRMSDFeaturizer and RMSDFeaturizer do the same thing

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#732]
https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/featurizer/featurizer.py#L205
https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/featurizer/featurizer.py#L892

cc #695 

Many apologies to @brookehus who was mislead into re-writing this featurizer :) Her code is probably better so we should use her code going forward.

I don't think we've made a release with `StrucRMSDFeaturizer` in it, so I propose throwing away existing `RMSDFeaturizer` and renaming `StrucRMSDFeaturizer` in its place (and adapting the order of arguments to make the api compatible)

**Comment by mpharrigan** [comment]
@brookehus notes that she could not discover the rmsdfeaturizer because it didn't show up on the command line #733

**Comment by brookehus** [comment]
I've addressed #734 on my own branch should I also address this one too with the same PR?

**Comment by mpharrigan** [comment]
:+1:

**Comment by mpharrigan** [comment]
This is somewhat important for the 3.4 release. We don't want to introduce a new api that will be removed shortly thereafter

**Comment by brookehus** [comment]
I can finish this up and the command line stuff by Friday.

**Comment by mpharrigan** [comment]
I think most of it is already there, so I'll finish this up

**Comment by mpharrigan** [comment]
closed by #764
