### ISSUE TITLE
Make sure everything is available on the command line

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#733]

**Comment by brookehus** [comment]
cc: @rmcgibbo should all the subset featurizers from [featurizer/subset_featurizer.py](https://github.com/msmbuilder/msmbuilder/blob/db27e6f8adfb6c3c3167f763c15581c57e318c90/msmbuilder/featurizer/subset_featurizer.py) show up in the command line? are these just normal featurizers?

**Comment by brookehus** [comment]
@rmcgibbo perhaps excluding the `SubsetCosPhiFeaturizer` and following; does `pass` in the code mean they are not implemented, or what does it mean otherwise?

**Comment by mpharrigan** [comment]
all the subset stuff shouldn't be included, see #738
