### ISSUE TITLE
return eigenvalue scalings for sparseTICA.transform

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/msmbuilder#742]
I've gotten better clustering/MSM results for my data after converting sparseTICA output into z-scores.

Is there any reason this hasn't been implemented?

**Comment by mpharrigan** [comment]
Why did you close this?

**Comment by rmcgibbo** [comment]
you should use the proper eigenvalue scaling from Frank + Cecilia's paper, not z-scores.

**Comment by cxhernandez** [comment]
@mpharrigan: I realized that z-scores didn't actually change the result (which makes sense in hindsight) and it was something I had implemented poorly.

@rmcgibbo: [This one](http://arxiv.org/abs/1506.06259)?

**Comment by rmcgibbo** [comment]
@cxhernandez yes.

**Comment by mpharrigan** [comment]
duplicate of #605
