### ISSUE TITLE
Change figshare links

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/msmbuilder#750]
In troubleshooting https://github.com/msmbuilder/msmbuilder/pull/748, I stumbled upon https://github.com/datacarpentry/R-ecology/issues/67#issue-137427152. Seems like we'll need to fix some links to download test data from figshare.

**Comment by rmcgibbo** [comment]
Okay, that looks pretty easy then. e.g. https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/example_datasets/met_enkephalin.py#L23

**Comment by cxhernandez** [comment]
yep! I'll submit a PR

**Comment by cxhernandez** [comment]
fixed in https://github.com/msmbuilder/msmbuilder/pull/751
