### ISSUE TITLE
Once-over on the docs

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#771]
Let's make a pass at the development docs before we release 3.4 cc #763 

I hacked this up quite a bit since 3.3. There's probably some typos or other low-hanging fruit improvements

http://msmbuilder.org/development/

**Comment by cxhernandez** [comment]
are we good on this?

**Comment by mpharrigan** [comment]
More people are welcome to take a look, but yeah. I probably won't cut the release until tomorrow so more doc fixes are welcome in that time
