### ISSUE TITLE
Too large or negative osprey model scores?

### ISSUE THREAD

**Issue by jadeshi** [msmbuilder/msmbuilder#777]
Has anyone used osprey and gotten scores greater than the theoretical maximum, or negative values? For 10 timescales, I'm getting scores ranging from 500 to -23. Should I just pick the best model with score less than the theoretical maximum of 11, or is this not recommended?

**Comment by rmcgibbo** [comment]
I think I've seen this anecdotally, but I never tracked it down. I would
recommend diving into the  code and y tying to figure out where it's coming
from. It could potentially be related to a numerical precision issue in the
matrix inverse, or maybe something else.

**Comment by cxhernandez** [comment]
> Should I just pick the best model with score less than the theoretical maximum of 11, or is this not recommended

It sounds like your dataset might not be converged enough for an MSM, but yeah I can't think of a reason not to try one of the models that's at least within the theoretical bounds

> diving into the code and trying to figure out where it's coming from.

@jadeshi: could you get the parameters and put together a test dataset that reproduces the wonky scores?

**Comment by jadeshi** [comment]
@cxhernandez I did some more digging and I think the issue is that my training and test sets sample different regions of conformational space, which screws up the GMRQ calculation. I think I may just not have enough data for some of my projects.
