### ISSUE TITLE
Version 3.5 release schedule

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#784]
Let's try to do more frequent releases. I propose 1/(2 months). Let's do the following schedule

 - March 30: development starts
 - May 16: feature freeze. release blockers only after this point
 - May 30: Release

**Comment by msultan** [comment]
i think 4 month is probably more apropos

**Comment by msultan** [comment]
development starts when the quarter starts and release happens at the end of quarter

**Comment by mpharrigan** [comment]
Quarters are 3 months. Let's try this schedule. It doesn't have to be a huge release, but it will let people stick to the conda packages and be able to use new features

**Comment by mpharrigan** [comment]
@msmbuilder/developers let's start identifying (and tagging with milestone) release blockers

**Comment by mpharrigan** [comment]
Going to do this today

**Comment by mpharrigan** [comment]
pypi

https://pypi.python.org/pypi/msmbuilder/3.5.0

**Comment by mpharrigan** [comment]
conda recipe pr (will get sent to "rc" channel)

https://github.com/omnia-md/conda-recipes/pull/541

**Comment by mpharrigan** [comment]
- [ ] check docs got built
- [ ] merge conda recipe
- [ ] test rc builds
- [ ] send email to mailing list
- [ ] update "creating a release" docs
- [ ] open thread for planning 3.6

**Comment by mpharrigan** [comment]
@msmbuilder/developers can you test the conda package (currently in the "rc" release candidate label)

```bash
conda install -c omnia/label/rc msmbuilder
```

**Comment by msultan** [comment]
is there some trick to getting the rc to work on macs? here is what i did but i am still seeing 3.4. i do have the repo cloned on the same machine but i would have thought conda would have overwritten that install. 

```
muneeb@DN51sk0p ~
$ which python
/Users/muneeb/Documents/anaconda/bin/python

muneeb@DN51sk0p ~
$ which conda
/Users/muneeb/Documents/anaconda/bin/conda

muneeb@DN51sk0p ~
$ conda install -c omnia/label/rc msmbuilder
Fetching package metadata .............
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /Users/muneeb/Documents/anaconda:
#
msmbuilder                3.5.0               np110py35_0    omnia/label/rc

muneeb@DN51sk0p ~
$ python -c "from msmbuilder.version import full_version; print(full_version)"
3.4.0.dev0.dev-dca7cf7
```

**Comment by cxhernandez** [comment]
>is there some trick to getting the rc to work on macs?

Did you remove the previous version?

**Comment by msultan** [comment]
trying to now, gonna see if that works. if its working on your mac, go ahead with the rc .

**Comment by mpharrigan** [comment]
Maybe you did `python setup.py develop` or `pip install -e .`. That might override conda install

**Comment by msultan** [comment]
Yea i might have done that at some point. The conda install is working on linux machines and updating to 3.5 correctly.

**Comment by cxhernandez** [comment]
Tests run fine on OSX

**Comment by mpharrigan** [comment]
Sorry everyone. I'm going to move this to the main channel now
