### ISSUE TITLE
[FR] Add possibility to featurized by binary "contacts" defined by a cutoff.

### ISSUE THREAD

**Issue by dr-nate** [msmbuilder/msmbuilder#790]
In the MSM field, there might be some confusion regarding the difference between the term "contacts" versus "distances", where

```
Distances = distance between atoms
Contacts = binary 0/1 value based upon whether an atom-atom distance was below a cutoff
```
The benefit of using contacts is that you can often use more features, as the 0/1 requires less memory, and it is less sensitive to slight changes in the system. This will also help us match up with the *de novo* structure prediction people who define it the same way, where a search of the PDB yielded 8Å as the magic cutoff for determining significant contacts for protein CAs, for example. 

Currently, the `ContactsFeaturizer` only supports distances. Implementing the distinction could possibly be done by either adding a `cutoff` argument to the `ContactsFeaturizer` as it is, or by having separate featurizers for the two.

This shouldn't require changes to any other parts of the code, as I believe tICA will work fine on either type of value.

**Comment by mpharrigan** [comment]
To realize the memory savings, we'd have to be careful with our numpy datatypes

**Comment by cxhernandez** [comment]
Do you think a logistic version of this could be useful as well ?

**Comment by Trayder** [comment]
This would be useful, I've been using binary contacts for a while as it has advantages for multi-body systems. And although its not much effort to convert a featurization into "binary", the current workflow does not play nice with integers so my 1's and 0's have been floats.

**Comment by jchodera** [comment]
Is tICA particularly efficient or scalable when the contacts are binary
beyond just the memory savings?

**Comment by dr-nate** [comment]
We used it pretty extensively in Gianni's group, and I believe Frank's
group does as well. I can't remember a time when we didn't have the
capability to do contacts+tica, and it had clear advantages with certain
application types like ligand binding. Perhaps distances would be
superior given more preprocessing like regularization, but that remains to
be shown IMO.

On Friday, April 8, 2016, John Chodera <notifications@github.com> wrote:

> Is tICA particularly efficient or scalable when the contacts are binary
> beyond just the memory savings?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/msmbuilder/msmbuilder/issues/790#issuecomment-207455375>
>


-- 
Sent from my phone.

**Comment by mpharrigan** [comment]
> the current workflow does not play nice with integers

Can you elaborate?

**Comment by mpharrigan** [comment]
answering my own question: it looks like tica's fit method casts to float64. Is there a reason for this?

**Comment by dr-nate** [comment]
Double precession is not necessary, and can be detrimental. tICA may accentuate really tiny and rare, but ultimately insignificant motions if too much precision is used. We previously dealt with this in the not-elegant way of just rounding to the nearest 0.1 Å with distances and degree with angles, but as I said regularization would probably be a better way to deal with this.

**Comment by cxhernandez** [comment]
Thought of a new featurizer for contacts/distances: it's be analogous to the `VonMisesFeaturizer` but, instead, using N gamma distributions at fixed distances apart for soft-binning. This is probably overkill though.

**Comment by mpharrigan** [comment]
For each distance pair?? `N^2` wasn't bad enough?

**Comment by cxhernandez** [comment]
lol I guess my system is pretty small....

**Comment by msultan** [comment]
@mpharrigan whats another O(N) between friends

**Comment by mpharrigan** [comment]
Implemented in gh-798
