### ISSUE TITLE
implement DPGHMM

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/msmbuilder#802]
This might help with future maintenance of the HMM code. We can rely on `hmmlearn` for the base class and just worry about our own [custom emmisions built from them](http://hmmlearn.readthedocs.org/en/latest/tutorial.html#implementing-hmms-with-custom-emission-probabilities).

**Comment by mpharrigan** [comment]
I think @peastman wrote some pretty good hmm code. Pretty sure there was a period of time when hmmlearn (split from scikit learn's hmm module) was unmaintained

**Comment by cxhernandez** [comment]
Ah, I see. Well then, let me make this as a request to implement HMMs using new mixture models found in scikit-learn, such as [DPGMM](http://scikit-learn.org/stable/modules/generated/sklearn.mixture.DPGMM.html#sklearn.mixture.DPGMM).

**Comment by mpharrigan** [comment]
As the emission distribution?
