### ISSUE TITLE
lumping objects make no sense

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/msmbuilder#803]
The transition matrix and other properties of macrostate model objects still return values corresponding to the microstate model they were fit to when using `from_msm`. This seems completely useless....

``` python
pccap = PCCAPlus.from_msm(msm, 6)
>>> msm.transmat_ is pccap.transmat_
True
```

**Comment by mpharrigan** [comment]
This was by design (although there was contention). I'm very open to changing it. 

For anyone reading this, the way you get a macrostate msm is
```python
pcca = PCCAPlus.from_msm(msm, 6)
macro_msm = MarkovStateModel().fit(pcca.transform(trajs))
```

**Comment by mohanpradhan** [comment]
Hi Matthew,

1) Can u suggest the code for building macrostate msm in msmbuilder3.8? This is how I think I can do. But please let me know if there is any easier way (similar to what you suggested above) to do this. 

pcca = PCCAPlus.from_msm(msm, n_macrostates=10)
pcca._do_lumping()
pcca.microstate_mapping_   # gives the mapping from microstates to macrostates

I can use this mapping array to convert microstates in ktrajs.values() to macrostates and then fit this to the msm model that I create.

2) Also, do I need to use the same parameters for building the markov state model that I used for microstates or do I need to find the optimal parameters for MSM again (and does this actually matter)? Above you fit the MSM with default parameters to the macrostates. I fit the below msm to the microstates-

msm = MarkovStateModel(lag_time=100, n_timescales=10, verbose=False) 
msm.fit(list(ktrajs.values()))_


Thanks.

**Comment by cxhernandez** [comment]
I believe this was resolved in #1036, right @brookehus?

**Comment by mohanpradhan** [comment]
i am not sure that i follow... but i am looking for the (1) code for building macrostate msms and (2) regarding parameters for building msm

**Comment by brookehus** [comment]
@cxhernandez that was for a different issue specifically with PCCA+ objective functions

@mohanpradhan, your code looks all right, but you will still need to actually build the MSM. You can use @mpharrigan's code above, where the second line builds a `macro_msm`. This `macro_msm` will have all the parameters of your new, macrostate MSM. The `pcca` object will have MSM parameters of your old, microstate MSM, such as `timescales_`.

For the macrostate MSM, it can be difficult to find one that is Markovian, so you should look at the implied timescales and see if you need a longer lag time for the macrostate MSM.

> do I need to find optimal parameters for MSM again

What do you mean by this?

**Comment by mohanpradhan** [comment]
Thanks for reply!

by optimal parameters for MSMS, i was referring to the parameters such as lag_time, n_timescales, etc... But you clarified my doubt- "The pcca object will have MSM parameters of your old, microstate MSM, such as timescales_"

So, the below code works well for me (assuming the assignments refer to the pcca.microstate_mapping_).

_pcca = PCCAPlus.from_msm(msm, n_macrostates=10)
pcca.do_lumping()
pcca.microstate_mapping # gives the mapping from microstates to macrostates
macro_msm = MarkovStateModel().fit(pcca.transform(pcca.microstate_mapping_))_

**Comment by brookehus** [comment]
Yes, that should be fine, and the `macro_msm` attributes will belong to your macrostate model.

**Comment by mohanpradhan** [comment]
Great! Thanks a lot!
