### ISSUE TITLE
create separate conda package for msmb test data

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/msmbuilder#805]
re: travis failures in https://github.com/msmbuilder/msmbuilder/pull/798

- [x] create repo ([msmbuilder/msmb_data](https://github.com/msmbuilder/msmb_data))
- [x] add to omnia conda channel (https://github.com/omnia-md/conda-recipes/pull/516)
- [x] integrate into msmbuilder tests

**Comment by cxhernandez** [comment]
Maybe this is a good use for Git LFS?

**Comment by mpharrigan** [comment]
I think it would be too much of a pain to install lfs support on travis, developer machines, et al. instead of just having it as a conda install

**Comment by mpharrigan** [comment]
Is this done?
