### ISSUE TITLE
Pipeline + RandomizedSearchCV workflow giving `ValueError: not enough values to unpack (expected 2, got 0)`

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/msmbuilder#806]
I've tried replicating the results from the [quadwell-n-states notebook](https://github.com/msmbuilder/msmbuilder/blob/master/examples/advanced/quadwell-n-states.ipynb) with my own MD simulations to do CV of the different hyperparameters in the models.

I can get a `Pipeline` + `RandomizedSearchCV` combination working with the `alanine_dipeptide` test dataset, but I fail when applying it to my data.

I've tried using both the `msmbuilder.dataset.dataset` the `md.iterload` functions to load my data in two different ways. I've put together a [notebook](https://github.com/jeiros/Jupyter_notebooks/blob/master/python/markov_analysis/gmrq-model-selection.ipynb) to show my workflow. Calling the `fit` method of the `RandomizedSearchCV` object on a `dataset` object or a list of `mdtraj.Trajectories` (not for the alanine_dipeptide trajectories) give the same ValueError. 

I don't understand why this fails with the `dataset` object because as is clear in the [introductory notebook](https://github.com/msmbuilder/msmbuilder/blob/master/examples/Intro.ipynb), the `fit_transform` method of a `DihedralFeaturizer` object works without problems on the `xyz` dataset.

I've checked that this is not caused by using the `fit` method of the `RandomizedSearchCV` object multiple times, as if I re-declare the object I still get the same errors.

I'm just copying here one of the error Tracebacks, in my [notebook](https://github.com/jeiros/Jupyter_notebooks/blob/master/python/markov_analysis/gmrq-model-selection.ipynb) there's the rest:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-9cadbe6b9742> in <module>()
      1 with timing("Cross-validation on my_trajs..."):
----> 2     my_scores = search.fit(my_trajs)

/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/grid_search.py in fit(self, X, y)
    994                                           self.n_iter,
    995                                           random_state=self.random_state)
--> 996         return self._fit(X, y, sampled_params)

/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/grid_search.py in _fit(self, X, y, parameter_iterable)
    551                                     self.fit_params, return_parameters=True,
    552                                     error_score=self.error_score)
--> 553                 for parameters in parameter_iterable
    554                 for train, test in cv)
    555 

/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py in __call__(self, iterable)
    798             # was dispatched. In particular this covers the edge
    799             # case of Parallel used with an exhausted iterator.
--> 800             while self.dispatch_one_batch(iterator):
    801                 self._iterating = True
    802             else:

/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py in dispatch_one_batch(self, iterator)
    656                 return False
    657             else:
--> 658                 self._dispatch(tasks)
    659                 return True
    660 

/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py in _dispatch(self, batch)
    564 
    565         if self._pool is None:
--> 566             job = ImmediateComputeBatch(batch)
    567             self._jobs.append(job)
    568             self.n_dispatched_batches += 1

/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py in __init__(self, batch)
    178         # Don't delay the application, to avoid keeping the input
    179         # arguments in memory
--> 180         self.results = batch()
    181 
    182     def get(self):

/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py in __call__(self)
     70 
     71     def __call__(self):
---> 72         return [func(*args, **kwargs) for func, args, kwargs in self.items]
     73 
     74     def __len__(self):

/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py in <listcomp>(.0)
     70 
     71     def __call__(self):
---> 72         return [func(*args, **kwargs) for func, args, kwargs in self.items]
     73 
     74     def __len__(self):

/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/cross_validation.py in _fit_and_score(estimator, X, y, scorer, train, test, verbose, parameters, fit_params, return_train_score, return_parameters, error_score)
   1548 
   1549     else:
-> 1550         test_score = _score(estimator, X_test, y_test, scorer)
   1551         if return_train_score:
   1552             train_score = _score(estimator, X_train, y_train, scorer)

/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/cross_validation.py in _score(estimator, X_test, y_test, scorer)
   1602     """Compute the score of an estimator on a given test set."""
   1603     if y_test is None:
-> 1604         score = scorer(estimator, X_test)
   1605     else:
   1606         score = scorer(estimator, X_test, y_test)

/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/metrics/scorer.py in _passthrough_scorer(estimator, *args, **kwargs)
    203 def _passthrough_scorer(estimator, *args, **kwargs):
    204     """Function that wraps estimator.score"""
--> 205     return estimator.score(*args, **kwargs)
    206 
    207 

/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/utils/metaestimators.py in <lambda>(*args, **kwargs)
     35             self.get_attribute(obj)
     36         # lambda, but not partial, allows help() to work with update_wrapper
---> 37         out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
     38         # update the docstring of the returned function
     39         update_wrapper(out, self.fn)

/Users/je714/anaconda3/lib/python3.5/site-packages/sklearn/pipeline.py in score(self, X, y)
    333         for name, transform in self.steps[:-1]:
    334             Xt = transform.transform(Xt)
--> 335         return self.steps[-1][-1].score(Xt, y)
    336 
    337     @property

/Users/je714/anaconda3/lib/python3.5/site-packages/msmbuilder/msm/msm.py in score(self, sequences, y)
    426 
    427         if self.mapping_ != m2.mapping_:
--> 428             V = self._map_eigenvectors(V, m2.mapping_)
    429             # we need to map this model's eigenvectors
    430             # into the m2 space

/Users/je714/anaconda3/lib/python3.5/site-packages/msmbuilder/msm/msm.py in _map_eigenvectors(self, V, other_mapping)
    445         self_inverse_mapping = {v: k for k, v in self.mapping_.items()}
    446         transform_mapping = _dict_compose(self_inverse_mapping, other_mapping)
--> 447         source_indices, dest_indices = zip(*transform_mapping.items())
    448 
    449         #print(source_indices, dest_indices)

ValueError: not enough values to unpack (expected 2, got 0)
```
Do you have any idea on what I might be doing wrong? Apologies is this is something related to scikit-learn.

**Comment by mpharrigan** [comment]
Hi @jeiros 

That's the error message we see when the test and train datasets don't overlap at all. E.g. your train data has transitions between states A and C and your test set only has transitions between D and E

Note to @msmbuilder/developers : we should have a much better error message here

This is somewhat related to the discussion here https://github.com/msmbuilder/msmbuilder/issues/787#issuecomment-205948623

Read through that comment and my response and see if it makes any sense. We usually suggest `ShuffleSplit` instead of `KFold` cross validation because we require both test and train to model the complete dynamics. Note that this implies you need to have *at least* twice as much data for cross validation as you need to build a converged msm. In practice, you *should* have like 10x the amount of data to get really solid results.

**Comment by jeiros** [comment]
Hey @mpharrigan thanks for the quick response!

Argh! Always with the damned sampling issue. It's going to take me ages to get that much data. Could I still in some crude way build a Markov Model on the data I have and obtain .rst (or pdb) structures from which is optimal to start new simulations? Granted, the trajectories I'm using have no water in them but I could re-solvate a proposed structure. 

Also, using the `dataset` as I intended above should work (as in, passing it to the `fit` method of a sklearn CV object), provided enough data is available for CV, right? Because I do have more data, this was just done to quickly test the functions.

I can try again with all the data I have, but it takes a long time, so I guess it doesn't hurt to ask first :)

**Comment by mpharrigan** [comment]
You can certainly build an MSM without doing cross validation by hand-picking the parameters. We use GMRQ cross validation on small systems for which we can get enough sampling to give us a good idea for "good" parameter choices for large systems where cross validation isn't feasible. 

Rules of thumb: dihedral featurizer, tica with 3-10 components, minibatchkmeans with a couple hundred states, msm with a lag time of around 1 ns

To seed new simulations, you can do "min counts" reseeding or "uniform" reseeding. Either pick structures uniformly among states, or pick structures from states that have the fewest transitions out of them

Getting structures from states is still pretty user-unfriendly (but we're working on it). Use `msmbuilder.utils.KDTree` to find data points closest to your cluster centers for the states you're interested in. It will return tuples of `(traj_i, frame_i)` indices. You really should go back to your raw trajectories (with water) and pull frames from them. If you resolvate, your system will have to equilibrate again before giving you meaningful data

**Comment by jeiros** [comment]
Thanks! I'll take that into account 😄

Btw, for what is worth, I also tried using your osprey software on the same dataset. I guess that also uses the GMRQ to do CV, but I wasn't getting any errors similar to the one on this issue.
