### ISSUE TITLE
Initialize n_components in KernelTICA.__init__

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/msmbuilder#817]
I got this error when using ktica in Osprey:

```
ValueError: Invalid parameter n_components for estimator KernelTICA. Check the list of available parameters with `estimator.get_params().keys()`.
```

**Comment by cxhernandez** [comment]
@mpharrigan: I'm confused why this would happen when `KernelTICA` inherits from `tICA`:

```python
   def __init__(self, kernel='rbf', degree=3, gamma=None, coef0=1., stride=1,
                 landmarks=None, random_state=None, kernel_params=None,
                 **kwargs):
    ...
    super(KernelTICA, self).__init__(**kwargs)
```

**Comment by mpharrigan** [comment]
re-read the error message. the voodoo magic of setting parameters in a pipeline inspects the constructor to figure out parameters. Since it's not there, it's not there

**Comment by cxhernandez** [comment]
stupid voodoo....

**Comment by mpharrigan** [comment]
Was this resolved?

**Comment by cxhernandez** [comment]
Not yet. I'll add it to https://github.com/msmbuilder/msmbuilder/pull/823

**Comment by cxhernandez** [comment]
done in https://github.com/msmbuilder/msmbuilder/pull/823
