### ISSUE TITLE
Version 3.6 Release Schedule

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#836]
Let's target a release for end of Q3

 - June 20 start development
 - Aug 20 feature freeze
 - Sep 20 release

**Comment by brookehus** [comment]
I have a personal goal to put my Ward stuff in this release

**Comment by cxhernandez** [comment]
How do @msmbuilder/developers feel about accelerating the v3.6 release? There's been quite a bit of work done already on documentation and stability, and it'd be nice to have this out in the wild ASAP.

**Comment by mpharrigan** [comment]
+1

**Comment by mpharrigan** [comment]
Feature freeze soon!

**Comment by brookehus** [comment]
😱

**Comment by msultan** [comment]
![](https://m.popkey.co/32e435/Q8Mlg.gif)

**Comment by mpharrigan** [comment]
Which I take to mean no more new feature PRs. Y'all good

**Comment by cxhernandez** [comment]
Is anyone opposed to releasing v3.6 a bit ahead of schedule? Loading data from figshare (using msmb v3.5) is slowing down testing in msmexplorer and mdentropy.... I'll try to finish up #885 and #890 today

**Comment by msultan** [comment]
Closing this now since we have the release . Wohoo!

**Comment by mpharrigan** [comment]
congratsemoji

**Comment by mpharrigan** [comment]
Devtools/readme left to do:

> Make sure there is a 3.(y+1) milestone already created
Create a new 3.(y+2) milestone [y is still the value of the release you just did]
Close the 3.y milestone.
Update this file (devtools/README.md) with anything you learned or changed during this release creation.
Open an Issue for 3.(y+1) release schedule.

**Comment by mpharrigan** [comment]
Plus encourage people to test release candidate conda build, and eventually move to main channel

**Comment by mpharrigan** [comment]
Bump

**Comment by cxhernandez** [comment]
They've worked for me on macOS

**Comment by mpharrigan** [comment]
Are they in the `rc` channel or the `main` channel?

**Comment by cxhernandez** [comment]
Still in `rc` as far as I know

**Comment by cxhernandez** [comment]
How do we change it? Just update the amnia recipe?

**Comment by mpharrigan** [comment]
No you have to go into the anaconda web interface. Do you want me to put them on main?

**Comment by cxhernandez** [comment]
Yeah. I'm not sure I have access to it.

**Comment by mpharrigan** [comment]
K. I put them on main
