### ISSUE TITLE
conda install in linux is not working

### ISSUE THREAD

**Issue by izaguirr** [msmbuilder/msmbuilder#839]
After installing Anaconda3 (which works) and then using
conda install -c omnia msmbuilder

I get
ImportError: No module named 'msmbuilder'

whether I run 
msmb -h
or 
import msmbuilder from within python

Is there any other step besides installing using "conda install -c omnia msmbuilder"

**Comment by cxhernandez** [comment]
Hi @izaguirr,

That's odd. I just tried installing `msmbuilder` on py34 using that same exact command and it worked. Just to be sure, could you confirm that there isn't a conflicting version of Python in your `$PATH` and that `$PYTHONPATH` is unset?

Also, would you mind posting the output of `conda list -e` here? This way I can try to reproduce your Anaconda environment.

Thanks!

**Comment by rmcgibbo** [comment]
Is anaconda Python in your PATH?

**Comment by izaguirr** [comment]
yeah, it was

it looks like the conda install is messing things up

I ended up installing mdtraj and other dependencies through pip, as well as
msmbuilder

it's working now. Not sure what the problem is with the conda install
