### ISSUE TITLE
pseudodihedral based clustering

### ISSUE THREAD

**Issue by poonampandey05** [msmbuilder/msmbuilder#846]
Hi,
I want to perform pseudodihedral based clustering of protein trajectories, obtained from simulation. I am following the following protocol:

#################################################

#1# Create an MSMBuilder Project
ConvertDataToHDF.py -s native.pdb -i XTC

#2# Cluster your data
Cluster.py rmsd hybrid -d 0.045 -l 50

#3# Validate microstate model with relaxation timescales
CalculateImpliedTimescales.py -l 1,25 -i 1 -o Data/ImpliedTimescales.dat
PlotImpliedTimescales.py -d 1. -i Data/ImpliedTimescales.dat

#4# Construct MSM at appropriate lagtime
BuildMSM.py -l 3

#5# Construct a Macrostate MSM
BuildMSM.py -l 1 -o L1
PCCA.py -n 4 -a L1/Assignments.Fixed.h5 -t L1/tProb.mtx -o Macro4/ -A PCCA+

#6# Examining the macrostate decomposition
python GetDihedrals.py --pdb native.pdb -a Macro4/MacroAssignments.h5 -n 1000
PCCA.py -n 4 -a L1/Assignments.Fixed.h5 -t L1/tProb.mtx -o Macro4/ -A PCCA+
sudo python GetDihedrals.py --pdb native.pdb -a Macro4/MacroAssignments.h5 -n 1000
python PlotDihedrals.py Dihedrals.h5
sudo python PlotDihedrals.py Dihedrals.h5

#7# Calculate Macrostate Implied Timescales
sudo CalculateImpliedTimescales.py -l 1,25 -i 1 -o Macro4/ImpliedTimescales.dat -a Macro4/MacroAssignments.h5 -e 3
sudo PlotImpliedTimescales.py -i Macro4/ImpliedTimescales.dat -d 1

#8# Visualizing Structures with Pymol
SaveStructures.py -s -1 -f pdb -S sep -a Macro4/MacroAssignments.h5
vmd PDBs/State0-0.pdb PDBs/State1-0.pdb PDBs/State2-0.pdb PDBs/State3-0.pdb
###############################################

But the first step (clustering) is based on RMSD. How can we use pseudodihedral based clustering to cluster the trajectory structures?

**Comment by mpharrigan** [comment]
Hi,
it looks like you're using msmbuilder 2. That version is no longer supported. One of the reasons why we re-wrote it for version 3 is msmbuilder's rigid pipeline that doesn't let you e.g. cluster based on dihedrals. I encourage you to check out the documentation for msmbuilder 3 and try to port your project
