### ISSUE TITLE
Start calling it "Feaure extraction" instead of "featurization"

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#861]
In the docs and elsewhere

ref: 
https://en.wikipedia.org/wiki/Feature_extraction
http://scikit-learn.org/stable/modules/feature_extraction.html

**Comment by mpharrigan** [comment]
One problem with this is that all the classes are `SomethingFeaturizer`

Looks like sklearn uses `SomethingVectorizer` which is still a made up word, and arguably less descriptive

**Comment by cxhernandez** [comment]
> One problem with this is that all the classes are SomethingFeaturizer

It should be fine. I think as long as the general organization of our API (e.g. `preprocessing`, `feature_extraction`) is analogous to sklearn's, we can take a few liberties in how the functions/classes are name without confusing users.

> Looks like sklearn uses SomethingVectorizer which is still a made up word, and arguably less descriptive

Yeah, definitely.

**Comment by msultan** [comment]
i mean why not keep it is as ```Featurizer``` and ```SomethingFeaturizer``` as it is now which imo is consistent. Deprecating ```Featurizer ``` for ```FeatureExtraction``` and then still sticking to ```SomethingFeaturizer``` is less consistent.

**Comment by mpharrigan** [comment]
> i mean why not keep it is as Featurizer and SomethingFeaturizer as it is now which imo is consistent. Deprecating Featurizer for FeatureExtraction and then still sticking to SomethingFeaturizer is less consistent. 

Right now, the package is `featurizer` and the classes are `SomethingFeaturizer` and the docs describe "Featurization"

Alternative one is to name the package `feature_extraction`, the classes `SomethingFeaturizer` and the docs describe "Feature Extraction"

Alternative two is to name the package `feature_extraction`, the classes `SomethingVectorizer` and the docs describe "Feature Extraction"

Although we're probably not going to do alternative two. @msultan : how does you opinion fit in with this framework?

**Comment by msultan** [comment]
If we are going to change, i would propose the following for consistency:

Name the package ```feature_extraction```, the classes ```SomethingFeatureExtractor``` and the docs describe it as "Feature Extraction". 

Its descriptive and somewhat in line with sklearn

**Comment by mpharrigan** [comment]
I don't think there's any benefit to (1) changing the class names to (2) something no one else uses

**Comment by cxhernandez** [comment]
`XYZFeatureExtractor` would at least be consistent with the module name, but I'm not picky either way. It's probably good enough to just switch to `feature_extractor` now and then worry about the class names later if we need to.

**Comment by msultan** [comment]
I think if we are going to switch, we should switch over completely and have a consistent naming scheme.

**Comment by brookehus** [comment]
Why don't we put it on a v4 wishlist?

**Comment by mpharrigan** [comment]
I'm starting to think there aren't compelling reasons to switch from what we've been calling it

It would be worth checking tensorflow, R machine learning packages, cpp machine learning packages to see how they talk about this stuff

**Comment by mpharrigan** [comment]
Specifically, if there isn't a strong convention, then we shouldn't go through the angst of making changes

**Comment by mpharrigan** [comment]
> if there isn't a strong convention, then we shouldn't go through the angst of making changes

Closing this issue for the above reason
