### ISSUE TITLE
KTICA with RMSD featurizer

### ISSUE THREAD

**Issue by msultan** [msmbuilder/msmbuilder#863]
I am not sure how to use KTICA with the RMSD featurizer when i give it a bunch of landmarks. Anyone have any scripts floating around? its probably a good idea to stick that on the docs somewhere as well.

**Comment by mpharrigan** [comment]
From #768 

https://github.com/mpharrigan/mixtape/blob/6d170fabe1dde631ab72bc45ce0ff4638273acde/msmbuilder/project_templates/landmarks/featurize.py
