### ISSUE TITLE
[Question] About msm lag time optimization with GMRQ

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/msmbuilder#912]
I've been reading through your [tutorial](http://msmbuilder.org/3.6.0/tutorial.html) and I would like to ask for clarification about the following statement in point 16:
```
The MSM lag-time is a parameter that cannot be optimized using gmrq.
```
I've been using Osprey to find good hyperparameters for my system and I have introduced it as part of my search space. I was actually going to open an issue asking about the following trend:
<img width="400" alt="screen shot 2016-09-28 at 19 34 20" src="https://cloud.githubusercontent.com/assets/10696140/18927148/98ea1f24-85b2-11e6-898c-969f5b065b2d.png">
Do you have any idea why there is such a negative correlation? Other parameters like the tICA lag time and the number of clusters seem to be more random.

I know that one can plot the relationship between the implied timescales and the lag time of the MSM (and that a sufficiently long lag time should be picked so that they have stabilised). But this is a never ending loop, because to reach this stage one must have already picked the tICA and clustering parameters.

If I run several Osprey optimisation runs with different MSM lag times, is this not basically introducing the lag time in the hyperparameter search?

I would appreciate any tips on how do you approach this problem :)

**Comment by mpharrigan** [comment]
This is a good question. I wanted to write some math, so I answered [here](http://mpharrigan.com/2016/09/29/gmrq.html)

Let me know if you have any questions

**Comment by jeiros** [comment]
Nice! I understand now why there is a decay of the score with larger lag times.
In practice though, is the implied timescales plot useful *before* or *after* the hyperparameter cross validation has been performed?

I'm thinking about:
- Hand pick some parameters
- Do an implied timescales plot
- Select lag time at which slowest timescale plateaus
- Optimize T at the chosen lag time with Osprey

Thanks for taking the time of showing this with a bit of math! It was a good read 😄

**Comment by mpharrigan** [comment]
That sounds like a good protocol to me
