### ISSUE TITLE
Add test for #920

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/msmbuilder#921]
Just a reminder for when we release v3.7

re: https://github.com/msmbuilder/msmbuilder/pull/920

**Comment by brookehus** [comment]
Was this done in #920? It appears to be changelogged but are tests needed? @mpharrigan can you advise?

**Comment by mpharrigan** [comment]
@cxhernandez can take care of it, if need be

**Comment by brookehus** [comment]
@cxhernandez what needs to be done here?

**Comment by cxhernandez** [comment]
Add a test to ensure that the order of the inputted featurizer list is preserved.

**Comment by cxhernandez** [comment]
done in #961
