### ISSUE TITLE
implement commute maps

### ISSUE THREAD

**Issue by msultan** [msmbuilder/msmbuilder#924]
Frank and Cecilia have a new paper 

http://pubs.acs.org/doi/pdf/10.1021/acs.jctc.6b00762 which is supposed to be a superior version of kinetic mapping. Based upon an initial reading, the critical equation is (13) and comes down to scaling eigenvectors by ```sqrt(timescale/2)``` instead of  the eigenvalues. The advantage is that distance metric has units of "time" and is, based upon the paper, the commute time between conformations. It also seemingly integrates out the lagtime without having to calculate an infinite number of time lagged correlation.

**Comment by jchodera** [comment]
FYI, @maxentile recently implemented this into pyemma:
https://github.com/markovmodel/PyEMMA/pull/963

**Comment by msultan** [comment]
ahh thanks for pointing this out @jchodera.

**Comment by msultan** [comment]
Done in #925
