### ISSUE TITLE
Version 3.7 Release Schedule

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#927]
Let's target a release for end of Q4
- Sep 20 start development
- Nov 20 feature freeze
- Dec 20 release

**Comment by mpharrigan** [comment]
@msmbuilder/developers let's start fixing any outstanding issues in preparation for release

**Comment by cxhernandez** [comment]
I think we're go to go for this release!

**Comment by brookehus** [comment]
will do tomorrow!

**Comment by brookehus** [comment]
Done in #962
