### ISSUE TITLE
AttributeError: module 'mdtraj' has no attribute 'join'

### ISSUE THREAD

**Issue by dart4869** [msmbuilder/msmbuilder#938]
Hi, 

I have 'mdtraj' updated to the latest version and I'm not sure why I got the following error when going through the tutorial provided on the MSMbuilder website: 

"/Applications/anaconda/envs/snakes/lib/python3.5/site-packages/mdtraj/formats/pdb/pdbfile.py:196: UserWarning: Unlikely unit cell vectors detected in PDB file likely resulting from a dummy CRYST1 record. Discarding unit cell vectors.
  warnings.warn('Unlikely unit cell vectors detected in PDB file likely '
Traceback (most recent call last):
  File "rmsd.py", line 19, in <module>
    rmsds = {k: md.rmsd(traj, ref) for k, traj in itertrajs(meta)}
  File "rmsd.py", line 19, in <dictcomp>
    rmsds = {k: md.rmsd(traj, ref) for k, traj in itertrajs(meta)}
  File "/Applications/anaconda/envs/snakes/lib/python3.5/site-packages/msmbuilder/io/io.py", line 148, in itertrajs
    yield i, md.join(md.iterload(row['traj_fn'],
AttributeError: module 'mdtraj' has no attribute 'join'"

Does anyone encounter this problem before? Any suggestions would be much appreciated.

**Comment by rmcgibbo** [comment]
mdtraj does not have a function in the main namespace named `join`. there is a method on the `Trajectory` object called join...

**Comment by dart4869** [comment]
I see. The function `join` is not in the main namespace in MDTraj version 1.7.2, but in 1.8.0 version `join` is actually included in the main namespace. Does anyone know how to install MDTraj 1.8.0, which is shown as dev0 on the website? Since the MSM tutorial is written based on MDTraj 1.8.0, can you guys share the installation files of MDTraj 1.8.0? Thanks~

**Comment by cxhernandez** [comment]
@dart4869 try:

```
pip install git+git://github.com/mdtraj/mdtraj.git#egg= mdtraj
```
