### ISSUE TITLE
Appveyor stuck on queued

### ISSUE THREAD

**Issue by mpharrigan** [msmbuilder/msmbuilder#939]
Cancelling / restarting doesn't help! I'm going to delete the appveyor "project" and start again

**Comment by msultan** [comment]
Should we try emailing their support or something first?

**Comment by cxhernandez** [comment]
I tweeted at them

**Comment by cxhernandez** [comment]
@mpharrigan: [Appveyor responded](https://twitter.com/appveyor/status/795829327203942400)

Try a new build?

**Comment by mpharrigan** [comment]
retrigged

**Comment by mpharrigan** [comment]
(You all should also be able to re-run pr's )

**Comment by mpharrigan** [comment]
Thanks for the tweeting @cxhernandez
