### ISSUE TITLE
HMM.predict() does not work after the HMM has been dumped and loaded

### ISSUE THREAD

**Issue by Trayder** [msmbuilder/msmbuilder#949]
It works as expected after the HMM is initially generated.
```
utils.dump(HMM, "HMM")
HMM = utils.load("HMM")
HMM.predict(tica_transformed)
```
>  ---------------------------------------------------------------------------
> MemoryError                               Traceback (most recent call last)
> <ipython-input-13-63e10eaf5d87> in <module>()
> ----> 1 HMM.predict(tica_transformed)
> 
> msmbuilder/hmm/gaussian.pyx in msmbuilder.hmm.gaussian.GaussianHMM.predict (msmbuilder/hmm/gaussian.cpp:13348)()
> 
> msmbuilder/hmm/gaussian.pyx in msmbuilder.hmm.gaussian.GaussianHMM._predict_double (msmbuilder/hmm/gaussian.cpp:14441)()
> 
> MemoryError: std::bad_alloc

I'm using the following code (from HMM.draw_samples) as a workaround to get state assignments for each sequence. Should I expect the results to differ?
Thanks,
-Trayder
```
from sklearn import mixture
logprob = [
    mixture.log_multivariate_normal_density(
    x, HMM.means_, HMM.vars_, covariance_type='diag'
    ) for x in tica_transformed]
ass = [lp.argmax(1) for lp in logprob]
```

**Comment by cxhernandez** [comment]
#996
