### ISSUE TITLE
Version 3.8 Release Schedule [TBD]

### ISSUE THREAD

**Issue by brookehus** [msmbuilder/msmbuilder#964]
Target date TBD

**Comment by cxhernandez** [comment]
Let's target the release for end of this week (since we're so behind)?
- Apr 12 feature freeze
- Apr 14 release

**Comment by brookehus** [comment]
Done in #1000

**Comment by mpharrigan** [comment]
Do conda forge!

**Comment by brookehus** [comment]
@mpharrigan where do you get the sha256

**Comment by mpharrigan** [comment]
compute it with `sha256sum`

**Comment by cxhernandez** [comment]
Add that to devtools docs plz

**Comment by brookehus** [comment]
and the argument should be the file i'm listing [here](https://github.com/conda-forge/msmbuilder-feedstock/pull/1/files#diff-e178b687b10a71a3348107ae3154e44cR11)?
