### ISSUE TITLE
msmbuilder.io.preload_tops can't load prmtops

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/msmbuilder#966]
I'm experimenting with `msmb TemplateProject`. I use AMBER to run MD so my topology files are `.prmtop` and the trajectories end with `.nc`.

Since the topology is referenced as `top.pdb` throughout the template, I've renamed the `prmtop` file to end with a `.pdb` (a bit ugly, but still a prmtop) and succesfully generated a metadata pickle file for the project.

Something is going wrong when I'm trying out the `featurize.py` script (in the `dihedrals` folder). In particular, this is what's crashing:
```python
import mdtraj as md

from msmbuilder.featurizer import DihedralFeaturizer
from msmbuilder.io import load_meta, preload_tops, save_trajs, save_generic
from multiprocessing import Pool

## Load
meta = load_meta()
tops = preload_tops(meta)
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "featurize.py", line 20, in <module>
    tops = preload_tops(meta)
  File "/Users/je714/anaconda3/envs/msmbuilder/lib/python3.5/site-packages/msmbuilder/io/io.py", line 112, in preload_tops
    tops[tfn] = md.load_topology(tfn)
  File "/Users/je714/anaconda3/envs/msmbuilder/lib/python3.5/site-packages/mdtraj/core/trajectory.py", line 150, in load_topology
    return _parse_topology(filename, **kwargs)
  File "/Users/je714/anaconda3/envs/msmbuilder/lib/python3.5/site-packages/mdtraj/core/trajectory.py", line 169, in _parse_topology
    _traj = load_frame(top, 0, **kwargs)
  File "/Users/je714/anaconda3/envs/msmbuilder/lib/python3.5/site-packages/mdtraj/core/trajectory.py", line 311, in load_frame
    return loader(filename, frame=index, **kwargs)
  File "/Users/je714/anaconda3/envs/msmbuilder/lib/python3.5/site-packages/mdtraj/formats/pdb/pdbfile.py", line 153, in load_pdb
    with PDBTrajectoryFile(filename, standard_names=standard_names) as f:
  File "/Users/je714/anaconda3/envs/msmbuilder/lib/python3.5/site-packages/mdtraj/formats/pdb/pdbfile.py", line 269, in __init__
    self._read_models()
  File "/Users/je714/anaconda3/envs/msmbuilder/lib/python3.5/site-packages/mdtraj/formats/pdb/pdbfile.py", line 557, in _read_models
    self._topology.create_disulfide_bonds(self.positions[0])
IndexError: index 0 is out of bounds for axis 0 with size 0
---------------------------------------------------------------------------
```
I've also tried `preload_top`, with the same error. [This](https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/io/io.py#L112) and [this](https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/io/io.py#L136) lines are that are crashing (`md.load` can't read a prmtop, it seems).

I've fixed this in my script by redefining the faulty function:
```python
def preload_top(meta):
    top_fns = set(meta['top_fn'])
    if len(top_fns) != 1:
        raise ValueError("More than one topology is used in this project!")
    return md.load_prmtop(top_fns.pop())
```

Maybe this could be avoided by tweaking how the `TemplateProject` is built? Haven't found out how that's possible. Also if you want I can fix this on a PR, catching the error and using `md.load_prmtop`, but not sure if that's a great idea since there are different kind of topologies (only use AMBER myself).

**Comment by mpharrigan** [comment]
ok: https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/io/io.py#L136 should use load_topology like https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/io/io.py#L112. But load_topology depends on the file extension being accurate

**Comment by mpharrigan** [comment]
Which you should just change here for your project in the generated scripts https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/project_templates/analysis/gather-metadata.py#L17

**Comment by jeiros** [comment]
Thanks for the quick help! 👍

**Comment by jeiros** [comment]
Just a question, though: even if I change the file extensions in [gather-metadata.py](https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/project_templates/analysis/gather-metadata.py) to match mine, the `msmb TemplateProject` still generates a tree of directories which have symlinks to `top.pdb`. Where can I change that behaviour?

**Comment by mpharrigan** [comment]
Ah, that is unfortunate. I'll have to think about how to do this better
