### ISSUE TITLE
GMRQ/tICA documentation typo?

### ISSUE THREAD

**Issue by RobertArbon** [msmbuilder/msmbuilder#973]
Hi, 

The documentation for tICA reads:

There are two parameters introduced in the tICA method. The first is Δt, which is used in the calculation of the time-lag correlation matrix (C(Δt)). The second is n, which is the number of tICs to project onto when calculating distances between conformations. **You can use the GMRQ score to choose these parameters. Typical values are of order nanoseconds and tens, respectively.**

This seems to say that you can tune your tICA lag time as well as the number of components using GMRQ.  But as I understand it, GMRQ decreases with lag time and is not logically able to be optimised using GMRQ.   For example calculating the tICA GMRQ score for different tICA lag times with the double well potential from the [tICA/PCA example](http://msmbuilder.org/3.7.0/examples/tICA-vs-PCA.html): 

![image](https://cloud.githubusercontent.com/assets/7603520/23726639/e20cd174-044c-11e7-9d73-82df9f7b370f.png)

Can I have some clarification on this issue please?

Thanks

Rob

**Comment by mpharrigan** [comment]
If tICA is used as an intermediate dimensionality reduction (typical use), you can select both parameters by doing GMRQ cross validation over the final MSM's score. Note that you have to fix the MSM lag time in this case.

If tICA is your final kinetic model, you're correct that you can no longer use GMRQ cross validation to select the tICA lag time.

We should clarify the docs

**Comment by RobertArbon** [comment]
Thanks, that makes sense actually.
