### ISSUE TITLE
IC corresponding to features

### ISSUE THREAD

**Issue by liyigerry** [msmbuilder/msmbuilder#974]
Hi,

I extracted features and employed the tICA on the trajectories. How can I get feature corresponding to the top ICs, e.g. IC0, IC1.

Thanks.

**Comment by msultan** [comment]
Depending on your featurizer object, the following script should work. 

```  python
import pandas as pd
import mdtraj as md
import numpy as np
from msmbuilder.featurizer import DihedralFeaturizer

#get random topology 
trj = md.load("top.pdb")
#setup a featurizer object
feat = DihedralFeaturizer()
#get a pandas dataframe to describe features
df =  pd.DataFrame(feat.describe_features(trj))

#suppose we wanna know the top 3 import features for the 0th tic/IC/PC/whatever. 
#i am also assuming that the tica_mdl contains your tica object. 
tic_index=0
wanted_inds=3
#arg sort the absolute of the component. 
important_feature_inds = np.argsort(abs(tica_mdl.components_[tic_index,0]))[-wanted_inds:]

df_important = df.iloc[important_feature_inds]
```
The ```df_important``` pandas dataframe has all the necessary features now.

**Comment by msultan** [comment]
we really should put this in the docs somewhere too.

**Comment by liyigerry** [comment]
@msultan Thanks for your rapid. Yes, better docs will be more helpful.

**Comment by liyigerry** [comment]
@msultan It does not seem to work.

`abs(tica_mdl.components_[tic_index,0])`: get IC0?
output: `-0.0024364545853644962`
`np.argsort(abs(tica_mdl.components_[tic_index,0]))`: sort what?
output: `array([0])`.

I just run the code, and got this result.

| atominds | featuregroup | featurizer	| otherinfo	resids | resnames | resseqs |
| ---------|--------------|-------------|------------------|----------|---------|
| [5, 7, 8, 14] | phi | Dihedral | sin | [0, 1] | [GLU, VAL] | | [1, 2] |

**Comment by msultan** [comment]
oh sorry about that, its supposed to be ```np.argsort(abs(tica_mdl.components_[tic_index,:]))```(: instead of 0) This argsorts the entire component vector along that dimension.

**Comment by liyigerry** [comment]
Ok, that's right and more clear. Thanks.
