### ISSUE TITLE
Add py36 to CI tests

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/msmbuilder#988]
@msmbuilder/developers: How do y'all feel about adding another test to the matrix? Should we drop testing on py27 as well?

**Comment by brookehus** [comment]
I think 3.6 is good but suspect there are still many users with 2.7, wouldn't drop those tests until we formally end support for 2.7

**Comment by cxhernandez** [comment]
also related to https://github.com/msmbuilder/msmbuilder/issues/852

**Comment by cxhernandez** [comment]
Unfortunately, I can't find anything related to when `sklearn` might drop py2 support. But many important packages, like `pandas` and `matplotlib`, have signed the petition @mpharrigan mentioned.

**Comment by cxhernandez** [comment]
done in #990
