### ISSUE TITLE
Warning/error in tICA when N>p

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#994]
With the default shrinkage covariance matrix estimator, no warning or error is thrown when the number of data points, N, is less than the number of features. But very frequently, the largest eigenvalue can be greater than 1. Without the shrinkage estimator, you'd get a linear algebra error from the covariance matrix not being positive definite in this situation. Perhaps a warning or error would be appropriate here.

```
In [177]: tICA(n_components=1).fit([np.random.RandomState(0).randn(9,10)]).eigenvalues_                                                                                    
Out[177]: array([ 1.26276845])

In [178]: tICA(n_components=1).fit([np.random.RandomState(0).randn(9,10)]).timescales_                                                                                     
Out[178]: array([-4.28620728])
```

**Comment by cxhernandez** [comment]
done in #998
